/* IELTS full mock exam. Own session and shell; specialized practice remains in app-23. */
let ieltsFullTimer=null,ieltsFullSpeechToken=0;
const ieltsFullSections=['listening','reading','writing'];
function ieltsFullSession(){return state.examEngine.ieltsFullSession||null}
function saveIeltsFull(){save({immediate:true,refresh:false})}
function startIeltsFullMock(mockId){const mock=customMock(mockId);if(!customMockReady(mock))return toast('此模拟卷的资料尚未齐全');const old=ieltsFullSession();
  if(old&&old.mockId===mockId&&old.section!=='finished'){sessionStorage.setItem('ieltsFullActive',mockId);return nav('ielts-full-exam')}
  if(old&&old.section!=='finished'&&!confirm('开始另一套将覆盖未完成的机考。确定继续吗？'))return;
  const now=Date.now();state.examEngine.ieltsFullSession={mockId,section:'listening',startedAt:now,deadline:now+30*60000,indices:{listening:0,reading:0},answers:{listening:{},reading:{}},flags:{listening:{},reading:{}},drafts:{writing1:'',writing2:''},writingTab:'writing1',results:{},completedAt:null};saveIeltsFull();sessionStorage.setItem('ieltsFullActive',mockId);nav('ielts-full-exam')}
function ieltsFullQuestions(session){const mock=customMock(session.mockId),item=session.section==='listening'?customListening(mock.listeningId):customReading(mock.readingId);return buildCustomExamQuestions(session.section,item)}
function ieltsFullScore(session,section){const mock=customMock(session.mockId),item=section==='listening'?customListening(mock.listeningId):customReading(mock.readingId);return buildCustomExamQuestions(section,item).reduce((n,q)=>n+Number(isObjectiveAnswerCorrect(q,session.answers[section][q.id]||'')),0)}
function ieltsFullFinishSection(automatic=false){const session=ieltsFullSession();if(!session||!ieltsFullSections.includes(session.section))return;
  if(!automatic&&!confirm('提交本部分后不能返回修改。确定提交吗？'))return;
  const old=session.section;if(old==='listening'||old==='reading')session.results[old]=ieltsFullScore(session,old);
  else session.results.writingSaved=true;
  const next={listening:'reading',reading:'writing',writing:'finished'}[old];session.section=next;session.deadline=next==='finished'?null:Date.now()+(next==='writing'?60:next==='reading'?60:30)*60000;
  if(next==='finished'){session.completedAt=Date.now();sessionStorage.removeItem('ieltsFullActive')}saveIeltsFull();const box=$('#ieltsFullWorkspace');if(box)box.dataset.section='';renderIeltsFullExam()}
function ieltsFullClock(){clearInterval(ieltsFullTimer);const update=()=>{const session=ieltsFullSession();if(!session||session.section==='finished')return clearInterval(ieltsFullTimer);const remain=Math.max(0,session.deadline-Date.now()),clock=$('#ieltsFullClock');if(clock)clock.textContent=`${String(Math.floor(remain/60000)).padStart(2,'0')}:${String(Math.floor(remain%60000/1000)).padStart(2,'0')}`;if(remain===0){clearInterval(ieltsFullTimer);ieltsFullFinishSection(true)}};update();ieltsFullTimer=setInterval(update,1000)}
function ieltsFullStopAudio(){ieltsFullSpeechToken++;if('speechSynthesis'in window)speechSynthesis.cancel();$('#ieltsFullAudio audio')?.pause()}
function ieltsFullAudio(item,part){const area=$('#ieltsFullAudio'),key=item.id+':'+part.number;if(!area||area.dataset.part===key)return;ieltsFullStopAudio();area.dataset.part=key;
  if(part.audioUrl){area.innerHTML=`<p class="sub">Part ${part.number} · 预录 TTS 音频</p><audio controls preload="metadata" src="${esc(part.audioUrl)}"></audio>`;return}
  area.innerHTML=`<p class="sub">Part ${part.number} · 设备 TTS 音频模拟</p><button class="btn" id="ieltsFullPlay">▶ 播放此 Part</button><button class="btn" id="ieltsFullStop">■ 停止</button>`;
  $('#ieltsFullPlay').onclick=()=>{if(!('speechSynthesis'in window))return toast('设备不支持语音合成');ieltsFullStopAudio();const token=ieltsFullSpeechToken;let pos=0;const play=()=>{if(token!==ieltsFullSpeechToken||pos>=part.lines.length)return;const line=part.lines[pos++],speech=new SpeechSynthesisUtterance(line.text);speech.lang='en-GB';speech.rate=.92;speech.onend=()=>{if(token===ieltsFullSpeechToken)setTimeout(play,Math.min(30000,line.pauseAfterMs||0))};speechSynthesis.speak(speech)};play()};$('#ieltsFullStop').onclick=ieltsFullStopAudio}
function ieltsFullRenderResult(session,mock,box){clearInterval(ieltsFullTimer);box.innerHTML=`<article class="card ielts-full-result"><span class="practice-label">${esc(mock.label)} · L/R/W 结果</span><h2>笔试已完成</h2><p>Listening ${session.results.listening} / 40</p><p>Reading ${session.results.reading} / 40</p><p>Writing Saved</p><div class="row"><button class="btn" id="ieltsFullCopy">复制题目与我的作文</button><button class="btn primary" id="ieltsFullSpeaking">开始 Speaking Test · ${esc(mock.speakingSetId)}</button><button class="btn" id="ieltsFullBack">返回题库</button></div></article>`;
  $('#ieltsFullCopy').onclick=async()=>{const t1=customOpen.writingTask1.find(t=>t.id===mock.writingTask1Id),t2=customOpen.writingTask2.find(t=>t.id===mock.writingTask2Id);const text=`Task 1\nQuestion: ${t1.prompt}\nMy Answer: ${session.drafts.writing1}\n\nTask 2\nQuestion: ${t2.prompt}\nMy Answer: ${session.drafts.writing2}`;try{await navigator.clipboard.writeText(text);toast('题目与作文已复制')}catch{toast('复制失败，请检查浏览器剪贴板权限')}};
  $('#ieltsFullSpeaking').onclick=()=>openCustomWork('speaking',mock.speakingSetId,mock.id);$('#ieltsFullBack').onclick=()=>nav('ielts-custom')}
async function renderIeltsFullExam(){const box=$('#ieltsFullWorkspace');if(!box)return;const session=ieltsFullSession();if(!session){nav('ielts-custom');return}try{await loadIeltsCustom()}catch(error){box.textContent='题库加载失败：'+error.message;return}const mock=customMock(session.mockId);if(!customMockReady(mock)){box.textContent='此模拟卷的题目不完整';return}if(session.section==='finished')return ieltsFullRenderResult(session,mock,box);
  if(session.deadline<=Date.now()){ieltsFullFinishSection(true);return}
  if(box.dataset.section!==session.section){ieltsFullStopAudio();box.dataset.section=session.section;box.innerHTML=`<div class="ielts-full-top"><div><span class="practice-label">${esc(mock.label)} · IELTS EXAM MODE</span><h2 id="ieltsFullSection"></h2><p class="sub" id="ieltsFullProgress"></p></div><div class="row"><strong class="exam-clock" id="ieltsFullClock">00:00</strong><button class="btn" id="ieltsFullExit">退出考试</button><button class="btn primary" id="ieltsFullSubmit">提交本部分</button></div></div><div id="ieltsFullNavigator" class="exam-number-nav"></div><div class="ielts-full-panes"><article class="card ielts-full-source"><div id="ieltsFullSource"></div><div id="ieltsFullAudio"></div></article><article class="card ielts-full-question"><div id="ieltsFullQuestion"></div><div class="row between"><button class="btn" id="ieltsFullPrevious">← 上一题</button><button class="btn" id="ieltsFullFlag">标记 Review</button><button class="btn" id="ieltsFullNext">下一题 →</button></div></article></div>`;
    $('#ieltsFullExit').onclick=()=>{if(confirm('退出机考？答卷和剩余时间会保留，计时不会暂停。')){ieltsFullStopAudio();clearInterval(ieltsFullTimer);saveIeltsFull();sessionStorage.removeItem('ieltsFullActive');nav('ielts-custom')}};$('#ieltsFullSubmit').onclick=()=>ieltsFullFinishSection(false)}
  const section=session.section;$('#ieltsFullSection').textContent={listening:'Listening · 30 分钟',reading:'Academic Reading · 60 分钟',writing:'Writing · 60 分钟'}[section];$('#ieltsFullProgress').textContent='Listening → Reading → Writing → 结果 → Speaking';
  if(section==='writing')renderIeltsFullWriting(session,mock);else renderIeltsFullQuestions(session,mock);ieltsFullClock()}
function renderIeltsFullQuestions(session,mock){const section=session.section,questions=ieltsFullQuestions(session),index=session.indices[section]||0,q=questions[index];if(!q)return;const answers=session.answers[section],flags=session.flags[section],item=section==='listening'?customListening(mock.listeningId):customReading(mock.readingId),part=item.parts.find(p=>q.section.endsWith('Part '+p.number));
  $('#ieltsFullNavigator').innerHTML=questions.map((question,i)=>`<button class="${i===index?'active':''} ${answers[question.id]?'answered':''} ${flags[question.id]?'review':''}" data-ielts-full-index="${i}">${i+1}</button>`).join('');$$('[data-ielts-full-index]').forEach(b=>b.onclick=()=>{session.indices[section]=Number(b.dataset.ieltsFullIndex);saveIeltsFull();renderIeltsFullQuestions(session,mock)});
  if(section==='reading'){const source=$('#ieltsFullSource'),partKey=item.id+':'+part.number;if(source.dataset.part!==partKey){source.dataset.part=partKey;source.innerHTML=`<h3>${esc(part.title)}</h3><div id="ieltsFullReadingLayout"></div><div class="exam-source-content">${esc(q.content?.passage||'').replaceAll('\n','<br>')}</div>`}$('#ieltsFullReadingLayout').innerHTML=customReadingLayout(q.content?.layout);$('#ieltsFullAudio').innerHTML=''}
  else{$('#ieltsFullSource').innerHTML=`<h3>Listening · Part ${part.number}</h3><p class="sub">Questions 1–40。考试中不显示录音原文、答案或解析。</p>`;ieltsFullAudio(item,part)}
  $('#ieltsFullQuestion').innerHTML=`<span class="practice-label">Question ${index+1} / 40</span><h3>${esc(q.stem).replaceAll('\n','<br>')}</h3><input id="ieltsFullAnswer" class="field" type="text" autocomplete="off" placeholder="输入答案" value="${esc(String(answers[q.id]||''))}"><small id="ieltsFullSaveState">已自动保存</small>`;
  $('#ieltsFullAnswer').oninput=e=>{answers[q.id]=e.target.value;saveIeltsFull();$('[data-ielts-full-index="'+index+'"]').classList.toggle('answered',Boolean(e.target.value.trim()));$('#ieltsFullSaveState').textContent='已自动保存'};
  $('#ieltsFullPrevious').disabled=index===0;$('#ieltsFullNext').disabled=index===39;$('#ieltsFullPrevious').onclick=()=>{session.indices[section]=index-1;saveIeltsFull();renderIeltsFullQuestions(session,mock)};$('#ieltsFullNext').onclick=()=>{session.indices[section]=index+1;saveIeltsFull();renderIeltsFullQuestions(session,mock)};
  $('#ieltsFullFlag').textContent=flags[q.id]?'✓ 已标记 Review':'标记 Review';$('#ieltsFullFlag').onclick=()=>{flags[q.id]=!flags[q.id];saveIeltsFull();renderIeltsFullQuestions(session,mock)}}
function renderIeltsFullWriting(session,mock){const key=session.writingTab,task=key==='writing1'?customOpen.writingTask1.find(t=>t.id===mock.writingTask1Id):customOpen.writingTask2.find(t=>t.id===mock.writingTask2Id),draft=session.drafts[key]||'';
  $('#ieltsFullNavigator').innerHTML=`<button class="${key==='writing1'?'active':''}" data-ielts-writing="writing1">Task 1</button><button class="${key==='writing2'?'active':''}" data-ielts-writing="writing2">Task 2</button>`;
  $$('[data-ielts-writing]').forEach(b=>b.onclick=()=>{session.writingTab=b.dataset.ieltsWriting;saveIeltsFull();renderIeltsFullWriting(session,mock)});
  $('#ieltsFullSource').innerHTML=`<h3>${key==='writing1'?'Academic Task 1':'Task 2'} · ${esc(task.type)}</h3><p>${esc(task.prompt).replaceAll('\n','<br>')}</p>${task.chartSpec?customChart(task.chartSpec):''}`;$('#ieltsFullAudio').innerHTML='';
  $('#ieltsFullQuestion').innerHTML=`<label for="ieltsFullDraft">我的作文 · 自动保存</label><textarea id="ieltsFullDraft" class="rec-text" rows="18" placeholder="在这里写作文">${esc(draft)}</textarea><p id="ieltsFullWordCount">${draft.trim()?draft.trim().split(/\s+/).length:0} words</p><small>提交 Writing 后，可在结果页复制题目与作文。</small>`;
  $('#ieltsFullDraft').oninput=e=>{session.drafts[key]=e.target.value;$('#ieltsFullWordCount').textContent=(e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0)+' words';saveIeltsFull()};
  $('#ieltsFullPrevious').disabled=key==='writing1';$('#ieltsFullNext').disabled=key==='writing2';$('#ieltsFullFlag').hidden=true;$('#ieltsFullPrevious').onclick=()=>{session.writingTab='writing1';saveIeltsFull();renderIeltsFullWriting(session,mock)};$('#ieltsFullNext').onclick=()=>{session.writingTab='writing2';saveIeltsFull();renderIeltsFullWriting(session,mock)}}
window.addEventListener('pagehide',()=>{clearInterval(ieltsFullTimer);ieltsFullSpeechToken++});
if(sessionStorage.getItem('ieltsFullActive')===state.examEngine.ieltsFullSession?.mockId&&state.examEngine.ieltsFullSession.section!=='finished')nav('ielts-full-exam');
