const PRIVATE_DB='englishMemoryLab_private_library_v1',PRIVATE_DB_VERSION=1,PRIVATE_PAPER_STORE='papers',PRIVATE_BLOB_STORE='blobs';
let privateDraft={pdf:null,audios:[]};
function openPrivateDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('浏览器不支持 IndexedDB'));const request=indexedDB.open(PRIVATE_DB,PRIVATE_DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(PRIVATE_PAPER_STORE)){const store=db.createObjectStore(PRIVATE_PAPER_STORE,{keyPath:'id'});store.createIndex('profileId','profileId',{unique:false})}if(!db.objectStoreNames.contains(PRIVATE_BLOB_STORE))db.createObjectStore(PRIVATE_BLOB_STORE,{keyPath:'sha256'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('私人题库数据库打开失败'))})}
function privateDBRequest(storeName,mode,operation){return openPrivateDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(storeName,mode),request=operation(tx.objectStore(storeName));let result;request.onsuccess=()=>{result=request.result};request.onerror=()=>reject(request.error);tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=()=>{db.close();reject(tx.error)}}))}
function getPrivateBlob(sha256){return privateDBRequest(PRIVATE_BLOB_STORE,'readonly',store=>store.get(sha256))}
function putPrivateBlob(record){return privateDBRequest(PRIVATE_BLOB_STORE,'readwrite',store=>store.put(record))}
function deletePrivateBlob(sha256){return privateDBRequest(PRIVATE_BLOB_STORE,'readwrite',store=>store.delete(sha256))}
function putPrivatePaper(record){return privateDBRequest(PRIVATE_PAPER_STORE,'readwrite',store=>store.put(record))}
function deletePrivatePaperRecord(id){return privateDBRequest(PRIVATE_PAPER_STORE,'readwrite',store=>store.delete(id))}
async function listPrivatePapers(allProfiles=false){const all=await privateDBRequest(PRIVATE_PAPER_STORE,'readonly',store=>store.getAll());return allProfiles?all:all.filter(paper=>paper.profileId===activeProfile().id)}
function privateProjectOptions(){return state.projects.filter(project=>!project.archived&&(project.type==='language_exam'||project.type==='custom'||project.id.startsWith('custom-')))}
function renderPrivateExamTypes(){const project=projectById($('#privateProject').value),select=$('#privateExamType'),current=select.value,types=project?examProjectTypes(project):[];select.innerHTML=types.map(type=>`<option value="${type}">${esc(EXAM_TYPE_REGISTRY[type]?.label||type)}</option>`).join('');if(types.includes(current))select.value=current}
async function inspectPrivateFile(file){const buffer=await file.arrayBuffer(),sha256=await sha256Buffer(buffer);return {buffer,sha256,name:file.name,type:file.type||'',size:file.size}}
async function parsePrivatePdf(item){showLoading('正在本地解析 PDF','解析完成后默认只保存结构化文字；只有勾选时才保留原 PDF。');try{const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(item.buffer.slice(0))}).promise,pages=[];for(let number=1;number<=pdf.numPages;number++){const page=await pdf.getPage(number),content=await page.getTextContent();pages.push(content.items.map(token=>token.str).join(' '))}return {text:pages.join('\n\n'),pages:pdf.numPages}}finally{hideLoading()}}
function parsePrivateAnswerKey(text){return String(text||'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map((line,index)=>{const match=line.match(/^(?:Q(?:uestion)?\s*)?(\d+)\s*[.):：\-]?\s*(.+)$/i);return match?{number:Number(match[1]),answer:match[2].trim()}:{number:index+1,answer:line}})}
function resetPrivateDraft(){privateDraft={pdf:null,audios:[]};for(const id of ['privateTitle','privateExtractedText','privateAnswerKey'])$('#'+id).value='';$('#retainPrivatePdf').checked=false;$('#privatePdfInput').value='';$('#privateAudioInput').value='';$('#privatePdfStatus').textContent='尚未选择';renderPrivateAudioBindings();renderPrivatePreview()}
function renderPrivateAudioBindings(){const box=$('#privateAudioBindings');if(!box)return;box.innerHTML=privateDraft.audios.length?privateDraft.audios.map((audio,index)=>`<div class="audio-binding-row"><span>${esc(audio.name)}</span><input class="field" data-audio-section="${index}" value="${esc(audio.section||'Section '+(index+1))}" aria-label="${esc(audio.name)} 对应 Section"><small>${(audio.size/1048576).toFixed(1)} MB · ${audio.sha256.slice(0,8)}</small><button class="btn" data-remove-private-audio="${index}">移除</button></div>`).join(''):'<p class="sub">尚未添加音频。</p>';$$('[data-audio-section]').forEach(input=>input.oninput=()=>privateDraft.audios[Number(input.dataset.audioSection)].section=input.value.slice(0,60));$$('[data-remove-private-audio]').forEach(button=>button.onclick=()=>{privateDraft.audios.splice(Number(button.dataset.removePrivateAudio),1);renderPrivateAudioBindings();renderPrivatePreview()})}
function renderPrivatePreview(){if(!$('#privatePaperPreview'))return;const answers=parsePrivateAnswerKey($('#privateAnswerKey').value),project=projectById($('#privateProject').value),title=$('#privateTitle').value.trim()||'未命名试卷';$('#privatePreviewTitle').textContent=title;$('#privatePaperPreview').innerHTML=`<dl><dt>项目</dt><dd>${esc(project?.name||'未选择')}</dd><dt>PDF</dt><dd>${privateDraft.pdf?esc(privateDraft.pdf.name)+' · '+privateDraft.pdf.pages+' 页':'未选择'}</dd><dt>原 PDF</dt><dd>${privateDraft.pdf&&$('#retainPrivatePdf').checked?'保存在本机 IndexedDB':'不保留，只存解析文字'}</dd><dt>音频绑定</dt><dd>${privateDraft.audios.length?privateDraft.audios.map(audio=>esc(audio.section||'未命名')+' ← '+esc(audio.name)).join('<br>'):'无'}</dd><dt>答案</dt><dd>${answers.length} 题</dd></dl>`}
async function renderPrivateLibrary(){
  const select=$('#privateProject');if(!select)return;const projects=privateProjectOptions(),selected=select.value;select.innerHTML=projects.map(project=>`<option value="${project.id}">${esc(project.name)}</option>`).join('');if(projects.some(project=>project.id===selected))select.value=selected;renderPrivateExamTypes();
  const papers=await listPrivatePapers();$('#privatePaperList').innerHTML=papers.length?papers.sort((a,b)=>b.updatedAt-a.updatedAt).map(paper=>`<div class="private-paper-row"><div><b>${esc(paper.title)}</b><p>${esc(projectById(paper.projectId)?.name||paper.projectId)} · ${esc(EXAM_TYPE_REGISTRY[paper.examType]?.label||paper.examType||'未指定')} · ${paper.pdf?.pages||0} 页 · ${paper.sections.length} 个音频 Section · ${paper.answers.length} 个答案</p></div><span>${new Date(paper.updatedAt).toLocaleDateString('zh-CN')}</span><div class="row"><button class="btn" data-run-private-paper="${paper.id}">进入机考</button><button class="btn danger" data-delete-private-paper="${paper.id}">删除</button></div></div>`).join(''):'<div class="empty">当前学习空间还没有私人试卷。</div>';
  const bytes=papers.reduce((total,paper)=>total+(paper.pdf?.retained?paper.pdf.size||0:0)+paper.sections.reduce((sum,section)=>sum+(section.audioSize||0),0),0);$('#privateStorageSummary').textContent='引用文件约 '+(bytes/1048576).toFixed(1)+' MB（去重前）';$$('[data-delete-private-paper]').forEach(button=>button.onclick=()=>removePrivatePaper(button.dataset.deletePrivatePaper));$$('[data-run-private-paper]').forEach(button=>button.onclick=()=>{const paper=papers.find(item=>item.id===button.dataset.runPrivatePaper);if(typeof startPrivateComputerExam==='function'&&paper)startPrivateComputerExam(paper)});renderPrivatePreview()
}
async function removePrivatePaper(id){if(!confirm('删除这份私人试卷及其本地绑定？若文件没有被其他试卷使用，也会释放对应 Blob。'))return;const papers=await listPrivatePapers(true),paper=papers.find(item=>item.id===id);if(!paper)return;await deletePrivatePaperRecord(id);const remaining=papers.filter(item=>item.id!==id),candidateHashes=[paper.pdf?.retained&&paper.pdf.sha256,...paper.sections.map(section=>section.audioSha256)].filter(Boolean);for(const sha256 of new Set(candidateHashes)){const stillUsed=remaining.some(item=>(item.pdf?.retained&&item.pdf.sha256===sha256)||item.sections.some(section=>section.audioSha256===sha256));if(!stillUsed)await deletePrivateBlob(sha256)}await renderPrivateLibrary();toast('私人试卷已删除')}
$('#pickPrivatePdf').onclick=()=>$('#privatePdfInput').click();
$('#privatePdfInput').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{const item=await inspectPrivateFile(file),parsed=await parsePrivatePdf(item);privateDraft.pdf={...item,pages:parsed.pages};$('#privateExtractedText').value=parsed.text;$('#privatePdfStatus').textContent=`${file.name} · ${parsed.pages} 页 · SHA-256 ${item.sha256.slice(0,12)}…`;if(!$('#privateTitle').value)$('#privateTitle').value=file.name.replace(/\.pdf$/i,'');renderPrivatePreview()}catch(error){alert('PDF 解析失败：'+error.message)}};
$('#pickPrivateAudio').onclick=()=>$('#privateAudioInput').click();
$('#privateAudioInput').onchange=async event=>{for(const file of event.target.files){const item=await inspectPrivateFile(file);if(privateDraft.audios.some(audio=>audio.sha256===item.sha256))continue;privateDraft.audios.push({...item,section:'Section '+(privateDraft.audios.length+1)});}renderPrivateAudioBindings();renderPrivatePreview();event.target.value=''};
$('#privateAnswerKey').oninput=()=>renderPrivatePreview();$('#privateTitle').oninput=()=>renderPrivatePreview();$('#privateProject').onchange=()=>{renderPrivateExamTypes();renderPrivatePreview()};$('#privateExamType').onchange=()=>renderPrivatePreview();$('#retainPrivatePdf').onchange=()=>renderPrivatePreview();$('#previewPrivatePaper').onclick=()=>renderPrivatePreview();$('#resetPrivatePaper').onclick=()=>resetPrivateDraft();
$('#savePrivatePaper').onclick=async()=>{const title=$('#privateTitle').value.trim(),projectId=$('#privateProject').value,examType=$('#privateExamType').value,text=$('#privateExtractedText').value.trim(),answers=parsePrivateAnswerKey($('#privateAnswerKey').value);if(!title)return toast('请填写试卷名称');if(!examType)return toast('请选择题型 / Part');if(!privateDraft.pdf&&!text&&!privateDraft.audios.length)return toast('请至少导入 PDF 或音频');showLoading('正在保存到本机','音频与主动保留的 PDF 会按 SHA-256 去重。');try{for(const audio of privateDraft.audios){if(!await getPrivateBlob(audio.sha256))await putPrivateBlob({sha256:audio.sha256,blob:new Blob([audio.buffer],{type:audio.type}),name:audio.name,type:audio.type,size:audio.size,createdAt:Date.now()})}const retainPdf=Boolean(privateDraft.pdf&&$('#retainPrivatePdf').checked);if(retainPdf&&!await getPrivateBlob(privateDraft.pdf.sha256))await putPrivateBlob({sha256:privateDraft.pdf.sha256,blob:new Blob([privateDraft.pdf.buffer],{type:'application/pdf'}),name:privateDraft.pdf.name,type:'application/pdf',size:privateDraft.pdf.size,createdAt:Date.now()});const now=Date.now(),record={id:'paper-'+now.toString(36),profileId:activeProfile().id,projectId,examType,title,createdAt:now,updatedAt:now,sourceType:'private_local',extractedText:text,pdf:privateDraft.pdf?{name:privateDraft.pdf.name,sha256:privateDraft.pdf.sha256,size:privateDraft.pdf.size,pages:privateDraft.pdf.pages,retained:retainPdf}:null,sections:privateDraft.audios.map((audio,index)=>({id:'section-'+(index+1),title:(audio.section||'Section '+(index+1)).trim(),audioSha256:audio.sha256,audioName:audio.name,audioType:audio.type,audioSize:audio.size})),answers};await putPrivatePaper(record);resetPrivateDraft();await renderPrivateLibrary();toast('私人试卷已保存到本机')}catch(error){alert('保存失败：'+error.message)}finally{hideLoading()}};
renderPrivateAudioBindings();
