function saveBuiltinProgress(deck,w){if(!deck?.builtin)return;const k=progressKey(deck.id,w.word);if(!(w.level||w.due||w.seen||w.correct||w.wrong||w.last)){delete state.vocab.progress[k];return}state.vocab.progress[k]=[w.level||0,w.due||0,w.seen||0,w.correct||0,w.wrong||0,w.last||0,w.screenRepeats||1,w.screenClass||'new']}
function makeRuntimeBuiltin(meta,data){return {id:meta.id,title:meta.title,created:data.cachedAt||now(),builtin:true,source:meta.source,words:(data.words||[]).map((x,i)=>runtimeBuiltinWord(meta.id,x,i))}}
function csvRows(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(c!=='\r')cell+=c}row.push(cell);if(row.some(x=>x))rows.push(row);return rows}
async function fetchWordTyper(meta){const r=await fetch(meta.url,{cache:'no-store'});if(!r.ok)throw new Error('下载失败 HTTP '+r.status);const j=await r.json();return (j.words||[]).map(x=>({word:String(x.word||'').trim(),phonetic:String(x.phonetic||''),meaning:compactMeaning((x.translations||[])[0]||'')})).filter(x=>x.word&&x.meaning)}
async function simplifyTraditional(items){try{const m=await import('https://cdn.jsdelivr.net/npm/opencc-js@1.0.5/+esm');const cv=m.Converter({from:'tw',to:'cn'});items.forEach(x=>x.meaning=cv(x.meaning))}catch{}return items}
async function fetchToeicFallback(){const u='https://huggingface.co/datasets/kknono668/toeic-vocab-tw/resolve/main/data/toeic_vocabulary.json';const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('TOEIC 备用词库下载失败');const j=await r.json();let arr=(Array.isArray(j)?j:[]).map((x,i)=>({word:String(x.english_word||'').trim(),meaning:compactMeaning(x.chinese_definition||''),phonetic:'',star:Number(x.star_rating||0),i})).filter(x=>x.word&&x.meaning);arr.sort((a,b)=>(b.star-a.star)||(a.i-b.i));arr=arr.slice(0,1800);await simplifyTraditional(arr);return arr}
async function fetchToeic(meta){let out=[];try{const sheet='https://docs.google.com/spreadsheets/d/1UQOXHQdbsyXTOgUyCsmKtHV-9pwS70CxhHJjEBFZD-E/gviz/tq?tqx=out:csv';const r=await fetch(sheet,{cache:'no-store'});if(r.ok){const rows=csvRows(await r.text());const h=(rows.shift()||[]).map(x=>x.trim().toLowerCase());let wi=h.findIndex(x=>x==='word'||x.includes('lemma')),ci=h.findIndex(x=>x.includes('chinese'));if(wi<0)wi=0;for(const row of rows){const word=String(row[wi]||'').trim(),meaning=compactMeaning(row[ci]||'');if(/[A-Za-z]/.test(word)&&meaning&&meaning!=='暂无释义')out.push({word,meaning,phonetic:''})}}}catch(e){}
  const seen=new Set(out.map(x=>normWord(x.word)));if(out.length<meta.expected){const fb=await fetchToeicFallback();for(const x of fb){const k=normWord(x.word);if(!seen.has(k)){seen.add(k);out.push(x)}if(out.length>=meta.expected)break}}
  return out.slice(0,meta.expected)
}
async function downloadBuiltin(meta){let words=meta.kind==='wordtyper'?await fetchWordTyper(meta):await fetchToeic(meta);if(!words.length)throw new Error('没有获得词库数据');const data={id:meta.id,version:meta.version,cachedAt:now(),words};await idbPutDeck(data);state.vocab.builtinInstalled[meta.id]={version:meta.version,count:words.length,cachedAt:data.cachedAt};save();return data}
async function ensureBuiltinDeck(id,force=false){const meta=BUILTIN_VOCAB[id];if(!meta)throw new Error('未知词库');if(!force&&builtinDeckCache.has(id))return builtinDeckCache.get(id);let data=null;if(!force)try{data=await idbGetDeck(id)}catch{}if(!data||data.version!==meta.version)data=await downloadBuiltin(meta);const deck=makeRuntimeBuiltin(meta,data);builtinDeckCache.set(id,deck);state.vocab.builtinInstalled[id]={version:meta.version,count:deck.words.length,cachedAt:data.cachedAt};save();return deck}
function installedBuiltinMetas(){return Object.values(BUILTIN_VOCAB).filter(m=>state.vocab.builtinInstalled[m.id])}
async function installBuiltin(id,force=false){const meta=BUILTIN_VOCAB[id],card=document.querySelector('[data-builtin-card="'+id+'"]'),status=card?.querySelector('.install-status');if(status){status.textContent='正在安装…';status.className='install-status loading'}try{const d=await ensureBuiltinDeck(id,force);if(status){status.textContent='已安装 '+d.words.length+' 词';status.className='install-status ready'}renderVocabHome();return d}catch(e){if(status){status.textContent='安装失败 · 点此重试';status.className='install-status badtxt'}console.warn(e);return null}}
async function preloadBuiltinDecks(){for(const id of Object.keys(BUILTIN_VOCAB)){if(state.vocab.builtinInstalled[id]){try{await ensureBuiltinDeck(id,false)}catch{}}else if(navigator.onLine){await installBuiltin(id,false)}}renderBuiltinVocab()}
function renderBuiltinVocab(){const box=$('#builtinVocabList');if(!box)return;box.innerHTML=Object.values(BUILTIN_VOCAB).map(m=>{const info=state.vocab.builtinInstalled[m.id],cached=builtinDeckCache.get(m.id),count=cached?.words.length||info?.count||m.expected;const ready=!!info;return `<div class="builtin-card" data-builtin-card="${m.id}"><div class="row between"><span style="font-size:22px">${m.icon}</span><span class="install-status ${ready?'ready':''}">${ready?'已缓存 '+count+' 词':'首次打开自动安装'}</span></div><div><h4>${esc(m.title)}</h4><div class="sub" style="margin-top:5px">${esc(m.description)}</div></div><div class="source">来源：${esc(m.source)}</div><div class="row"><button class="btn primary" data-builtin-screen="${m.id}">${ready?'四选一':'安装并开始'}</button><button class="btn" data-builtin-spell="${m.id}">拼写</button><button class="btn" data-builtin-refresh="${m.id}" title="重新下载词库">↻</button></div></div>`}).join('');$$('[data-builtin-screen]').forEach(b=>b.onclick=async()=>{const d=await installBuiltin(b.dataset.builtinScreen,false);if(d)startVocabScreen(d.id)});$$('[data-builtin-spell]').forEach(b=>b.onclick=async()=>{const d=await installBuiltin(b.dataset.builtinSpell,false);if(d)startVocabSpell(d.id)});$$('[data-builtin-refresh]').forEach(b=>b.onclick=async()=>installBuiltin(b.dataset.builtinRefresh,true))}
function uid(prefix='x'){return prefix+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function parseVocabLines(text){const out=[],seen=new Set();for(const raw of text.replace(/\r/g,'').split('\n')){let line=raw.trim();if(!line)continue;let word='',meaning='';let m=line.match(/^(.+?)\s*(?:\t+|\||｜|=|＝|:|：)\s*(.+)$/);if(m){word=m[1].trim();meaning=m[2].trim()}else{m=line.match(/^([A-Za-z][A-Za-z' -]*?)\s+([\u3400-\u9fff].*)$/);if(m){word=m[1].trim();meaning=m[2].trim()}}word=word.replace(/^[-•\d.、\s]+/,'').trim();if(!word||!meaning||!/[A-Za-z]/.test(word))continue;const key=word.toLowerCase();if(seen.has(key))continue;seen.add(key);out.push({id:uid('w'),word,meaning,example:'',seen:0,correct:0,wrong:0,level:0,due:0,last:0,screenRepeats:1,screenClass:'new',sessionCorrect:0,sessionWrong:0})}return out.slice(0,1000)}
function wordById(deck,id){let m=deckIndexCache.get(deck);if(!m){m=new Map(deck.words.map(w=>[w.id,w]));deckIndexCache.set(deck,m)}return m.get(id)||null}
function activeVocabDeck(){return state.vocab.decks.find(d=>d.id===state.vocab.activeDeck)||builtinDeckCache.get(state.vocab.activeDeck)||null}
function addVocabDeck(title,text){const words=parseVocabLines(text);if(!words.length)return toast('没有识别到“英文 + 中文释义”');const d={id:uid('vd'),title:title||'未命名单词库',created:now(),words};state.vocab.decks.unshift(d);state.vocab.activeDeck=d.id;state.vocab.session=null;save();renderVocabHome();toast('已建立 '+words.length+' 个单词')}
function vocabDueCount(){const t=now();let n=state.vocab.decks.reduce((a,d)=>a+d.words.filter(w=>w.level>0&&(w.due||0)<=t).length,0);for(const d of builtinDeckCache.values())n+=d.words.filter(w=>w.level>0&&(w.due||0)<=t).length;return n}
function renderVocabHome(){const box=$('#vocabDeckList');const custom=state.vocab.decks, built=[...builtinDeckCache.values()];const decks=[...custom,...built];$('#vocabDeckCount').textContent=custom.length+Object.keys(state.vocab.builtinInstalled).length;$('#vocabWordCount').textContent=custom.reduce((n,d)=>n+d.words.length,0)+Object.values(state.vocab.builtinInstalled).reduce((n,x)=>n+(x.count||0),0);$('#vocabMasteredCount').textContent=decks.reduce((n,d)=>n+d.words.filter(w=>w.level>=3).length,0);$('#vocabDueBadge').textContent='待复习 '+vocabDueCount();$('#vocabBatchSize').value=state.settings.vocabBatchSize||'100';renderBuiltinVocab();if(!custom.length)box.innerHTML='<div class="empty">这里还没有自定义词库；上面的 TOEIC / IELTS / 考研词库已经可以直接使用。</div>';else box.innerHTML=custom.map(d=>{const mastered=d.words.filter(w=>w.level>=3).length;return `<div class="vocab-deck ${d.id===state.vocab.activeDeck?'active':''}"><div><div class="doc-title">${esc(d.title)}</div><div class="doc-meta">${d.words.length} 词 · 熟练 ${mastered}/${d.words.length}</div></div><div class="row"><button class="btn primary" data-vscreen="${d.id}">四选一</button><button class="btn" data-vspell="${d.id}">拼写</button><button class="btn danger" data-vdel="${d.id}">删除</button></div></div>`}).join('');$$('[data-vscreen]').forEach(b=>b.onclick=()=>startVocabScreen(b.dataset.vscreen));$$('[data-vspell]').forEach(b=>b.onclick=()=>startVocabSpell(b.dataset.vspell));$$('[data-vdel]').forEach(b=>b.onclick=()=>{if(confirm('删除这个词库和学习进度？')){state.vocab.decks=state.vocab.decks.filter(d=>d.id!==b.dataset.vdel);if(state.vocab.activeDeck===b.dataset.vdel)state.vocab.activeDeck=state.vocab.decks[0]?.id||null;state.vocab.session=null;save();renderVocabHome()}});if(state.vocab.session&&activeVocabDeck()){$('#vocabTrainer').style.display='block';renderVocabSession()}else $('#vocabTrainer').style.display='none'}
function vocabDistractors(deck,word){const out=[],used=new Set([word.meaning]);let tries=0,n=deck.words.length;while(out.length<3&&tries<80&&n>1){const w=deck.words[Math.floor(Math.random()*n)];tries++;if(!w||w.id===word.id||used.has(w.meaning))continue;used.add(w.meaning);out.push(w.meaning)}if(out.length<3){for(const w of deck.words){if(w.id!==word.id&&!used.has(w.meaning)){used.add(w.meaning);out.push(w.meaning);if(out.length===3)break}}}return out}
function vocabOptionsFor(deck,word){let opts=[word.meaning,...vocabDistractors(deck,word)];const filler=['以上都不符合','需要进一步确认','与该词无关'];let i=0;while(opts.length<4)opts.push(filler[i++]);return shuffle(opts.slice(0,4))}
function startVocabScreen(deckId,onlyDue=false){const d=state.vocab.decks.find(x=>x.id===deckId)||builtinDeckCache.get(deckId);if(!d)return;if(d.words.length<4)return toast('四选一至少需要 4 个单词');state.vocab.activeDeck=d.id;let pool=onlyDue?d.words.filter(w=>w.level>0&&(w.due||0)<=now()):shuffle(d.words);if(!onlyDue){const size=state.settings.vocabBatchSize||'100';if(size!=='all')pool=pool.slice(0,Math.max(4,Number(size)||100))}if(!pool.length)return toast('现在没有到期单词');pool.forEach(w=>{w.sessionCorrect=0;w.sessionWrong=0});state.vocab.session={phase:'screen',queue:shuffle(pool.map(w=>w.id)),participants:pool.map(w=>w.id),index:0,started:now(),questionStart:now(),screen:{fast:0,steady:0,slow:0,wrong:0},reinforceTotal:0,reinforceDone:0};save();$('#vocabTrainer').style.display='block';renderVocabSession();setTimeout(()=>$('#vocabTrainer').scrollIntoView({behavior:'smooth',block:'start'}),30)}
function startVocabSpell(deckId){const d=state.vocab.decks.find(x=>x.id===deckId)||builtinDeckCache.get(deckId);if(!d)return;state.vocab.activeDeck=d.id;let pool=shuffle(d.words),size=state.settings.vocabBatchSize||'100';if(size!=='all')pool=pool.slice(0,Math.max(1,Number(size)||100));pool.forEach(w=>{w.sessionCorrect=0;w.sessionWrong=0});state.vocab.session={phase:'spell',queue:shuffle(pool.map(w=>w.id)),participants:pool.map(w=>w.id),index:0,started:now(),questionStart:now(),spellCorrect:0,spellWrong:0};save();$('#vocabTrainer').style.display='block';renderVocabSession();setTimeout(()=>$('#vocabTrainer').scrollIntoView({behavior:'smooth',block:'start'}),30)}
function currentVocabWord(){const d=activeVocabDeck(),s=state.vocab.session;if(!d||!s||!s.queue.length)return null;return wordById(d,s.queue[s.index])}
function renderVocabSession(){clearTimeout(vocabAdvanceTimer);const d=activeVocabDeck(),s=state.vocab.session;if(!d||!s){$('#vocabTrainer').style.display='none';return}const w=currentVocabWord();if(!w){finishVocabSession();return}$('#vocabTrainer').style.display='block';$('#vocabDeckName').textContent=d.title;$('#vocabSessionResult').style.display='none';$('#vocabQuestionArea').style.display='block';$('#vocabFeedback').innerHTML='';$('#vocabUnknown').style.display=s.phase==='spell'?'none':'inline-block';$('#vocabSkip').style.display='inline-block';$('#vocabOptions').style.display=s.phase==='spell'?'none':'grid';$('#vocabSpellBox').style.display=s.phase==='spell'?'block':'none';const done=s.index,total=s.queue.length;$('#vocabProgress').style.width=(total?done/total*100:0)+'%';$('#vocabRepeatBadge').textContent=`第 ${Math.min(done+1,total)} / ${total}`;if(s.phase==='screen'){$('#vocabPhaseTitle').textContent='① 极速四选一';$('#vocabCue').textContent='第一轮：不要想太久，凭第一反应选中文释义';renderVocabChoice(d,w)}else if(s.phase==='reinforce'){$('#vocabPhaseTitle').textContent='② 强化记忆轮';const remain=s.queue.slice(s.index).filter(id=>id===w.id).length;$('#vocabCue').textContent='错词和慢词会重复出现，直到形成快速反应';$('#vocabRepeatBadge').textContent=`${done+1}/${total} · 本词还会见 ${remain} 次`;renderVocabChoice(d,w)}else{$('#vocabPhaseTitle').textContent='③ 拼写强化';$('#vocabCue').textContent='看中文，手打英文；这是写作考试最重要的一步';$('#vocabWord').textContent='';$('#vocabPhonetic').textContent=w.phonetic||'';$('#vocabSpellMeaning').textContent=w.meaning;$('#vocabSpellInput').value='';$('#vocabSpellInput').classList.remove('correct','wrong');setTimeout(()=>$('#vocabSpellInput').focus(),30)}s.questionStart=now();save()}
