function keywords(s,n=5){let a=(s.toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g)||[]).filter(w=>w.length>3&&!stop.has(w));const f={};a.forEach(w=>f[w]=(f[w]||0)+1);return [...new Set(a)].sort((x,y)=>(f[y]-f[x])||(y.length-x.length)).slice(0,n)}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function sentenceTokens(s){return s.match(/[A-Za-z]+(?:'[A-Za-z]+)?|\d+|[^A-Za-z\d\s]+/g)||[]}
function cloze(s,ratio,i){const t=sentenceTokens(s),cand=t.map((w,k)=>({w,k})).filter(x=>/^[A-Za-z]/.test(x.w)&&x.w.length>2);const ranked=[...cand].sort((a,b)=>((a.k*19+i*13)%37)-((b.k*19+i*13)%37));const h=new Set(ranked.slice(0,Math.max(1,Math.round(cand.length*ratio))).map(x=>x.k));let blankNo=0;return t.map((w,k)=>{if(!h.has(k))return esc(w);blankNo++;const width=Math.max(5,Math.min(14,w.length+2));return '<input class="cloze-input" data-answer="'+esc(w)+'" data-blank="'+blankNo+'" autocomplete="off" autocapitalize="off" spellcheck="false" aria-label="填空 '+blankNo+'" style="width:'+width+'ch" />'}).join(' ').replace(/\s+([,.;!?])/g,'$1')}
function initials(s){return sentenceTokens(s).map(w=>/^[A-Za-z]/.test(w)?esc(w[0])+'…':esc(w)).join(' ').replace(/\s+([,.;!?])/g,'$1')}
function now(){return Date.now()}function dayKey(d=new Date()){return d.toISOString().slice(0,10)}
function active(){return state.docs.find(d=>d.id===state.activeDoc)||null}
function makeDoc(title,text){const ss=splitSentences(text); if(!ss.length)throw new Error('没有识别到英文完整句子');const paras=text.split(/\n\s*\n|\n(?=[A-Z][^\n]{0,50}$)/).map(x=>x.trim()).filter(Boolean);let sections=[]; if(paras.length>1){sections=paras.slice(0,20).map((p,i)=>({name:'Story '+(i+1),keywords:keywords(p,4),preview:p.slice(0,80)}))}else{for(let i=0;i<ss.length;i+=4){const chunk=ss.slice(i,i+4).join(' ');sections.push({name:'Node '+(sections.length+1),keywords:keywords(chunk,4),preview:chunk.slice(0,80)})}}
return {id:'d'+Date.now(),title:title||'未命名资料',text,sentences:ss,sections,created:now(),cards:ss.map((s,i)=>({i,ease:0,due:0,reps:0,lapses:0,last:0})),weak:{}}}
function addDoc(title,text){const d=makeDoc(title,text);state.docs.unshift(d);state.activeDoc=d.id;state.study={index:0,mode:'full'};save();renderLibrary();renderStudy();toast('资料已生成，共 '+d.sentences.length+' 句');nav('study')}
function renderLibrary(){const box=$('#libraryList');if(!state.docs.length){box.innerHTML='<div class="empty">还没有资料。把刚刚的串题故事粘贴进上面，就可以马上开始。</div>';return}box.innerHTML=state.docs.map(d=>{const mastered=d.cards.filter(c=>c.ease>=3).length;return `<div class="doc"><div><div class="doc-title">${esc(d.title)}</div><div class="doc-meta">${d.sentences.length} 句 · ${d.sections.length} 个故事节点 · 熟练 ${mastered}/${d.sentences.length}</div><div style="margin-top:7px">${d.sections.slice(0,3).flatMap(x=>x.keywords.slice(0,1)).map(k=>'<span class="tag" style="margin-right:5px">'+esc(k)+'</span>').join('')}</div></div><div class="row"><button class="btn" data-open="${d.id}">开始背</button><button class="btn danger" data-del="${d.id}">删除</button></div></div>`}).join('');$$('[data-open]').forEach(b=>b.onclick=()=>{state.activeDoc=b.dataset.open;state.study.index=0;save();renderStudy();nav('study')});$$('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('删除这份资料和它的进度？')){state.docs=state.docs.filter(d=>d.id!==b.dataset.del);if(state.activeDoc===b.dataset.del)state.activeDoc=state.docs[0]?.id||null;save();renderLibrary()}})}
function renderStudy(){const d=active();if(!d){$('#studyDocName').textContent='还没有选择资料';$('#sentenceIndex').textContent='0 / 0';$('#cueLabel').textContent='请选择资料';$('#sentenceDisplay').textContent='先到资料库导入你的串题故事。';$('#storyMap').innerHTML='';$('#clozeTools').style.display='none';$('#clozeFeedback').textContent='';return}let i=Math.max(0,Math.min(state.study.index,d.sentences.length-1));state.study.index=i;const s=d.sentences[i],m=state.study.mode;$('#studyDocName').textContent=d.title;$('#sentenceIndex').textContent=(i+1)+' / '+d.sentences.length;$$('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));$('#answerDisplay').style.display='none';$('#answerDisplay').textContent=s;$('#revealAnswer').style.display=m==='full'?'none':'inline-block';$('#revealAnswer').textContent='显示原句';$('#recBox').style.display=(m==='recall')?'block':'none';$('#scoreResult').innerHTML='';$('#clozeFeedback').textContent='';const isCloze=m==='cloze30'||m==='cloze60';$('#clozeTools').style.display=isCloze?'flex':'none';let html='',cue='';if(m==='full'){cue='完整阅读 · 先理解节奏';html=esc(s)}else if(m==='cloze30'){cue='30% 挖空 · 直接在空格里打字';html=cloze(s,.3,i)}else if(m==='cloze60'){cue='60% 挖空 · 模拟写作记忆，填完再检查';html=cloze(s,.6,i)}else if(m==='initials'){cue='首字母提示 · 还原整句';html=initials(s)}else if(m==='keywords'){cue='只看关键词 · 自己组织英文';html=keywords(s,5).map(k=>'<span class="keyword-chip">'+esc(k)+'</span>').join('')}else{cue='完整复述 · 不看原文';html=keywords(s,3).map(k=>'<span class="keyword-chip">'+esc(k)+'</span>').join('')||'现在直接说出这句话。'}$('#cueLabel').textContent=cue;$('#sentenceDisplay').innerHTML=html;if(isCloze){const first=$('#sentenceDisplay .cloze-input');if(first)setTimeout(()=>first.focus(),0)}renderMap()}
function renderMap(){const d=active();if(!d)return;$('#storyMap').innerHTML=d.sections.map((x,i)=>`<button class="node" data-node="${i}"><b>${esc(x.name)}</b> · ${x.keywords.map(esc).join(' → ')}</button>`).join('');$$('[data-node]').forEach((b,idx)=>b.onclick=()=>{const start=Math.min(idx*4,d.sentences.length-1);state.study.index=start;state.study.mode='keywords';save();renderStudy()})}
$$('.mode').forEach(b=>b.onclick=()=>{state.study.mode=b.dataset.mode;save();renderStudy()});$('#prevSentence').onclick=()=>{const d=active();if(!d)return;state.study.index=(state.study.index-1+d.sentences.length)%d.sentences.length;save();renderStudy()};$('#nextSentence').onclick=()=>{const d=active();if(!d)return;state.study.index=(state.study.index+1)%d.sentences.length;save();renderStudy()};$('#shuffleSentence').onclick=()=>{const d=active();if(!d)return;state.study.index=Math.floor(Math.random()*d.sentences.length);save();renderStudy()};$('#revealAnswer').onclick=()=>{const a=$('#answerDisplay');a.style.display=a.style.display==='none'?'block':'none';$('#revealAnswer').textContent=a.style.display==='none'?'显示原句':'隐藏原句'};
function normBlank(s){return (s||'').trim().toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9']/g,'')}
function checkClozeAnswers(){const inputs=$$('#sentenceDisplay .cloze-input');if(!inputs.length)return;let correct=0,empty=0;inputs.forEach(inp=>{const ok=normBlank(inp.value)===normBlank(inp.dataset.answer);inp.classList.remove('correct','wrong');if(!inp.value.trim()){empty++;inp.classList.add('wrong')}else if(ok){correct++;inp.classList.add('correct')}else inp.classList.add('wrong')});const pct=Math.round(correct/inputs.length*100);$('#clozeFeedback').innerHTML=`<b>${correct}/${inputs.length} 正确 · ${pct}%</b>${empty?` · 还有 ${empty} 个没填`:''}<br><span class="muted">绿色正确，红色需要再想。你可以修改后反复点“检查填空”。</span>`;if(pct===100){toast('全部正确 ✓');logPractice(true)}else{logPractice(false)}save()}
$('#checkCloze').onclick=checkClozeAnswers;$('#resetCloze').onclick=()=>{$$('#sentenceDisplay .cloze-input').forEach(x=>{x.value='';x.classList.remove('correct','wrong')});$('#clozeFeedback').textContent='';const first=$('#sentenceDisplay .cloze-input');if(first)first.focus()};$('#sentenceDisplay').addEventListener('keydown',e=>{if(e.target.classList&&e.target.classList.contains('cloze-input')&&e.key==='Enter'){e.preventDefault();const inputs=$$('#sentenceDisplay .cloze-input'),i=inputs.indexOf(e.target);if(i>=0&&i<inputs.length-1)inputs[i+1].focus();else checkClozeAnswers()}});
const speechSupported='speechSynthesis'in window&&'SpeechSynthesisUtterance'in window;
let speechVoices=[],cachedSpeechVoice=null,cachedSpeechLang='',speechGestureReady=false,speechRestartTimer=null;
function refreshSpeechVoices(){if(!speechSupported)return[];speechVoices=window.speechSynthesis.getVoices()||[];cachedSpeechVoice=null;cachedSpeechLang='';return speechVoices}
function englishSpeechVoice(lang){lang=String(lang||'en-US');if(cachedSpeechVoice&&cachedSpeechLang===lang)return cachedSpeechVoice;const wanted=lang.toLowerCase(),base=wanted.split('-')[0],voices=speechVoices.length?speechVoices:refreshSpeechVoices();cachedSpeechVoice=voices.find(v=>String(v.lang).toLowerCase()===wanted&&v.localService)||voices.find(v=>String(v.lang).toLowerCase()===wanted)||voices.find(v=>String(v.lang).toLowerCase().startsWith(base+'-')&&v.localService)||voices.find(v=>String(v.lang).toLowerCase().startsWith(base+'-'))||null;cachedSpeechLang=lang;return cachedSpeechVoice}
function primeSpeech(){if(!speechSupported)return false;speechGestureReady=true;refreshSpeechVoices();try{window.speechSynthesis.resume()}catch{}return true}
function speak(text,{userInitiated=false}={}){if(!speechSupported){if(userInitiated)toast('当前浏览器不支持文字朗读');return false}text=String(text||'').trim();if(!text)return false;if(userInitiated)primeSpeech();else if(!speechGestureReady)return false;const synth=window.speechSynthesis,lang=state.settings.speechLang||'en-US',u=new SpeechSynthesisUtterance(text),voice=englishSpeechVoice(lang);u.lang=lang;u.rate=Number(state.settings.speechRate)||.9;if(voice)u.voice=voice;u.onerror=e=>{if(userInitiated&&!['canceled','interrupted'].includes(e.error))toast('朗读没有启动，请再点一次“朗读”')};const start=()=>{try{synth.resume();synth.speak(u);return true}catch{if(userInitiated)toast('朗读没有启动，请再点一次“朗读”');return false}};clearTimeout(speechRestartTimer);if(synth.speaking||synth.pending){synth.cancel();speechRestartTimer=setTimeout(start,70);return true}return start()}
if(speechSupported){refreshSpeechVoices();if(window.speechSynthesis.addEventListener)window.speechSynthesis.addEventListener('voiceschanged',refreshSpeechVoices);else window.speechSynthesis.onvoiceschanged=refreshSpeechVoices;document.addEventListener('pointerdown',primeSpeech,{once:true,capture:true});document.addEventListener('keydown',primeSpeech,{once:true,capture:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){refreshSpeechVoices();try{window.speechSynthesis.resume()}catch{}}})}
$('#speakSentence').onclick=()=>{const d=active();if(d)speak(d.sentences[state.study.index],{userInitiated:true})};
function rateCard(rate){const d=active();if(!d)return;const c=d.cards[state.study.index],ms=86400000;const map={again:{ease:0,wait:0},hard:{ease:1,wait:.5},good:{ease:2,wait:2},easy:{ease:3,wait:5}}[rate];c.ease=map.ease;c.reps++;if(rate==='again')c.lapses++;c.last=now();c.due=now()+map.wait*ms;logPractice(rate!=='again');save();state.study.index=(state.study.index+1)%d.sentences.length;renderStudy();toast(rate==='again'?'已加入高频复习':'已记录')}
$$('[data-rate]').forEach(b=>b.onclick=()=>rateCard(b.dataset.rate));
function logPractice(ok){const k=dayKey();state.logs[k]=state.logs[k]||{reviewed:0,correct:0};state.logs[k].reviewed++;if(ok)state.logs[k].correct++}
function normalize(s){return (s.toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g)||[]).filter(w=>!stop.has(w))}function similarity(ref,input){const a=normalize(ref),b=normalize(input);const A=new Set(a),B=new Set(b);let common=0;A.forEach(x=>B.has(x)&&common++);const coverage=A.size?common/A.size:0;const key=keywords(ref,6);const keyHit=key.length?key.filter(x=>B.has(x)).length/key.length:0;const len=Math.min(1,b.length/Math.max(1,a.length*.7));const structure=/because|however|therefore|instead|as a result|for example|first|finally|experience|learned|taught/i.test(input)?1:.6;return {coverage,keyHit,len,structure,total:Math.round((coverage*.45+keyHit*.3+len*.15+structure*.1)*100)}}
function scoreHTML(x,exam=false){return `<div class="score-grid"><div class="score"><b>${x.total}</b><small>综合分</small></div><div class="score"><b>${Math.round(x.coverage*100)}%</b><small>内容覆盖</small></div><div class="score"><b>${Math.round(x.keyHit*100)}%</b><small>关键词调用</small></div><div class="score"><b>${Math.round(x.len*100)}%</b><small>${exam?'回答长度':'复述完整度'}</small></div></div><div class="sub" style="margin-top:10px">${x.total>=82?'✅ 已经可以脱离原文复述。':x.total>=65?'△ 基本记住了，但还有关键词掉落。':'→ 先看关键词再说一次，不建议重新从头死背。'}</div>`}
$('#localScoreBtn').onclick=()=>{const d=active();if(!d)return;const inp=$('#recInput').value.trim();if(!inp)return toast('先说或输入你的复述');const ref=d.sentences[state.study.index];const s=similarity(ref,inp);$('#scoreResult').innerHTML=scoreHTML(s);d.weak= d.weak||{};keywords(ref,6).forEach(w=>{if(!normalize(inp).includes(w))d.weak[w]=(d.weak[w]||0)+1});save()};
function setupRecognition(btn,input,status){btn.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('请用 Chrome / Edge 使用语音识别');return}if(recognition){recognition.stop();recognition=null;btn.textContent='🎙️ 开始语音识别';return}recognition=new SR();recognition.lang='en-US';recognition.continuous=true;recognition.interimResults=true;let final='';recognition.onstart=()=>{btn.textContent='■ 停止识别';if(status)status.textContent='正在听…'};recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)final+=e.results[i][0].transcript+' ';else interim+=e.results[i][0].transcript}input.value=(final+interim).trim()};recognition.onerror=e=>{if(status)status.textContent='识别失败：'+e.error};recognition.onend=()=>{recognition=null;btn.textContent='🎙️ 开始语音识别';if(status)status.textContent=''};recognition.start()}}
setupRecognition($('#speechBtn'),$('#recInput'),$('#speechStatus'));setupRecognition($('#examSpeak'),$('#examInput'),null);
const BUILTIN_VOCAB={
  toeic_core:{id:'toeic_core',title:'TOEIC 核心 1250',expected:1250,icon:'💼',description:'从完整 TOEIC 双语词库中筛出的核心 1,250 词，优先按重要度学习。',source:'完整 TOEIC 单字库 · CC BY-SA 4.0',kind:'static-toeic',manifest:'data/toeic-manifest.json',version:'2026.09.05-static.1'},
  toeic_full:{id:'toeic_full',title:'TOEIC 完整 11154',expected:11154,icon:'🧳',description:'完整 11,154 词 TOEIC 双语词库。首次安装读取本站静态分片，之后直接使用本机缓存。',source:'完整 TOEIC 单字库 · CC BY-SA 4.0',kind:'static-toeic',manifest:'data/toeic-manifest.json',version:'2026.09.05-static.1',deferred:true},
  ielts_core:{id:'ielts_core',title:'IELTS 核心词汇',expected:4974,icon:'🌍',description:'IELTS 核心词汇，适合后续雅思阅读、听力、写作与口语。',source:'WordTyper Vocabularies，客观派生自 ECDICT · MIT',kind:'wordtyper',url:'https://raw.githubusercontent.com/grhliu/wordtyper-vocabularies/main/vocabularies/ielts_core.json',version:'2.0.1'},
  kaoyan_core:{id:'kaoyan_core',title:'考研英语核心',expected:4787,icon:'📚',description:'考研英语大纲核心词汇，可直接四选一筛查并做拼写强化。',source:'WordTyper Vocabularies，客观派生自 ECDICT · MIT',kind:'wordtyper',url:'https://raw.githubusercontent.com/grhliu/wordtyper-vocabularies/main/vocabularies/kaoyan.json',version:'2.0.0'}
};
const VOCAB_DB='englishMemoryLab_vocab_cache_v1', VOCAB_STORE='decks';
function openVocabDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('浏览器不支持 IndexedDB'));const r=indexedDB.open(VOCAB_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(VOCAB_STORE))r.result.createObjectStore(VOCAB_STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('IndexedDB 打开失败'))})}
async function idbGetDeck(id){const db=await openVocabDB();return new Promise((resolve,reject)=>{const tx=db.transaction(VOCAB_STORE,'readonly'),r=tx.objectStore(VOCAB_STORE).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()})}
async function idbPutDeck(obj){const db=await openVocabDB();return new Promise((resolve,reject)=>{const tx=db.transaction(VOCAB_STORE,'readwrite');tx.objectStore(VOCAB_STORE).put(obj);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
function compactMeaning(s=''){s=String(s).replace(/^\[[^\]]+\]\s*/,'').replace(/\s+/g,' ').trim();if(s.length>46)s=s.slice(0,46).replace(/[，,；;][^，,；;]*$/,'')+'…';return s||'暂无释义'}
function progressKey(deckId,word){return deckId+'|'+normWord(word)}
function runtimeBuiltinWord(deckId,x,i){const k=progressKey(deckId,x.word),p=state.vocab.progress[k]||[];return {id:'bw:'+deckId+':'+normWord(x.word),word:x.word,meaning:x.meaning,phonetic:x.phonetic||'',pos:x.pos||'',example:x.example||'',exampleZh:x.exampleZh||'',tags:Array.isArray(x.tags)?x.tags:[],rank:Number(x.rank||i+1),seen:p[2]||0,correct:p[3]||0,wrong:p[4]||0,level:p[0]||0,due:p[1]||0,last:p[5]||0,screenRepeats:p[6]||1,screenClass:p[7]||'new',sessionCorrect:0,sessionWrong:0,builtinDeckId:deckId}}
