/* IELTS full mock exam. Own session and shell; specialized practice remains in app-23. */
let ieltsFullTimer=null,ieltsFullSpeechToken=0,ieltsFullAudioVolume=1,ieltsFullAudioActive=null;
const ieltsFullSections=['listening','reading','writing'];
function ieltsFullSession(){return state.examEngine.ieltsFullSession||null}
function saveIeltsFull(){save({immediate:true,refresh:false})}
function startIeltsFullMock(mockId){const mock=customMock(mockId);if(!customMockReady(mock))return toast('此模拟卷的资料尚未齐全');const old=ieltsFullSession();
  if(old&&old.mockId===mockId&&old.section!=='finished'){sessionStorage.setItem('ieltsFullActive',mockId);return nav('ielts-full-exam')}
  if(old&&old.section!=='finished'&&!confirm('开始另一套将覆盖未完成的机考。确定继续吗？'))return;
  const now=Date.now();state.examEngine.ieltsFullSession={mockId,section:'listening',startedAt:now,deadline:now+30*60000,indices:{listening:0,reading:0},answers:{listening:{},reading:{}},flags:{listening:{},reading:{}},drafts:{writing1:'',writing2:''},writingTab:'writing1',results:{},completedAt:null};saveIeltsFull();sessionStorage.setItem('ieltsFullActive',mockId);nav('ielts-full-exam')}
function ieltsFullQuestions(session){const mock=customMock(session.mockId),item=session.section==='listening'?customListening(mock.listeningId):customReading(mock.readingId);return buildCustomExamQuestions(session.section,item)}
function ieltsFullScore(session,section){const mock=customMock(session.mockId),item=section==='listening'?customListening(mock.listeningId):customReading(mock.readingId);return buildCustomExamQuestions(section,item).reduce((n,q)=>n+Number(isObjectiveAnswerCorrect(q,session.answers[section][q.id]||'')),0)}
function ieltsFullFinishSection(automatic=false){const session=ieltsFullSession();if(!session||!ieltsFullSections.includes(session.section))return;
  if(!automatic){ieltsFullDialog('提交本部分后不能返回修改。确定提交吗？',()=>ieltsFullFinishSection(true));return}
  const old=session.section;if(old==='listening'||old==='reading')session.results[old]=ieltsFullScore(session,old);
  else session.results.writingSaved=true;
  const next={listening:'reading',reading:'writing',writing:'finished'}[old];session.section=next;session.deadline=next==='finished'?null:Date.now()+(next==='writing'?60:next==='reading'?60:30)*60000;
  if(next==='finished'){session.completedAt=Date.now();sessionStorage.removeItem('ieltsFullActive')}saveIeltsFull();const box=$('#ieltsFullWorkspace');if(box)box.dataset.section='';renderIeltsFullExam()}
function ieltsFullClock(){clearInterval(ieltsFullTimer);const update=()=>{const session=ieltsFullSession();if(!session||session.section==='finished')return clearInterval(ieltsFullTimer);const remain=Math.max(0,session.deadline-Date.now()),clock=$('#ieltsFullClock');if(clock){clock.textContent=`${String(Math.floor(remain/60000)).padStart(2,'0')}:${String(Math.floor(remain%60000/1000)).padStart(2,'0')}`;clock.classList.toggle('warning',remain<=60000)}if(remain===0){clearInterval(ieltsFullTimer);ieltsFullFinishSection(true)}};update();ieltsFullTimer=setInterval(update,1000)}
function ieltsFullStopAudio(){ieltsFullSpeechToken++;ieltsFullAudioActive=null;if('speechSynthesis'in window)speechSynthesis.cancel();$('#ieltsFullAudio audio')?.pause()}
function ieltsFullAudio(item,part){const area=$('#ieltsFullAudio'),key=item.id+':'+part.number,session=ieltsFullSession();if(!area||area.dataset.part===key||ieltsFullAudioActive)return;ieltsFullStopAudio();area.dataset.part=key;session.audioProgress||={};const progress=session.audioProgress[key]||{started:false,complete:false,position:0};session.audioProgress[key]=progress;
  area.innerHTML=`<div class="ielts-full-audio-label">Part ${part.number} · ${part.audioUrl?'预录 TTS':'设备 TTS'}</div><button type="button" id="ieltsFullPlay" ${progress.complete?'disabled':''}>${progress.complete?'已播放':progress.started?'▶ 继续播放':'▶ 开始播放'}</button><label>音量 <input id="ieltsFullVolume" type="range" min="0" max="100" value="${Math.round(ieltsFullAudioVolume*100)}"></label>${part.audioUrl?`<audio preload="metadata" src="${esc(part.audioUrl)}"></audio>`:''}`;
  $('#ieltsFullVolume').oninput=e=>{ieltsFullAudioVolume=Number(e.target.value)/100;const audio=area.querySelector('audio');if(audio)audio.volume=ieltsFullAudioVolume};
  $('#ieltsFullPlay').onclick=()=>{if(ieltsFullAudioActive||progress.complete)return;if(!part.audioUrl&&!('speechSynthesis'in window))return toast('设备不支持语音合成');progress.started=true;saveIeltsFull();ieltsFullAudioActive=key;$('#ieltsFullPlay').disabled=true;$('#ieltsFullPlay').textContent='正在播放';const done=()=>{ieltsFullAudioActive=null;progress.complete=true;saveIeltsFull();$('#ieltsFullPlay').textContent='已播放'};
    if(part.audioUrl){const audio=area.querySelector('audio');audio.volume=ieltsFullAudioVolume;audio.currentTime=progress.position||0;audio.ontimeupdate=()=>{if(Math.abs(audio.currentTime-progress.position)>3){progress.position=audio.currentTime;saveIeltsFull()}};audio.onended=done;audio.play().catch(()=>{ieltsFullAudioActive=null;$('#ieltsFullPlay').disabled=false;$('#ieltsFullPlay').textContent='▶ 继续播放'});return}
    const token=ieltsFullSpeechToken;let pos=progress.position||0;const play=()=>{if(token!==ieltsFullSpeechToken)return;if(pos>=part.lines.length){done();return}const line=part.lines[pos++],speech=new SpeechSynthesisUtterance(line.text);speech.lang='en-GB';speech.volume=ieltsFullAudioVolume;speech.rate=.92;speech.onend=()=>{progress.position=pos;saveIeltsFull();if(token===ieltsFullSpeechToken)setTimeout(play,Math.min(30000,line.pauseAfterMs||0))};speechSynthesis.speak(speech)};play()}}
function ieltsFullRenderResult(session,mock,box){clearInterval(ieltsFullTimer);box.innerHTML=`<article class="card ielts-full-result"><span class="practice-label">${esc(mock.label)} · L/R/W 结果</span><h2>笔试已完成</h2><p>Listening ${session.results.listening} / 40</p><p>Reading ${session.results.reading} / 40</p><p>Writing Saved</p><div class="row"><button class="btn" id="ieltsFullCopy">复制题目与我的作文</button><button class="btn primary" id="ieltsFullSpeaking">开始 Speaking Test · ${esc(mock.speakingSetId)}</button><button class="btn" id="ieltsFullBack">返回题库</button></div></article>`;
  $('#ieltsFullCopy').onclick=async()=>{const t1=customOpen.writingTask1.find(t=>t.id===mock.writingTask1Id),t2=customOpen.writingTask2.find(t=>t.id===mock.writingTask2Id);const text=`Task 1\nQuestion: ${t1.prompt}\nMy Answer: ${session.drafts.writing1}\n\nTask 2\nQuestion: ${t2.prompt}\nMy Answer: ${session.drafts.writing2}`;try{await navigator.clipboard.writeText(text);toast('题目与作文已复制')}catch{toast('复制失败，请检查浏览器剪贴板权限')}};
  $('#ieltsFullSpeaking').onclick=()=>openCustomWork('speaking',mock.speakingSetId,mock.id);$('#ieltsFullBack').onclick=()=>nav('ielts-custom')}
// The exam shell reimplements interaction patterns from aknahin/ielts-on-computer (MIT, © 2026 Asrafuzzaman Khan Nahin).
function ieltsFullDialog(message,action){const layer=$('#ieltsFullModal');layer.hidden=false;layer.innerHTML=`<div class="ielts-full-dialog" role="dialog" aria-modal="true" aria-label="确认操作"><h3>请确认</h3><p>${esc(message)}</p><div class="ielts-full-actions"><button type="button" id="ieltsFullCancel">继续考试</button><button type="button" id="ieltsFullConfirm">确认</button></div></div>`;$('#ieltsFullCancel').onclick=()=>layer.hidden=true;$('#ieltsFullConfirm').onclick=()=>{layer.hidden=true;action()};$('#ieltsFullCancel').focus()}
function ieltsFullPreferences(session){session.examPreferences||={contrast:'standard',size:'regular',ratio:50};return session.examPreferences}
function ieltsFullOptions(session){const menu=$('#ieltsFullOptionsMenu'),prefs=ieltsFullPreferences(session);menu.hidden=!menu.hidden;if(menu.hidden)return;menu.innerHTML=`<h3>考试选项</h3><fieldset><legend>对比度</legend>${[['standard','白底黑字'],['dark','黑底白字'],['warm','暖色高对比']].map(([v,l])=>`<label><input type="radio" name="ielts-contrast" value="${v}" ${prefs.contrast===v?'checked':''}>${l}</label>`).join('')}</fieldset><fieldset><legend>文字大小</legend>${[['regular','标准'],['large','大'],['xlarge','特大']].map(([v,l])=>`<label><input type="radio" name="ielts-size" value="${v}" ${prefs.size===v?'checked':''}>${l}</label>`).join('')}</fieldset><button type="button" id="ieltsFullInstructionsButton">考试说明</button><button type="button" id="ieltsFullOptionsSubmit">提交本部分</button>`;
  menu.querySelectorAll('input').forEach(el=>el.onchange=()=>{prefs[el.name==='ielts-contrast'?'contrast':'size']=el.value;ieltsFullApplyPreferences(session);saveIeltsFull()});$('#ieltsFullInstructionsButton').onclick=()=>{menu.hidden=true;ieltsFullDialog('本部分计时持续运行；提交后不能返回。答案自动保存。阅读文章可选中文字进行标注。',()=>{})};$('#ieltsFullOptionsSubmit').onclick=()=>{menu.hidden=true;ieltsFullFinishSection()}}
function ieltsFullApplyPreferences(session){const box=$('#ieltsFullWorkspace'),prefs=ieltsFullPreferences(session);box.dataset.contrast=prefs.contrast;box.dataset.size=prefs.size;box.style.setProperty('--exam-split',prefs.ratio+'%')}
function ieltsFullSplit(session){const divider=$('#ieltsFullDivider'),panes=$('#ieltsFullPanes');if(!divider||!panes||session.section==='listening')return;const prefs=ieltsFullPreferences(session);const set=value=>{prefs.ratio=Math.max(25,Math.min(75,Math.round(value)));ieltsFullApplyPreferences(session);saveIeltsFull()};divider.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();set(prefs.ratio+(e.key==='ArrowLeft'?-5:5))}};divider.onpointerdown=e=>{e.preventDefault();divider.setPointerCapture(e.pointerId);divider.onpointermove=event=>{const rect=panes.getBoundingClientRect();set((event.clientX-rect.left)*100/rect.width)};divider.onpointerup=()=>divider.onpointermove=null}}
function ieltsFullPassageHTML(text,marks){let index=0;return String(text||'').split(/(\s+)/).map(chunk=>{if(!chunk.trim())return esc(chunk).replaceAll('\n','<br>');const id=index++;return `<span data-exam-word="${id}" class="${marks[id]?'ielts-full-mark':''}">${esc(chunk)}</span>`}).join('')}
function ieltsFullReadingTools(session,part){const key=String(part.number),source=$('#ieltsFullSource'),toolbar=$('#ieltsFullSelectionTools');session.highlights||={};session.notes||={};const marks=session.highlights[key]||{},notes=session.notes[key]||{};let selection=[];
  source.onmouseup=()=>{const sel=window.getSelection?.();if(!sel||sel.isCollapsed||!source.contains(sel.anchorNode)||!source.contains(sel.focusNode))return;const range=sel.getRangeAt(0),words=[...source.querySelectorAll('[data-exam-word]')].filter(span=>range.intersectsNode(span));selection=words.map(span=>span.dataset.examWord);toolbar.hidden=!selection.length};
  $('#ieltsFullHighlight').onclick=()=>{for(const id of selection)marks[id]=true;session.highlights[key]=marks;saveIeltsFull();source.querySelectorAll('[data-exam-word]').forEach(span=>span.classList.toggle('ielts-full-mark',Boolean(marks[span.dataset.examWord])));toolbar.hidden=true;window.getSelection?.()?.removeAllRanges()};
  $('#ieltsFullNoteButton').onclick=()=>{if(!selection.length)return;const id=selection[0];session.notes[key]||={};notes[id]||='';ieltsFullShowNotes(session,part,id);toolbar.hidden=true};
  $('#ieltsFullNotesToggle').onclick=()=>ieltsFullShowNotes(session,part);source.onclick=e=>{const span=e.target.closest?.('[data-exam-word]');if(span&&notes[span.dataset.examWord])ieltsFullShowNotes(session,part,span.dataset.examWord)};
}
function ieltsFullShowNotes(session,part,focusId){const key=String(part.number),panel=$('#ieltsFullNotes'),notes=session.notes?.[key]||{};panel.hidden=false;panel.innerHTML=`<div class="ielts-full-notes-title"><strong>阅读笔记 · Passage ${key}</strong><button type="button" id="ieltsFullNotesClose">关闭</button></div><label>选中文字后可添加笔记</label><textarea id="ieltsFullNoteText" rows="5" placeholder="此处记录笔记"></textarea><button type="button" id="ieltsFullNoteSave">保存笔记</button><div id="ieltsFullNotesList"></div>`;$('#ieltsFullNotesClose').onclick=()=>panel.hidden=true;const render=()=>{$('#ieltsFullNotesList').innerHTML=Object.entries(notes).map(([id,value])=>`<div class="ielts-full-note"><b>词 ${Number(id)+1}</b><p>${esc(value)}</p><button type="button" data-exam-note="${id}">编辑</button></div>`).join('');panel.querySelectorAll('[data-exam-note]').forEach(button=>button.onclick=()=>{$('#ieltsFullNoteText').value=notes[button.dataset.examNote];panel.dataset.word=button.dataset.examNote})};panel.dataset.word=focusId??'';if(focusId!==undefined)$('#ieltsFullNoteText').value=notes[focusId]||'';$('#ieltsFullNoteSave').onclick=()=>{if(!panel.dataset.word)return;notes[panel.dataset.word]=$('#ieltsFullNoteText').value;session.notes[key]=notes;saveIeltsFull();render()};render()}
function ieltsFullControl(item,part,q,answer){const raw=part.questions?.find(x=>x.number===Number(q.id.split(':').pop()));const group=part.groups?.find(g=>g.questions.some(x=>x.number===Number(q.id.split(':').pop())));const type=raw?.type||group?.type,options=raw?.options?Object.entries(raw.options).map(([key,label])=>({key,label})):group?.options?.map(x=>({key:x.key,label:x.text}))||[];
  if(type==='true_false_not_given'||type==='yes_no_not_given'){const keys=type==='true_false_not_given'?['TRUE','FALSE','NOT GIVEN']:['YES','NO','NOT GIVEN'];return `<div class="ielts-full-choices">${keys.map(key=>`<label><input type="radio" name="ielts-full-answer" value="${key}" ${String(answer).toUpperCase()===key?'checked':''}>${key}</label>`).join('')}</div>`}
  if(type==='multiple_choice'&&options.length)return `<div class="ielts-full-choices">${options.map(({key,label})=>`<label><input type="radio" name="ielts-full-answer" value="${esc(key)}" ${answer===key?'checked':''}><b>${esc(key)}</b> ${esc(label)}</label>`).join('')}</div>`;
  if(type?.startsWith('matching')&&options.length)return `<select id="ieltsFullAnswer" class="field" aria-label="选择答案"><option value="">选择答案</option>${options.map(({key,label})=>`<option value="${esc(key)}" ${answer===key?'selected':''}>${esc(key)} · ${esc(label)}</option>`).join('')}</select>`;
  return `<input id="ieltsFullAnswer" class="field" type="text" autocomplete="off" aria-label="第 ${esc(q.id.split(':').pop())} 题答案" placeholder="输入答案" value="${esc(answer)}">`}
async function renderIeltsFullExam(){const box=$('#ieltsFullWorkspace');if(!box)return;const session=ieltsFullSession();if(!session){nav('ielts-custom');return}try{await loadIeltsCustom()}catch(error){box.textContent='题库加载失败：'+error.message;return}const mock=customMock(session.mockId);if(!customMockReady(mock)){box.textContent='此模拟卷的题目不完整';return}if(session.section==='finished')return ieltsFullRenderResult(session,mock,box);if(session.deadline<=Date.now()){ieltsFullFinishSection(true);return}
  if(box.dataset.section!==session.section){ieltsFullStopAudio();box.dataset.section=session.section;box.innerHTML=`<div class="ielts-full-top"><div class="ielts-full-brand"><strong>CUSTOM TRAINING MOCK</strong><span>${esc(mock.label)} · <span id="ieltsFullSection"></span></span></div><div class="ielts-full-clock-wrap"><span>剩余时间</span><strong class="exam-clock" id="ieltsFullClock">00:00</strong></div><div class="ielts-full-head-actions"><button type="button" id="ieltsFullOptionsButton" aria-expanded="false">Options ▾</button><button type="button" id="ieltsFullExit">退出</button></div><div class="ielts-full-options" id="ieltsFullOptionsMenu" hidden></div></div><div class="ielts-full-instruction"><span id="ieltsFullProgress"></span><button type="button" id="ieltsFullNotesToggle" hidden>笔记</button><button type="button" id="ieltsFullSubmit">提交本部分</button></div><div class="ielts-full-panes" id="ieltsFullPanes"><article class="ielts-full-source" id="ieltsFullSourcePane"><div id="ieltsFullSource"></div><div id="ieltsFullAudio"></div></article><div class="ielts-full-divider" id="ieltsFullDivider" role="separator" aria-orientation="vertical" aria-label="调整左右区域宽度" tabindex="0"></div><article class="ielts-full-question"><div id="ieltsFullQuestion"></div><div class="ielts-full-question-actions"><button type="button" id="ieltsFullPrevious">← 上一题</button><button type="button" id="ieltsFullFlag">标记 Review</button><button type="button" id="ieltsFullNext">下一题 →</button></div></article></div><div class="ielts-full-selection" id="ieltsFullSelectionTools" hidden><button type="button" id="ieltsFullHighlight">高亮</button><button type="button" id="ieltsFullNoteButton">添加笔记</button></div><aside class="ielts-full-notes" id="ieltsFullNotes" hidden></aside><div class="ielts-full-bottom"><span id="ieltsFullPartLabel"></span><div id="ieltsFullNavigator" class="exam-number-nav"></div></div><div id="ieltsFullModal" class="ielts-full-modal" hidden></div>`;
    $('#ieltsFullExit').onclick=()=>ieltsFullDialog('退出考试？答卷和剩余时间会保留，计时不会暂停。',()=>{ieltsFullStopAudio();clearInterval(ieltsFullTimer);saveIeltsFull();sessionStorage.removeItem('ieltsFullActive');nav('ielts-custom')});$('#ieltsFullSubmit').onclick=()=>ieltsFullFinishSection();$('#ieltsFullOptionsButton').onclick=()=>{ieltsFullOptions(session);$('#ieltsFullOptionsButton').setAttribute('aria-expanded',String(!$('#ieltsFullOptionsMenu').hidden))};ieltsFullSplit(session)}
  const section=session.section;$('#ieltsFullSection').textContent={listening:'Listening',reading:'Academic Reading',writing:'Writing'}[section];$('#ieltsFullProgress').textContent={listening:'听力 · 30 分钟 · 请按顺序听完每个 Part',reading:'阅读 · 60 分钟 · 可以选择文字高亮或记笔记',writing:'写作 · Task 1 与 Task 2 共用 60 分钟'}[section];$('#ieltsFullNotesToggle').hidden=section!=='reading';ieltsFullApplyPreferences(session);
  if(section==='writing')renderIeltsFullWriting(session,mock);else renderIeltsFullQuestions(session,mock);ieltsFullClock()}
function renderIeltsFullQuestions(session,mock){const section=session.section,questions=ieltsFullQuestions(session),index=session.indices[section]||0,q=questions[index];if(!q)return;const answers=session.answers[section],flags=session.flags[section],item=section==='listening'?customListening(mock.listeningId):customReading(mock.readingId),part=item.parts.find(p=>q.section.endsWith('Part '+p.number));
  let previousPart=0;$('#ieltsFullNavigator').innerHTML=questions.map((question,i)=>{const number=Number(question.id.split(':').pop()),group=item.parts.find(p=>section==='listening'?p.questions?.some(x=>x.number===number):p.groups?.some(g=>g.questions.some(x=>x.number===number))),partNumber=group?.number||Number(question.section.match(/Part (\d+)/)?.[1]||1),first=partNumber!==previousPart;previousPart=partNumber;return `${first?`<span class="ielts-full-part-chip">Part ${partNumber}</span>`:''}<button type="button" aria-label="第 ${i+1} 题${flags[question.id]?'，已标记':''}" class="${i===index?'active':''} ${answers[question.id]?'answered':''} ${flags[question.id]?'review':''}" data-ielts-full-index="${i}">${i+1}</button>`}).join('');$$('[data-ielts-full-index]').forEach(b=>b.onclick=()=>{session.indices[section]=Number(b.dataset.ieltsFullIndex);saveIeltsFull();renderIeltsFullQuestions(session,mock)});
  $('#ieltsFullPartLabel').textContent=`${section==='listening'?'Listening':'Reading'} · Part ${part.number}`;const source=$('#ieltsFullSource'),sourceKey=item.id+':'+part.number;if(section==='reading'){const marks=session.highlights?.[String(part.number)]||{};if(source.dataset.part!==sourceKey){source.dataset.part=sourceKey;source.innerHTML=`<h2>${esc(part.title)}</h2><div class="exam-source-content">${ieltsFullPassageHTML(q.content?.passage||'',marks)}</div>`;source.scrollTop=0}$('#ieltsFullAudio').innerHTML='';ieltsFullReadingTools(session,part);const layout=customReadingLayout(q.content?.layout);$('#ieltsFullQuestion').dataset.layout=layout?'1':'0'}
  else{source.dataset.part=sourceKey;source.innerHTML=`<h2>Listening · Part ${part.number}</h2><p>请听录音并回答对应问题。录音原文和答案在考试中不可查看。</p>`;ieltsFullAudio(item,part)}
  const number=Number(q.id.split(':').pop()),original=part.questions?.find(x=>x.number===number)||part.groups?.flatMap(g=>g.questions).find(x=>x.number===number),group=part.groups?.find(g=>g.questions.some(x=>x.number===number)),stem=original?.options||group?.options?[original.instruction||group?.instruction,original.prompt].filter(Boolean).join('\n'):q.stem;
  const control=ieltsFullControl(item,part,q,String(answers[q.id]||''));$('#ieltsFullQuestion').innerHTML=`<div class="ielts-full-question-head"><span>Part ${part.number}</span><strong>Question ${index+1} / 40</strong></div>${section==='reading'&&q.content?.layout?customReadingLayout(q.content.layout):''}<div class="ielts-full-prompt">${esc(stem).replaceAll('\n','<br>')}</div><label class="ielts-full-answer-label" for="ieltsFullAnswer">你的答案</label>${control}<small id="ieltsFullSaveState">已自动保存</small>`;
  const update=value=>{answers[q.id]=value;saveIeltsFull();$('[data-ielts-full-index="'+index+'"]').classList.toggle('answered',Boolean(value.trim()));$('#ieltsFullSaveState').textContent='已自动保存'};const field=$('#ieltsFullAnswer');if(field)field.oninput=e=>update(e.target.value);$('#ieltsFullQuestion').querySelectorAll('input[name="ielts-full-answer"]').forEach(el=>el.onchange=e=>update(e.target.value));
  $('#ieltsFullPrevious').disabled=index===0;$('#ieltsFullNext').disabled=index===39;$('#ieltsFullPrevious').onclick=()=>{session.indices[section]=index-1;saveIeltsFull();renderIeltsFullQuestions(session,mock)};$('#ieltsFullNext').onclick=()=>{session.indices[section]=index+1;saveIeltsFull();renderIeltsFullQuestions(session,mock)};$('#ieltsFullFlag').hidden=false;$('#ieltsFullFlag').textContent=flags[q.id]?'✓ 已标记 Review':'⚑ 标记 Review';$('#ieltsFullFlag').onclick=()=>{flags[q.id]=!flags[q.id];saveIeltsFull();renderIeltsFullQuestions(session,mock)}}
function renderIeltsFullWriting(session,mock){const key=session.writingTab,task=key==='writing1'?customOpen.writingTask1.find(t=>t.id===mock.writingTask1Id):customOpen.writingTask2.find(t=>t.id===mock.writingTask2Id),draft=session.drafts[key]||'';
  $('#ieltsFullPartLabel').textContent='Writing';$('#ieltsFullNavigator').innerHTML=`<button type="button" class="${key==='writing1'?'active':''}" data-ielts-writing="writing1">Task 1</button><button type="button" class="${key==='writing2'?'active':''}" data-ielts-writing="writing2">Task 2</button>`;$$('[data-ielts-writing]').forEach(b=>b.onclick=()=>{session.writingTab=b.dataset.ieltsWriting;saveIeltsFull();renderIeltsFullWriting(session,mock)});
  $('#ieltsFullSource').innerHTML=`<h2>${key==='writing1'?'Academic Task 1':'Task 2'} · ${esc(task.type)}</h2><p>${esc(task.prompt).replaceAll('\n','<br>')}</p>${task.chartSpec?customChart(task.chartSpec):''}`;$('#ieltsFullAudio').innerHTML='';$('#ieltsFullQuestion').innerHTML=`<label for="ieltsFullDraft">我的作文 · 自动保存</label><textarea id="ieltsFullDraft" class="rec-text" rows="18" placeholder="在这里写作文">${esc(draft)}</textarea><p id="ieltsFullWordCount">${draft.trim()?draft.trim().split(/\s+/).length:0} words</p><small>提交 Writing 后，可在结果页复制题目与作文。</small>`;
  $('#ieltsFullDraft').oninput=e=>{session.drafts[key]=e.target.value;$('#ieltsFullWordCount').textContent=(e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0)+' words';saveIeltsFull()};$('#ieltsFullPrevious').disabled=key==='writing1';$('#ieltsFullNext').disabled=key==='writing2';$('#ieltsFullFlag').hidden=true;$('#ieltsFullPrevious').onclick=()=>{session.writingTab='writing1';saveIeltsFull();renderIeltsFullWriting(session,mock)};$('#ieltsFullNext').onclick=()=>{session.writingTab='writing2';saveIeltsFull();renderIeltsFullWriting(session,mock)}}
window.addEventListener('pagehide',()=>{clearInterval(ieltsFullTimer);ieltsFullSpeechToken++});
if(sessionStorage.getItem('ieltsFullActive')===state.examEngine.ieltsFullSession?.mockId&&state.examEngine.ieltsFullSession.section!=='finished')nav('ielts-full-exam');
