/* IELTS Custom Training Mock: stable references and canonical current-season speaking. */
let customManifest=null,customOpen=null,customSpeaking=null,customTab='mocks',customWork=null,customSpeakingTab='sets';
let customSpeechToken=0,customSpeechPart='';
async function loadIeltsCustom(){if(!customManifest){const [m,o,s]=await Promise.all([fetch('data/ielts-custom-manifest.json'),fetch('data/ielts-custom-open.json'),fetch('data/ielts-speaking-2026-09.json')]);if(!m.ok||!o.ok||!s.ok)throw new Error('IELTS 数据加载失败');customManifest=await m.json();customOpen=await o.json();customSpeaking=await s.json()}return customManifest}
function customProgress(id){state.examEngine.customMockProgress=state.examEngine.customMockProgress||{};return state.examEngine.customMockProgress[id]||(state.examEngine.customMockProgress[id]={sections:{},drafts:{}})}
function completeCustomMockSection(id,section){if(!id||!section)return;customProgress(id).sections[section]=Date.now();save({immediate:true,refresh:false})}
function customMock(id){return customManifest.mocks.find(mock=>mock.id===id)}
function customReading(id){return customOpen.reading.find(item=>item.id===id)}
function customListening(id){return customOpen.listening.find(item=>item.id===id)}
function customMockReady(mock){if(!mock||mock.status!=='ready'||mock.missingSections?.length)return false;const l=customListening(mock.listeningId);return Boolean(l&&customReading(mock.readingId)&&customSpeaking&&(l.audioType!=='TTS'||'speechSynthesis'in window))}
async function renderIeltsCustom(){const panel=$('#customCatalog');if(!panel)return;panel.innerHTML='<p class="sub">正在读取题库目录…</p>';try{await loadIeltsCustom()}catch(error){panel.textContent='题库加载失败：'+error.message;return}
  $('#customSpeakingStatus').textContent='当季原题已内置：43 个 Part 1 话题、46 张 cue card、46 组 Part 3；S001–S030 固定引用。';
  $$('[data-custom-tab]').forEach(button=>button.classList.toggle('primary',button.dataset.customTab===customTab));
  if(customTab==='mocks')panel.innerHTML=`<p class="sub">完整机考模拟：${customManifest.mocks.filter(customMockReady).length} 套。按听力 → 阅读 → 写作进行，统一结果页后单独进入口语。未完成的引用仍保存在 manifest，专项题目可在各科题库练习。</p><div class="custom-grid">${customManifest.mocks.filter(customMockReady).map(mock=>{const l=customListening(mock.listeningId);return `<article class="card custom-card"><h3>${esc(mock.label)}</h3><small>IELTS EXAM MODE · 自组训练卷</small><p>Listening 40Q · ${l.audioType==='TTS'?'设备 TTS':'预录 TTS'}<br>Reading 40Q · Writing Task 1 + Task 2 · ${esc(mock.speakingSetId)}</p><button class="btn primary" data-custom-full="${mock.id}">开始机考模拟</button></article>`}).join('')}</div>`;
  else if(customTab==='listening')panel.innerHTML=`<h3>Listening 专项 · ${customOpen.listening.length} 套完整 40 题</h3><p class="sub">设备 TTS 7 套、预录 TTS 1 套；非真人考试录音。</p><div class="custom-grid">${customOpen.listening.map(item=>`<article class="card custom-card"><h3>${esc(item.id)} · ${esc(item.title)}</h3><p>${esc(item.audioType)} · 40Q / 40A</p><small>来源：${esc(item.sourceRepo)} · ${esc(item.contentLicense)}</small><button class="btn" data-custom-solo="listening:${item.id}">开始专项训练</button></article>`).join('')}</div>`;
  else if(customTab==='reading')panel.innerHTML=`<h3>Academic Reading 专项 · ${customOpen.reading.length} 套完整 40 题</h3><div class="custom-grid">${customOpen.reading.map(item=>`<article class="card custom-card"><h3>${esc(item.id)} · ${esc(item.title)}</h3><p>Passage 1–3 · 40Q / 40A</p><button class="btn" data-custom-solo="reading:${item.id}">开始专项训练</button></article>`).join('')}</div>`;
  else if(customTab==='writing')panel.innerHTML=`<h3>Writing Bank</h3><p class="sub">Task 1：38 道 prompt 与可绘制图表 · Task 2：42 道 prompt。</p><div class="custom-grid">${[...customOpen.writingTask1,...customOpen.writingTask2].map(item=>`<article class="card custom-card"><h3>${esc(item.id)} · ${esc(item.type)}</h3><p>${esc(item.prompt.slice(0,100))}…</p><button class="btn" data-custom-solo="writing:${item.id}">打开写作</button></article>`).join('')}</div>`;
  else {const sections={sets:customManifest.speakingSets,part1:customSpeaking.part1,part2:customSpeaking.part2,part3:customSpeaking.part3};panel.innerHTML=`<h3>Speaking · 2026 年 9–12 月</h3><p>43 Part 1 topics / 247 questions · 46 cue cards · 46 Part 3 groups / 233 questions</p><div class="row">${Object.entries({sets:'S001–S030',part1:'Part 1 Bank',part2:'Part 2 Bank',part3:'Part 3 Bank'}).map(([id,label])=>`<button class="btn ${customSpeakingTab===id?'primary':''}" data-speaking-bank="${id}">${label}</button>`).join('')}</div><div class="custom-grid">${sections[customSpeakingTab].map(item=>`<article class="card custom-card"><h3>${esc(item.id)} · ${esc(item.title||item.prompt||'当季题组')}</h3><p>${customSpeakingTab==='sets'?esc(item.part1TopicIds.join(' · ')+' · '+item.part2CueCardId+' → '+item.part3GroupId):customSpeakingTab==='part1'?item.questions.map(esc).join('<br>'):customSpeakingTab==='part2'?esc(item.cuePoints.join(' · ')):item.questions.map(esc).join('<br>')}</p>${customSpeakingTab==='sets'?`<button class="btn" data-custom-solo="speaking:${item.id}">开始口语专项</button>`:''}</article>`).join('')}</div>`}
  $$('[data-speaking-bank]').forEach(button=>button.onclick=()=>{customSpeakingTab=button.dataset.speakingBank;renderIeltsCustom()});
  $$('[data-custom-full]').forEach(b=>b.onclick=()=>launchCustomFull(b.dataset.customFull));$$('[data-custom-start]').forEach(b=>b.onclick=()=>{const [id,section]=b.dataset.customStart.split(':');startCustomSection(id,section)});$$('[data-custom-solo]').forEach(b=>b.onclick=()=>{const [kind,id]=b.dataset.customSolo.split(':');startCustomSolo(kind,id)});
}
function launchCustomFull(id){const mock=customMock(id);if(!customMockReady(mock))return toast('整套仍缺可用资料');startIeltsFullMock(id)}
function startCustomSection(id,section){const mock=customMock(id);if(!mock)return;if(section==='listening')return startCustomExam('listening',mock.listeningId,id);if(section==='reading')return startCustomExam('reading',mock.readingId,id);if(section==='speaking')return openCustomWork('speaking',mock.speakingSetId,id);return openCustomWork('writing',section==='writing2'?mock.writingTask2Id:mock.writingTask1Id,id)}
function startCustomSolo(kind,id){if(kind==='reading'||kind==='listening')startCustomExam(kind,id,null);else openCustomWork(kind,id,null)}
function customAnswerVariants(value){if(Array.isArray(value))return [...new Set(value.flat(Infinity).map(item=>typeof item==='object'?item.value:item).map(String))];return [String(value)]}
function customQuestions(kind,item){return item.parts.flatMap(part=>kind==='listening'?part.questions.map(q=>({n:q.number,stem:[q.instruction,q.prompt,q.options&&Object.entries(q.options).map(([key,value])=>`${key}. ${value}`).join('\n')].filter(Boolean).join('\n'),answer:q.answer,explanation:q.explanation,part})):
  part.groups.flatMap(g=>g.questions.map(q=>({n:q.number,stem:[g.instruction,g.options?.map(option=>`${option.key}. ${option.text}`).join('\n'),q.prompt].filter(Boolean).join('\n'),answer:q.answers,explanation:q.explanation,part,layout:g.layout}))));}
function startCustomExam(kind,id,mockId){const item=kind==='reading'?customReading(id):customListening(id);if(!item)return toast('这份资料还没有加载');if(kind==='listening'&&item.audioType==='TTS'&&!('speechSynthesis'in window))return toast('当前设备不支持合成语音，不能开始听力');
  privateComputerQuestions=buildCustomExamQuestions(kind,item);
  if(privateComputerQuestions.length!==40)return toast('题目不足 40，拒绝启动');const now=Date.now();state.examEngine.activeSession={id:'exam-'+now.toString(36),customMockId:mockId,customSection:kind,customBankId:id,projectId:'ielts',type:`ielts_${kind}`,mode:'exam',format:'timed',questionIds:privateComputerQuestions.map(q=>q.id),index:0,answers:{},review:{},highlights:[],startedAt:now,deadline:now+(kind==='reading'?60:30)*60000,completedAt:null,result:null};save({immediate:true,refresh:false});nav('computer-exam')}
function renderCustomListeningAudio(session,question){if(session.type!=='ielts_listening')return;const item=customListening(session.customBankId),part=item?.parts.find(p=>question.section.endsWith('Part '+p.number));const area=$('#computerAudioArea');if(!part||!area)return;const partId=session.customBankId+':'+part.number;
  if(part.audioUrl){const existing=area.querySelector('audio[data-custom-part]');if(existing?.dataset.customPart===partId)return;area.innerHTML=`<p class="sub">Part ${part.number} · 来源提供的预录 TTS；按需加载</p><audio controls preload="metadata" data-custom-part="${esc(partId)}" src="${esc(part.audioUrl)}"></audio>`;return}
  if(customSpeechPart&&customSpeechPart!==partId){customSpeechToken++;speechSynthesis.cancel();customSpeechPart=''}if(area.dataset.customPart===partId)return;area.dataset.customPart=partId;area.innerHTML=`<p class="sub">Part ${part.number} · 设备合成语音模拟（非真人或原始考试录音；练习停顿不计时）</p><button class="btn primary" id="customPlayPart">▶ 播放本 Part</button><button class="btn" id="customStopPart">■ 停止</button>`;$('#customPlayPart').onclick=()=>{customSpeechToken++;speechSynthesis.cancel();customSpeechPart=partId;const token=customSpeechToken;let index=0;const play=()=>{if(token!==customSpeechToken||index>=part.lines.length)return;const line=part.lines[index++],utterance=new SpeechSynthesisUtterance(line.text);utterance.lang='en-GB';utterance.rate=.92;utterance.onend=play;speechSynthesis.speak(utterance)};play()};$('#customStopPart').onclick=()=>{customSpeechToken++;customSpeechPart='';speechSynthesis.cancel()}}
function buildCustomExamQuestions(kind,item){return customQuestions(kind,item).map(({n,stem,answer,explanation,part,layout})=>normalizeExamQuestion({id:`custom:${item.id}:${n}`,projectId:'ielts',type:`ielts_${kind}`,section:`${item.title} · Part ${part.number}`,stem,answer:customAnswerVariants(answer),explanation,content:kind==='reading'?{title:part.title,passage:part.texts.flatMap(t=>t.paragraphs||[]).map(p=>(p.id?p.id+'\n':'')+p.text).join('\n\n'),layout}:null,sourceType:'custom_open',license:item.contentLicense,attribution:item.sourceRepo},'ielts'))}
function customReadingLayout(layout){if(!layout)return '';const heading=`<h4>${esc(layout.title||'')}</h4>`,line=s=>esc(String(s)).replaceAll(/\{\{(\d+)\}\}/g,'<b>[$1]</b>');
  if(layout.kind==='note'||layout.kind==='flow_chart')return `<section class="custom-reading-layout">${heading}${(layout.lines||layout.steps||[]).map(value=>`<p>${line(value)}</p>`).join('')}</section>`;
  if(layout.kind==='table')return `<section class="custom-reading-layout">${heading}<div class="custom-table-wrap"><table><tr>${(layout.columns||[]).map(cell=>`<th>${esc(cell)}</th>`).join('')}</tr>${(layout.rows||[]).map(row=>`<tr>${row.map(cell=>`<td>${line(cell)}</td>`).join('')}</tr>`).join('')}</table></div></section>`;
  if(layout.kind==='diagram'&&layout.image==='data/ielts-custom-media/dg_front_pack_panel.svg')return `<section class="custom-reading-layout">${heading}<img src="${layout.image}" alt="${esc(layout.alt||'阅读图示')}" width="400" height="300"></section>`;
  return ''}
function renderCustomReadingLayout(question){if(question?.sourceType!=='custom_open'||question.type!=='ielts_reading')return;const html=customReadingLayout(question.content?.layout);if(html)$('#computerSourceContent').insertAdjacentHTML('afterbegin',html)}
const customColors=['#6259c5','#28a7a0','#ed9b56','#bb68b3','#507fc8','#91a951'];
function customChart(spec){if(!spec)return '<p class="sub">缺少图表媒体。</p>';
  const title=`<h3>${esc(spec.title||'')}</h3>`, kind=spec.kind;
  if(kind==='mixed')return `<div class="custom-chart-mixed">${(spec.panels||[]).map(customChart).join('')}</div>`;
  if(kind==='table')return title+`<div class="custom-table-wrap"><table>${(spec.rows||[]).map((row,i)=>`<tr>${row.map(cell=>i?`<td>${esc(String(cell))}</td>`:`<th>${esc(String(cell))}</th>`).join('')}</tr>`).join('')}</table></div>`;
  if(kind==='process')return title+`<div class="custom-process">${(spec.steps||[]).map((step,i)=>`<div><b>${i+1}. ${esc(step.label)}</b><small>${step.next?.length?'→ '+step.next.map(next=>esc((spec.steps.find(s=>s.id===next)||{label:next}).label)).join(' / '):'流程终点'}</small></div>`).join('')}</div>`;
  if(kind==='map')return title+`<div class="custom-chart-mixed">${(spec.snapshots||[]).map(snap=>`<figure><figcaption>${esc(snap.label)}</figcaption><svg role="img" aria-label="${esc(snap.label)}" viewBox="0 0 600 350"><rect width="600" height="350" fill="#f4f8f5"/>${(snap.features||[]).map(f=>{const x=Number(f.x)*6,y=Number(f.y)*3.5,w=Number(f.w)*6,h=Number(f.h)*3.5,fill=f.shape==='river'?'#8ac4d7':f.shape==='road'?'#b9b7bd':f.shape==='tree'?'#90bc84':'#ddd1b7';return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${f.shape==='circle'?Math.min(w,h)/2:5}" fill="${fill}" stroke="#6e7882"/><text x="${x+w/2}" y="${y+h/2}" text-anchor="middle" font-size="11">${esc(f.label)}</text>`}).join('')}</svg></figure>`).join('')}</div>`;
  const categories=spec.x_axis?.categories||[],series=spec.series||[];
  if(kind==='pie'){let offset=0;const vals=series[0]?.values||[],total=vals.reduce((a,b)=>a+Number(b),0);const sectors=vals.map((raw,i)=>{const share=Number(raw)/total,a=offset*2*Math.PI-Math.PI/2,b=(offset+share)*2*Math.PI-Math.PI/2;offset+=share;const x1=200+135*Math.cos(a),y1=180+135*Math.sin(a),x2=200+135*Math.cos(b),y2=180+135*Math.sin(b);return `<path d="M 200 180 L ${x1} ${y1} A 135 135 0 ${share>.5?1:0} 1 ${x2} ${y2} Z" fill="${customColors[i%6]}" stroke="white" stroke-width="2"/>`}).join('');return title+`<svg viewBox="0 0 600 360" role="img" aria-label="${esc(spec.title)}">${sectors}${categories.map((cat,i)=>`<rect x="370" y="${42+i*42}" width="14" height="14" fill="${customColors[i%6]}"/><text x="392" y="${54+i*42}" font-size="13">${esc(cat)}: ${esc(String(vals[i]))}</text>`).join('')}</svg>`}
  const max=Number(spec.y_axis?.max)||Math.max(1,...series.flatMap(s=>s.values||[]).map(Number)),min=Number(spec.y_axis?.min)||0,span=Math.max(1,max-min),x=i=>70+i*470/Math.max(1,categories.length-1),y=v=>260-(Number(v)-min)*210/span;
  const grid=[0,.25,.5,.75,1].map(t=>`<line x1="60" x2="550" y1="${260-t*210}" y2="${260-t*210}" stroke="#dae0ec"/><text x="48" y="${264-t*210}" text-anchor="end" font-size="11">${Math.round((min+t*span)*100)/100}</text>`).join('');
  let marks='';for(let j=0;j<series.length;j++){const s=series[j],color=customColors[j%6];if(kind==='line'){marks+=`<polyline fill="none" stroke="${color}" stroke-width="3" points="${s.values.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}"/>`+s.values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="${color}"/>`).join('')}
    else marks+=s.values.map((v,i)=>{let bottom=0;if(kind==='stacked_bar')bottom=series.slice(0,j).reduce((n,prev)=>n+Number(prev.values[i]||0),0);const width=kind==='grouped_bar'?Math.min(26,350/categories.length/series.length):Math.min(50,350/categories.length),bx=70+i*470/Math.max(1,categories.length)+(kind==='grouped_bar'?(j-series.length/2)*width:0)-width/2;return `<rect x="${bx}" y="${y(bottom+v)}" width="${width}" height="${Math.max(0,y(bottom)-y(bottom+v))}" fill="${color}"/>`}).join('')}
  return title+`<svg viewBox="0 0 600 360" role="img" aria-label="${esc(spec.title)}">${grid}${marks}${categories.map((cat,i)=>`<text x="${x(i)}" y="285" text-anchor="end" transform="rotate(-30 ${x(i)} 285)" font-size="11">${esc(cat)}</text>`).join('')}${series.map((s,j)=>`<rect x="${70+j*125}" y="335" width="12" height="12" fill="${customColors[j%6]}"/><text x="${86+j*125}" y="345" font-size="11">${esc(s.name)}</text>`).join('')}</svg><p class="sub">${esc(spec.unit||'')}</p>`
}
function openCustomWork(kind,id,mockId){const item=kind==='speaking'?customManifest?.speakingSets.find(set=>set.id===id):[...customOpen.writingTask1,...customOpen.writingTask2].find(task=>task.id===id);if(!item||kind==='speaking'&&!customSpeaking)return toast('所选题目未加载');customWork={kind,id,mockId};nav('ielts-custom-work')}
function renderIeltsCustomWork(){const box=$('#customWorkspace');if(!customWork||!box)return;const {kind,id,mockId}=customWork;
  if(kind==='speaking'){const set=customManifest.speakingSets.find(s=>s.id===id),p1=set.part1TopicIds.map(key=>customSpeaking.part1.find(t=>t.id===key)),p2=customSpeaking.part2.find(c=>c.id===set.part2CueCardId),p3=customSpeaking.part3.find(g=>g.id===set.part3GroupId);if(p1.some(x=>!x)||!p2||!p3||p3.linkedPart2Id!==p2.id){box.textContent='口语题库引用错误';return}
    box.innerHTML=`<button class="btn" id="customBack">← 返回题库</button><span class="practice-label">自组训练 Mock · ${esc(id)}</span><h2>Speaking</h2><h3>Part 1</h3>${p1.map(t=>`<section><h4>${esc(t.title)}</h4><ol>${t.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol></section>`).join('')}<h3>Part 2 · ${esc(p2.id)}</h3><p>${esc(p2.prompt)}</p><ul>${p2.cuePoints.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><h3>Part 3 · ${esc(p3.id)}</h3><ol>${p3.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol><div class="row"><button class="btn" data-go-page="language-skills">打开现有录音工具</button><button class="btn primary" id="customFinish">标记本次口语完成</button></div>`;
  }else {const task=[...customOpen.writingTask1,...customOpen.writingTask2].find(t=>t.id===id),section=id.startsWith('WT1')?'writing1':'writing2';state.examEngine.customPractice=state.examEngine.customPractice||{drafts:{}};const progress=mockId?customProgress(mockId):state.examEngine.customPractice,text=progress.drafts?.[id]||'';box.innerHTML=`<button class="btn" id="customBack">← 返回题库</button><span class="practice-label">IELTS Writing ${section==='writing1'?'Task 1':'Task 2'} · ${esc(id)}</span><h2>${esc(task.type)}</h2><p class="custom-prompt">${esc(task.prompt).replaceAll('\n','<br>')}</p>${task.chartSpec?`<div class="custom-media">${customChart(task.chartSpec)}</div>`:''}<label for="customDraft">我的作文 · 自动保存在当前学习空间</label><textarea id="customDraft" class="rec-text" rows="14" placeholder="在这里写作文">${esc(text)}</textarea><p id="customWordCount">${text.trim()?text.trim().split(/\s+/).length:0} words</p><div class="row"><button class="btn" id="customCopy">复制题目与作文</button><button class="btn primary" id="customFinish">标记本题完成</button></div>`;
    $('#customDraft').oninput=()=>{const text=$('#customDraft').value;$('#customWordCount').textContent=(text.trim()?text.trim().split(/\s+/).length:0)+' words';progress.drafts[id]=text;save({refresh:false})};
    $('#customCopy').onclick=async()=>{const result=`IELTS Writing ${section==='writing1'?'Task 1':'Task 2'}\nQuestion:\n${task.prompt}\n\nMy Answer:\n${$('#customDraft').value}`;try{await navigator.clipboard.writeText(result);toast('已复制题目与作文')}catch{toast('浏览器不允许自动复制，请手动选取文本')}};
  }
  $('#customBack').onclick=()=>nav('ielts-custom');const recordButton=box.querySelector('[data-go-page="language-skills"]');if(recordButton)recordButton.onclick=()=>nav('language-skills');$('#customFinish').onclick=()=>{if(mockId)completeCustomMockSection(mockId,kind==='speaking'?'speaking':id.startsWith('WT1')?'writing1':'writing2');toast('已记录到本机');nav('ielts-custom')};
}
window.addEventListener('pagehide',()=>{customSpeechToken++;if('speechSynthesis'in window)speechSynthesis.cancel()});
$$('[data-custom-tab]').forEach(button=>button.onclick=()=>{customTab=button.dataset.customTab;renderIeltsCustom()});
if(sessionStorage.getItem('ieltsCustomReturn')){sessionStorage.removeItem('ieltsCustomReturn');setTimeout(()=>nav('ielts-custom'),100)}
else if(state.examEngine.activeSession?.customBankId&&!state.examEngine.activeSession.completedAt){loadIeltsCustom().then(()=>{const session=state.examEngine.activeSession,kind=session.type==='ielts_reading'?'reading':'listening',item=kind==='reading'?customReading(session.customBankId):customListening(session.customBankId);if(item){privateComputerQuestions=buildCustomExamQuestions(kind,item);nav('computer-exam')}}).catch(console.error)}
