const ENGLISH_RELATION_DECKS=new Set(['toeic_core','toeic_full','ielts_core','kaoyan_core','tem8','tem8_core','tem8_full']);
const ENGLISH_EXAM_TAGS={toeic_core:'TOEIC',toeic_full:'TOEIC',ielts_core:'IELTS',kaoyan_core:'postgraduate',tem8:'TEM8',tem8_core:'TEM8',tem8_full:'TEM8'};
const ENGLISH_EXAM_LABELS={postgraduate:'考研英语',general:'通用英语'};
let englishRelationsPromise=null;
const englishRelationShardPromises=new Map();

function isEnglishRelationDeck(deck){return !!deck&&(!deck.builtin||ENGLISH_RELATION_DECKS.has(deck.id))}
function englishRelationShardKey(word){const first=normWord(word).charAt(0);return /[a-z]/.test(first)?first:'_'}
function loadEnglishRelationManifest(){if(!englishRelationsPromise)englishRelationsPromise=fetch(new URL('data/english-word-relations.json',document.baseURI),{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('English relations HTTP '+response.status);return response.json()}).catch(error=>{console.warn(error);return {entries:{}}});return englishRelationsPromise}
async function loadEnglishRelations(word){const manifest=await loadEnglishRelationManifest();if(manifest.entries)return manifest;const shard=manifest.shards?.[englishRelationShardKey(word)];if(!shard)return {...manifest,entries:{}};if(!englishRelationShardPromises.has(shard.file))englishRelationShardPromises.set(shard.file,fetch(new URL(shard.file,document.baseURI),{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('English relation shard HTTP '+response.status);return response.json()}).catch(error=>{console.warn(error);return {entries:{}}}));const data=await englishRelationShardPromises.get(shard.file);return {...manifest,entries:data.entries||{}}}
function englishRelationFor(data,word){return data?.entries?.[normWord(word)]||null}
function englishDeckTag(deck){return ENGLISH_EXAM_TAGS[deck?.id]||(!deck?.builtin?'general':null)}
function englishMasterLexicon(primaryDeck){const lexicon=new Map(),decks=[primaryDeck,...builtinDeckCache.values(),...state.vocab.decks],seenDecks=new Set();for(const deck of decks){if(!isEnglishRelationDeck(deck)||seenDecks.has(deck.id))continue;seenDecks.add(deck.id);const tag=englishDeckTag(deck);for(const word of deck.words||[]){const key=normWord(word.word);if(!key)continue;let entry=lexicon.get(key);if(!entry){entry={word:word.word,meaning:'',pos:'',phonetic:'',example:'',exampleZh:'',examTags:new Set()};lexicon.set(key,entry)}for(const field of ['meaning','pos','phonetic','example','exampleZh'])if(!entry[field]&&word[field])entry[field]=word[field];if(tag)entry.examTags.add(tag)}}return lexicon}
function compactEnglishPos(value){const key=String(value||'').trim().toLowerCase().replace(/\.$/,'');return ({noun:'n.',n:'n.',verb:'v.',v:'v.',adjective:'adj.',adj:'adj.',adverb:'adv.',adv:'adv.',preposition:'prep.',prep:'prep.',conjunction:'conj.',conj:'conj.',pronoun:'pron.',pron:'pron.'})[key]||String(value||'')}
function englishMeaningFor(lexicon,word){return lexicon.get(normWord(word))?.meaning||'暂无中文释义'}
function englishPosFor(lexicon,item){return compactEnglishPos(lexicon.get(normWord(item.word))?.pos||item.pos||'')}
function confusableDifferenceZh(item,rootWord,lexicon){if(item.differenceZh)return item.differenceZh;const rootMeaning=englishMeaningFor(lexicon,rootWord),relatedMeaning=englishMeaningFor(lexicon,item.word);return `${rootWord}：${rootMeaning}；${item.word}：${relatedMeaning}`}
function relationItems(items,kind,lexicon,rootWord,limit=Infinity){if(!items?.length)return'';return items.slice(0,limit).map(item=>{if(kind==='collocations')return `<li><b>${esc(item.text)}</b>${item.translation?` · ${esc(item.translation)}`:''}${item.note?`<small>${esc(item.note)}</small>`:''}</li>`;const pos=kind==='family'?englishPosFor(lexicon,item):'',meaning=englishMeaningFor(lexicon,item.word),detail=kind==='confusables'?confusableDifferenceZh(item,rootWord,lexicon):meaning;return `<li><b>${esc(item.word)}</b>${pos?` <span>${esc(pos)}</span>`:''}<small>${esc(detail)}</small></li>`}).join('')}
function englishRelationAttribution(entry,data){const sources=(entry.sources||[entry.source]).filter(Boolean),meta=data.sources||[];const links=sources.map(url=>{const item=meta.find(source=>url.startsWith(source.url));return `<a href="${esc(url)}" target="_blank" rel="noopener">${esc(item?.name||'来源')}</a>`});const licenses=[...new Set(meta.filter(source=>sources.some(url=>url.startsWith(source.url))).map(source=>source.license))];return `${links.join(' / ')}${licenses.length?` · ${esc(licenses.join(' / '))}`:''}`}
function englishRelationPanel(entry,data,rootWord,lexicon){if(!entry?.relations)return'';const groups=[['family','词族'],['synonyms','近义词'],['collocations','常用搭配'],['confusables','易混词']].filter(([key])=>entry.relations[key]?.length);if(!groups.length)return'';return `<details class="vocab-relations english-relations"><summary>关联词</summary><div class="english-relation-groups">${groups.map(([key,label])=>`<details><summary>${label} ${entry.relations[key].length}</summary><ul>${relationItems(entry.relations[key],key,lexicon,rootWord)}</ul></details>`).join('')}</div><small class="relation-source">来源：${englishRelationAttribution(entry,data)}</small></details>`}
function englishAnswerRelationHTML(entry,rootWord,lexicon){if(!entry?.relations)return'';const groups=[['family','词族',3],['synonyms','近义词',3],['confusables','易混词',1]].filter(([key])=>entry.relations[key]?.length);return groups.map(([key,label,limit])=>`<section><h3>${label}</h3><ul>${relationItems(entry.relations[key],key,lexicon,rootWord,limit)}</ul>${entry.relations[key].length>limit?`<small class="sub">另有 ${entry.relations[key].length-limit} 项，完整详情中查看</small>`:''}</section>`).join('')}
function addEnglishExamTags(deck,word,lexicon){const tags=[...(lexicon.get(normWord(word.word))?.examTags||[])];if(!tags.length)return;const fields=$('#vocabDetailBody .vocab-detail-fields');if(fields)fields.insertAdjacentHTML('beforeend',`<div><span>考试标签</span><b>${tags.map(tag=>`<span class="tag">${esc(ENGLISH_EXAM_LABELS[tag]||tag)}</span>`).join(' ')}</b></div>`)}

const baseShowVocabDetail21=showVocabDetail;
showVocabDetail=async function(id){const deck=vocabBrowserState.deck,word=wordById(deck,id);baseShowVocabDetail21(id);if(!word||!isEnglishRelationDeck(deck))return;$('#vocabDetailBody').querySelectorAll(':scope > .vocab-relations').forEach(node=>node.remove());const lexicon=englishMasterLexicon(deck);addEnglishExamTags(deck,word,lexicon);const data=await loadEnglishRelations(word.word),entry=englishRelationFor(data,word.word);if(vocabBrowserState.detail!==word||!$('#vocabDetailModal').classList.contains('show'))return;const html=englishRelationPanel(entry,data,word.word,lexicon),example=$('#vocabDetailBody .vocab-detail-example');if(html&&example)example.insertAdjacentHTML('beforebegin',html)};

const relationModeToggle=$('#vocabShowRelationsAfterAnswer');
relationModeToggle.checked=state.settings.vocabShowRelationsAfterAnswer===true;
relationModeToggle.onchange=()=>{state.settings.vocabShowRelationsAfterAnswer=relationModeToggle.checked;save()};
async function startPrimaryEnglishQuick(button){button.disabled=true;try{nav('vocab');const meta=visibleBuiltinMetas().find(item=>ENGLISH_RELATION_DECKS.has(item.id));const deck=meta?(builtinDeckCache.get(meta.id)||await installBuiltin(meta.id,false)):state.vocab.decks.find(isEnglishRelationDeck);if(deck)startVocabQuick(deck);else toast('请先在“我的”中显示 TOEIC、IELTS 或考研英语')}finally{button.disabled=false}}
$$('[data-vocab-quick-entry]').forEach(button=>button.onclick=()=>startPrimaryEnglishQuick(button));
let relationAdvanceCapture=null,activeAnswerRelation=null;
const baseAdvanceVocab21=advanceVocab;
advanceVocab=function(delay=300){if(relationAdvanceCapture){relationAdvanceCapture.delay=delay;return}baseAdvanceVocab21(delay)};
function hideAnswerRelationCard(){const card=$('#vocabRelationCard');if(card)card.hidden=true;activeAnswerRelation=null}
async function presentAnswerRelationCard(context){await new Promise(resolve=>setTimeout(resolve,Math.min(220,context.delay||0)));if(state.vocab.session!==context.session||context.session.index!==context.index||currentVocabWord()!==context.word)return;const data=await loadEnglishRelations(context.word.word),entry=englishRelationFor(data,context.word.word),lexicon=englishMasterLexicon(context.deck),groups=englishAnswerRelationHTML(entry,context.word.word,lexicon);if(!groups){baseAdvanceVocab21(context.delay||0);return}activeAnswerRelation=context;$('#vocabQuestionArea').style.display='none';$('#vocabRelationCard').hidden=false;$('#vocabRelationOutcome').className='vocab-relation-outcome '+(context.ok?'correct':'wrong');$('#vocabRelationOutcome').textContent=context.ok?'✓ 回答正确':'✗ 正确答案';$('#vocabRelationWord').textContent=context.word.word;$('#vocabRelationMeaning').textContent=context.word.meaning;$('#vocabRelationGroups').innerHTML=groups;$('#vocabUnknown').style.display='none';$('#vocabSkip').style.display='none'}
const baseAnswerVocabChoice21=answerVocabChoice;
answerVocabChoice=function(selected,button,forceUnknown=false){const deck=activeVocabDeck(),session=state.vocab.session,word=currentVocabWord(),useRelations=state.settings.vocabShowRelationsAfterAnswer===true&&isEnglishRelationDeck(deck)&&!!word,context=useRelations?{deck,session,word,index:session.index,ok:!forceUnknown&&selected===word.meaning,delay:null}:null;relationAdvanceCapture=context;try{baseAnswerVocabChoice21(selected,button,forceUnknown)}finally{relationAdvanceCapture=null}if(context&&context.delay!==null)presentAnswerRelationCard(context)};
const baseRenderVocabSession21=renderVocabSession;
renderVocabSession=function(){hideAnswerRelationCard();baseRenderVocabSession21()};
$('#vocabRelationNext').onclick=()=>{if(!activeAnswerRelation)return;hideAnswerRelationCard();baseAdvanceVocab21(0)};
$('#vocabRelationMore').onclick=()=>{if(!activeAnswerRelation)return;vocabBrowserState.deck=activeAnswerRelation.deck;showVocabDetail(activeAnswerRelation.word.id)};

const quickStage=$('#vocabQuickStage');
let quickSwipeStart=0,quickSwipePointer=null,quickSwipeLocked=false;
function resetQuickSwipe(){quickStage.classList.remove('dragging','swipe-known','swipe-unknown','quick-exit-known','quick-exit-unknown','quick-exit-fuzzy');quickStage.style.transform='';quickStage.style.opacity='';quickSwipePointer=null}
const baseRenderVocabQuick21=renderVocabQuick;
renderVocabQuick=function(){baseRenderVocabQuick21();resetQuickSwipe()};
const baseAnswerVocabQuick21=answerVocabQuick;
answerVocabQuick=function(status){if(!quickDeck||!isEnglishRelationDeck(quickDeck))return baseAnswerVocabQuick21(status);if(quickSwipeLocked)return;quickSwipeLocked=true;quickStage.classList.add('quick-exit-'+status);setTimeout(()=>{baseAnswerVocabQuick21(status);quickSwipeLocked=false;resetQuickSwipe()},180)};
quickStage.addEventListener('pointerdown',event=>{if(!quickDeck||!isEnglishRelationDeck(quickDeck)||quickSwipeLocked||event.target.closest('button'))return;quickSwipeStart=event.clientX;quickSwipePointer=event.pointerId;quickStage.setPointerCapture?.(event.pointerId);quickStage.classList.add('dragging')});
quickStage.addEventListener('pointermove',event=>{if(event.pointerId!==quickSwipePointer)return;const dx=event.clientX-quickSwipeStart;quickStage.style.transform=`translateX(${dx}px) rotate(${dx*.025}deg)`;quickStage.style.opacity=String(Math.max(.62,1-Math.abs(dx)/420));quickStage.classList.toggle('swipe-known',dx>30);quickStage.classList.toggle('swipe-unknown',dx<-30)});
quickStage.addEventListener('pointerup',event=>{if(event.pointerId!==quickSwipePointer)return;const dx=event.clientX-quickSwipeStart;quickStage.classList.remove('dragging');quickSwipePointer=null;if(dx>60)answerVocabQuick('known');else if(dx<-60)answerVocabQuick('unknown');else resetQuickSwipe()});
quickStage.addEventListener('pointercancel',()=>resetQuickSwipe());
