function refreshDashboard(){const log=state.logs[dayKey()]||{reviewed:0,correct:0};$('#todayReviewed').textContent=log.reviewed;$('#todayCorrect').textContent=log.reviewed?Math.round(log.correct/log.reviewed*100)+'%':'0%';$('#dueCount').textContent=dueCards().length;let cards=state.docs.flatMap(d=>d.cards),mastered=cards.filter(c=>c.ease>=3).length,pct=cards.length?Math.round(mastered/cards.length*100):0;$('#overallPct').textContent=pct+'%';$('#overallBar').style.width=pct+'%'}
function renderStats(){const days=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let k=dayKey(d);days.push({k,n:state.logs[k]?.reviewed||0,label:(d.getMonth()+1)+'/'+d.getDate()})}const max=Math.max(1,...days.map(x=>x.n));$('#weekChart').innerHTML=days.map((x,i)=>`<div class="bar ${i===6?'today':''}" style="height:${Math.max(8,x.n/max*100)}%"><span>${x.label}</span></div>`).join('');$('#statDocs').textContent=state.docs.length;$('#statSentences').textContent=state.docs.reduce((a,d)=>a+d.sentences.length,0);$('#statMastered').textContent=state.docs.reduce((a,d)=>a+d.cards.filter(c=>c.ease>=3).length,0);const weak={};state.docs.forEach(d=>Object.entries(d.weak||{}).forEach(([k,v])=>weak[k]=(weak[k]||0)+v));const sorted=Object.entries(weak).sort((a,b)=>b[1]-a[1]).slice(0,12);$('#weakWords').innerHTML=sorted.length?'<b style="color:var(--text)">常卡关键词：</b><br>'+sorted.map(([w,n])=>`<span class="tag" style="margin:6px 5px 0 0">${esc(w)} ×${n}</span>`).join(''):'训练后，这里会显示你经常卡住的关键词。'}
function showLoading(title,text){$('#loadingTitle').textContent=title;$('#loadingText').textContent=text;$('#loadingModal').classList.add('show')}function hideLoading(){$('#loadingModal').classList.remove('show')}
async function readFile(file){const ext=file.name.split('.').pop().toLowerCase();if(ext==='txt'||ext==='md')return await file.text();if(ext==='docx'){showLoading('正在解析 Word','DOCX 解析需要联网加载组件；解析后资料会保存在本地。');if(!window.mammoth){await loadScript('https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js')}const buf=await file.arrayBuffer();const r=await window.mammoth.extractRawText({arrayBuffer:buf});return r.value}if(ext==='pdf'){showLoading('正在解析 PDF','PDF 解析需要联网加载组件；解析后资料会保存在本地。');const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let out='';for(let p=1;p<=Math.min(pdf.numPages,80);p++){const page=await pdf.getPage(p),c=await page.getTextContent();out+=c.items.map(x=>x.str).join(' ')+'\n\n'}return out}throw new Error('暂不支持这个文件格式')}
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=()=>rej(new Error('解析组件加载失败，请检查网络'));document.head.appendChild(s)})}
async function handleFile(f){try{const t=await readFile(f);$('#pasteText').value=t;$('#materialTitle').value=f.name.replace(/\.[^.]+$/,'');toast('文件已读入，可以生成背诵材料')}catch(e){alert(e.message)}finally{hideLoading()}}
$('#pickFile').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>e.target.files[0]&&handleFile(e.target.files[0]);const dz=$('#dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>e.dataTransfer.files[0]&&handleFile(e.dataTransfer.files[0]));
$('#createMaterial').onclick=()=>{try{let t=$('#pasteText').value.trim();if(!t)return toast('先粘贴或导入资料');addDoc($('#materialTitle').value.trim(),t);$('#pasteText').value='';$('#materialTitle').value=''}catch(e){alert(e.message)}};
const demo=`When I was a college student, I worked on an important fashion project with several classmates. At first, we had different ideas and it was difficult to communicate with each other. Instead of arguing, I suggested that we divide the work according to everyone's strengths. I was responsible for design and presentation, while my teammates focused on research and technical details. We also held a short meeting every evening to check our progress. As a result, we finished the project on time and received positive feedback from our teacher. This experience taught me that good communication and teamwork can make a difficult task much easier.`;
$('#loadDemo').onclick=()=>addDoc('示例 · Teamwork Story',demo);$('#newMaterial').onclick=()=>nav('library');
$('#hideMap').onclick=()=>{$('#storyMap').style.display=$('#storyMap').style.display==='none'?'flex':'none'};
$('#speechRate').value=state.settings.speechRate||.9;$('#speechLang').value=state.settings.speechLang||'en-US';$('#apiEndpoint').value=state.settings.apiEndpoint||'';$('#apiModel').value=state.settings.apiModel||'';$('#apiKey').value=state.settings.apiKey||'';
$('#saveSettings').onclick=()=>{state.settings={speechRate:Number($('#speechRate').value),speechLang:$('#speechLang').value,apiEndpoint:$('#apiEndpoint').value.trim(),apiModel:$('#apiModel').value.trim(),apiKey:$('#apiKey').value.trim(),vocabBatchSize:state.settings.vocabBatchSize||'100'};save();toast('设置已保存')};$('#resetAll').onclick=()=>{if(confirm('真的清空全部资料、进度和设置？此操作无法恢复。')){localStorage.removeItem(KEY);location.reload()}};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='串题记忆室_学习数据_'+dayKey()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#importDataBtn').onclick=()=>$('#importDataFile').click();$('#importDataFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const j=JSON.parse(await f.text());if(!j||!Array.isArray(j.docs)||typeof j.settings!=='object')throw new Error('文件不是有效的学习数据');if(!confirm('导入会覆盖当前浏览器里的学习资料和进度，继续吗？'))return;state={...structuredClone(defaultState),...j};state.vocab=state.vocab||{decks:[],activeDeck:null,session:null,builtinInstalled:{},progress:{}};state.vocab.decks=state.vocab.decks||[];state.vocab.builtinInstalled=state.vocab.builtinInstalled||{};state.vocab.progress=state.vocab.progress||{};state.vocabLogs=state.vocabLogs||{};save();location.reload()}catch(err){alert('导入失败：'+err.message)}finally{e.target.value=''}};
if('serviceWorker' in navigator && location.protocol.startsWith('http')){navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
let installPrompt=null;const isIOS=/iphone|ipad|ipod/i.test(navigator.userAgent);const isStandalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(isIOS&&!isStandalone)$('#installApp').style.display='inline-block';window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installApp').style.display='inline-block'});$('#installApp').onclick=async()=>{if(isIOS&&!installPrompt){alert('iPhone 安装方法：\n1. 请用 Safari 打开本网页\n2. 点击底部“分享”按钮\n3. 选择“添加到主屏幕”\n4. 以后就能像 App 一样打开');return}if(!installPrompt)return toast('请使用浏览器菜单里的“添加到主屏幕 / 安装应用”');installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installApp').style.display='none'};window.addEventListener('appinstalled',()=>toast('已安装到设备 ✓'));
renderLibrary();renderStudy();refreshDashboard();renderExam();renderVocabHome();preloadBuiltinDecks();
