/* IELTS full mock exam. Own session and shell; specialized practice remains in app-23. */
let ieltsFullTimer=null,ieltsFullSpeechToken=0,ieltsFullAudioVolume=1,ieltsFullAudioActive=null;
const ieltsFullSections=['listening','reading','writing'];
function ieltsFullSession(){return state.examEngine.ieltsFullSession||null}
function saveIeltsFull(){save({immediate:true,refresh:false})}
function startIeltsFullMock(mockId){const mock=customMock(mockId);if(!customMockReady(mock))return toast('此模拟卷的资料尚未齐全');const old=ieltsFullSession();
  if(old&&old.mockId===mockId&&old.section!=='finished'){sessionStorage.setItem('ieltsFullActive',mockId);return nav('ielts-full-exam')}
  if(old&&old.section!=='finished'&&!confirm('开始另一套将覆盖未完成的机考。确定继续吗？'))return;
  const now=Date.now();state.examEngine.ieltsFullSession={mockId,section:'listening',startedAt:now,deadline:now+30*60000,indices:{listening:0,reading:0},answers:{listening:{},reading:{}},flags:{listening:{},reading:{}},highlights:{},notes:{},drafts:{writing1:'',writing2:''},writingTab:'writing1',results:{},completedAt:null};saveIeltsFull();sessionStorage.setItem('ieltsFullActive',mockId);nav('ielts-full-exam')}
function ieltsFullQuestions(session){const mock=customMock(session.mockId),item=session.section==='listening'?customListening(mock.listeningId):customReading(mock.readingId);return buildCustomExamQuestions(session.section,item)}
function ieltsFullScore(session,section){const mock=customMock(session.mockId),item=section==='listening'?customListening(mock.listeningId):customReading(mock.readingId);return buildCustomExamQuestions(section,item).reduce((n,q)=>n+Number(isObjectiveAnswerCorrect(q,session.answers[section][q.id]||'')),0)}
function ieltsFullFinishSection(automatic=false){const session=ieltsFullSession();if(!session||!ieltsFullSections.includes(session.section))return;
  if(!automatic){ieltsFullDialog('提交本部分后不能返回修改。确定提交吗？',()=>ieltsFullFinishSection(true));return}
  const old=session.section;if(old==='listening'||old==='reading')session.results[old]=ieltsFullScore(session,old);
  else session.results.writingSaved=true;
  const next={listening:'reading',reading:'writing',writing:'finished'}[old];session.section=next;session.deadline=next==='finished'?null:Date.now()+(next==='writing'?60:next==='reading'?60:30)*60000;
  if(next==='finished'){session.completedAt=Date.now();sessionStorage.removeItem('ieltsFullActive')}saveIeltsFull();const box=$('#ieltsFullWorkspace');if(box)box.dataset.section='';renderIeltsFullExam()}
function ieltsFullClock(){clearInterval(ieltsFullTimer);const update=()=>{const session=ieltsFullSession();if(!session||session.section==='finished')return clearInterval(ieltsFullTimer);const remain=Math.max(0,session.deadline-Date.now()),clock=$('#ieltsFullClock'),header=$('#ieltsFullHeader');if(clock){clock.textContent=`${String(Math.floor(remain/60000)).padStart(2,'0')}:${String(Math.floor(remain%60000/1000)).padStart(2,'0')}`;clock.classList.toggle('warning',remain<=60000)}header?.classList.toggle('warning',remain<=60000);if(remain===0){clearInterval(ieltsFullTimer);ieltsFullFinishSection(true)}};update();ieltsFullTimer=setInterval(update,1000)}
function ieltsFullStopAudio(){ieltsFullSpeechToken++;ieltsFullAudioActive=null;if('speechSynthesis'in window)speechSynthesis.cancel();$('#ieltsFullAudio audio')?.pause()}
function ieltsFullAudio(item,part){const area=$('#ieltsFullAudio'),key=item.id+':'+part.number,session=ieltsFullSession();if(!area||area.dataset.part===key||ieltsFullAudioActive)return;ieltsFullStopAudio();area.dataset.part=key;session.audioProgress||={};const progress=session.audioProgress[key]||{started:false,complete:false,position:0};session.audioProgress[key]=progress;
  area.innerHTML=`<div class="ielts-full-audio-label">Part ${part.number} · ${part.audioUrl?'预录 TTS':'设备 TTS'}</div><button type="button" id="ieltsFullPlay" ${progress.complete?'disabled':''}>${progress.complete?'已播放':progress.started?'▶ 继续播放':'▶ 开始播放'}</button><label>音量 <input id="ieltsFullVolume" type="range" min="0" max="100" value="${Math.round(ieltsFullAudioVolume*100)}"></label>${part.audioUrl?`<audio preload="metadata" src="${esc(part.audioUrl)}"></audio>`:''}`;
  $('#ieltsFullVolume').oninput=e=>{ieltsFullAudioVolume=Number(e.target.value)/100;const audio=area.querySelector('audio');if(audio)audio.volume=ieltsFullAudioVolume};
  $('#ieltsFullPlay').onclick=()=>{if(ieltsFullAudioActive||progress.complete)return;if(!part.audioUrl&&!('speechSynthesis'in window))return toast('设备不支持语音合成');progress.started=true;saveIeltsFull();ieltsFullAudioActive=key;$('#ieltsFullPlay').disabled=true;$('#ieltsFullPlay').textContent='正在播放';const done=()=>{ieltsFullAudioActive=null;progress.complete=true;saveIeltsFull();$('#ieltsFullPlay').textContent='已播放'};
    if(part.audioUrl){const audio=area.querySelector('audio');audio.volume=ieltsFullAudioVolume;audio.currentTime=progress.position||0;audio.ontimeupdate=()=>{if(Math.abs(audio.currentTime-progress.position)>3){progress.position=audio.currentTime;saveIeltsFull()}};audio.onended=done;audio.play().catch(()=>{ieltsFullAudioActive=null;$('#ieltsFullPlay').disabled=false;$('#ieltsFullPlay').textContent='▶ 继续播放'});return}
    const token=ieltsFullSpeechToken;let pos=progress.position||0;const play=()=>{if(token!==ieltsFullSpeechToken)return;if(pos>=part.lines.length){done();return}const line=part.lines[pos++],speech=new SpeechSynthesisUtterance(line.text);speech.lang='en-GB';speech.volume=ieltsFullAudioVolume;speech.rate=.92;speech.onend=()=>{progress.position=pos;saveIeltsFull();if(token===ieltsFullSpeechToken)setTimeout(play,Math.min(30000,line.pauseAfterMs||0))};speechSynthesis.speak(speech)};play()}}
function ieltsFullRenderResult(session,mock,box){clearInterval(ieltsFullTimer);box.innerHTML=`<article class="card ielts-full-result"><span class="practice-label">${esc(mock.label)} · L/R/W 结果</span><h2>笔试已完成</h2><p>Listening ${session.results.listening} / 40</p><p>Reading ${session.results.reading} / 40</p><p>Writing Saved</p><div class="row"><button class="btn" id="ieltsFullCopy">复制题目与我的作文</button><button class="btn primary" id="ieltsFullSpeaking">开始 Speaking Test · ${esc(mock.speakingSetId)}</button><button class="btn" id="ieltsFullBack">返回题库</button></div></article>`;
  $('#ieltsFullCopy').onclick=async()=>{const t1=customOpen.writingTask1.find(t=>t.id===mock.writingTask1Id),t2=customOpen.writingTask2.find(t=>t.id===mock.writingTask2Id);const text=`Task 1\nQuestion: ${t1.prompt}\nMy Answer: ${session.drafts.writing1}\n\nTask 2\nQuestion: ${t2.prompt}\nMy Answer: ${session.drafts.writing2}`;try{await navigator.clipboard.writeText(text);toast('题目与作文已复制')}catch{toast('复制失败，请检查浏览器剪贴板权限')}};
  $('#ieltsFullSpeaking').onclick=()=>openCustomWork('speaking',mock.speakingSetId,mock.id);$('#ieltsFullBack').onclick=()=>nav('ielts-custom')}
// The exam shell reimplements interaction patterns from aknahin/ielts-on-computer (MIT, © 2026 Asrafuzzaman Khan Nahin).
function ieltsFullDialog(message,action){const layer=$('#ieltsFullModal');layer.hidden=false;layer.innerHTML=`<div class="ielts-full-dialog" role="dialog" aria-modal="true" aria-label="确认操作"><h3>请确认</h3><p>${esc(message)}</p><div class="ielts-full-actions"><button type="button" id="ieltsFullCancel">继续考试</button><button type="button" id="ieltsFullConfirm">确认</button></div></div>`;$('#ieltsFullCancel').onclick=()=>layer.hidden=true;$('#ieltsFullConfirm').onclick=()=>{layer.hidden=true;action()};$('#ieltsFullCancel').focus()}
function ieltsFullPreferences(session){session.examPreferences||={contrast:'standard',size:'regular',ratio:50};if(session.examPreferences.contrast==='warm')session.examPreferences.contrast='yellow';return session.examPreferences}
function ieltsFullOptions(session){const menu=$('#ieltsFullOptionsMenu'),prefs=ieltsFullPreferences(session);menu.hidden=!menu.hidden;if(menu.hidden)return;const choices=(name,current,items)=>items.map(([value,label])=>`<button type="button" class="ielts-full-menu-item ${current===value?'selected':''}" data-exam-preference="${name}:${value}"><span>${label}</span>${current===value?'<b aria-hidden="true">✓</b>':''}</button>`).join('');menu.innerHTML=`<div class="ielts-full-menu-title"><strong>Options</strong><button type="button" id="ieltsFullOptionsClose" aria-label="关闭选项">×</button></div><p class="ielts-full-menu-label">Contrast</p>${choices('contrast',prefs.contrast,[['standard','Black on white'],['dark','White on black'],['yellow','Yellow on black']])}<p class="ielts-full-menu-label">Text size</p>${choices('size',prefs.size,[['regular','Regular'],['large','Large'],['xlarge','Extra large']])}<div class="ielts-full-menu-rule"></div><button type="button" class="ielts-full-menu-item" id="ieltsFullInstructionsButton"><span>Test instructions</span><b aria-hidden="true">›</b></button><button type="button" class="ielts-full-menu-item submit" id="ieltsFullOptionsSubmit"><span>Submit section</span></button><small>练习功能：真实考试通常由监考流程结束本部分。</small>`;
  $('#ieltsFullOptionsClose').onclick=()=>{menu.hidden=true;$('#ieltsFullOptionsButton').setAttribute('aria-expanded','false')};menu.querySelectorAll('[data-exam-preference]').forEach(button=>button.onclick=()=>{const [name,value]=button.dataset.examPreference.split(':');prefs[name]=value;ieltsFullApplyPreferences(session);saveIeltsFull();menu.hidden=true;ieltsFullOptions(session)});$('#ieltsFullInstructionsButton').onclick=()=>{menu.hidden=true;ieltsFullDialog('计时不会暂停；答案会自动保存。Reading 中拖选文字可 Highlight 或添加 Note，点击已有标注可删除或重新打开笔记。',()=>{})};$('#ieltsFullOptionsSubmit').onclick=()=>{menu.hidden=true;ieltsFullFinishSection()}}
function ieltsFullApplyPreferences(session){const box=$('#ieltsFullWorkspace'),prefs=ieltsFullPreferences(session);box.dataset.contrast=prefs.contrast;box.dataset.size=prefs.size;box.style.setProperty('--exam-split',prefs.ratio+'%')}
function ieltsFullSplit(session){const divider=$('#ieltsFullDivider'),panes=$('#ieltsFullPanes');if(!divider||!panes||session.section==='listening')return;const prefs=ieltsFullPreferences(session);const set=value=>{prefs.ratio=Math.max(20,Math.min(80,Math.round(value)));ieltsFullApplyPreferences(session);saveIeltsFull()};const finish=()=>{divider.onpointermove=null;document.body.style.userSelect='';document.body.style.cursor=''};divider.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();set(prefs.ratio+(e.key==='ArrowLeft'?-2:2))}};divider.onpointerdown=e=>{e.preventDefault();document.body.style.userSelect='none';document.body.style.cursor='col-resize';divider.setPointerCapture?.(e.pointerId);divider.onpointermove=event=>{const rect=panes.getBoundingClientRect();set((event.clientX-rect.left)*100/rect.width)};divider.onpointerup=finish;divider.onpointercancel=finish}}
function ieltsFullAnnotationRanges(value,notes=false){if(Array.isArray(value))return value;if(!value||typeof value!=='object')return[];const ids=Object.keys(value).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(notes)return ids.map(id=>({id:`legacy-note-${id}`,start:id,end:id,text:String(value[id]||'')}));const ranges=[];for(const id of ids){const last=ranges.at(-1);if(last&&id===last.end+1)last.end=id;else ranges.push({id:`legacy-highlight-${id}`,start:id,end:id})}return ranges}
function ieltsFullPartAnnotations(session,key){session.highlights||={};session.notes||={};session.highlights[key]=ieltsFullAnnotationRanges(session.highlights[key]);session.notes[key]=ieltsFullAnnotationRanges(session.notes[key],true);return{highlights:session.highlights[key],notes:session.notes[key]}}
function ieltsFullCoverage(ranges){const covered=new Set;for(const range of ranges)for(let i=range.start;i<=range.end;i++)covered.add(i);return covered}
function ieltsFullPassageHTML(text,highlights=[],notes=[]){const marked=ieltsFullCoverage(highlights),noted=ieltsFullCoverage(notes),tokens=String(text||'').split(/(\s+)/);let index=0,lastWord=-1;const nextWordAt=from=>{for(let i=from;i<tokens.length;i++)if(tokens[i]&&!/^\s+$/.test(tokens[i]))return lastWord+1;return-1};return tokens.map((chunk,position)=>{if(!chunk)return'';if(/^\s+$/.test(chunk)){const next=nextWordAt(position+1),classes=[marked.has(lastWord)&&marked.has(next)?'ielts-full-mark':'',noted.has(lastWord)&&noted.has(next)?'ielts-full-note-mark':''].filter(Boolean).join(' ');return `<span class="${classes}">${esc(chunk).replaceAll('\n','<br>')}</span>`}const id=index++;lastWord=id;const classes=[marked.has(id)?'ielts-full-mark':'',noted.has(id)?'ielts-full-note-mark':''].filter(Boolean).join(' ');return `<span data-exam-word="${id}" class="${classes}">${esc(chunk)}</span>`}).join('')}
function ieltsFullAddHighlight(existing,start,end){let lo=start,hi=end;const kept=[];for(const item of existing){if(item.start<=end+1&&start<=item.end+1){lo=Math.min(lo,item.start);hi=Math.max(hi,item.end)}else kept.push(item)}kept.push({id:`hl-${lo}-${hi}-${Date.now()}`,start:lo,end:hi});return kept.sort((a,b)=>a.start-b.start)}
function ieltsFullSelection(source){const selected=window.getSelection?.();if(!selected||selected.isCollapsed||!selected.rangeCount)return null;const range=selected.getRangeAt(0);if(!source.contains(range.commonAncestorContainer))return null;const words=[...source.querySelectorAll('[data-exam-word]')].filter(span=>range.intersectsNode(span));if(!words.length)return null;const ids=words.map(span=>Number(span.dataset.examWord)).filter(Number.isFinite),rect=range.getBoundingClientRect();return{start:Math.min(...ids),end:Math.max(...ids),x:rect.left+rect.width/2,y:Math.max(8,rect.top-8)}}
function ieltsFullToolbar(toolbar,x,y,items){toolbar.hidden=false;toolbar.style.left=x+'px';toolbar.style.top=y+'px';toolbar.innerHTML=items.map(item=>`<button type="button" data-exam-tool="${item.id}">${item.label}</button>`).join('');for(const item of items)toolbar.querySelector(`[data-exam-tool="${item.id}"]`).onclick=event=>{event.preventDefault();item.action()}}
function ieltsFullUpdateNotesButton(session){const count=Object.values(session.notes||{}).reduce((n,value)=>n+ieltsFullAnnotationRanges(value,true).length,0),button=$('#ieltsFullNotesToggle'),label=$('#ieltsFullNotesCount');if(button)button.hidden=session.section!=='reading'||count===0;if(label)label.textContent=count?`(${count})`:''}
function ieltsFullRefreshPassage(session,part){const key=String(part.number),source=$('#ieltsFullSource'),passage=source?.dataset.passage||'',annotations=ieltsFullPartAnnotations(session,key),body=source?.querySelector('.exam-source-content');if(body)body.innerHTML=ieltsFullPassageHTML(passage,annotations.highlights,annotations.notes);ieltsFullUpdateNotesButton(session);ieltsFullReadingTools(session,part)}
function ieltsFullReadingTools(session,part){const key=String(part.number),source=$('#ieltsFullSource'),toolbar=$('#ieltsFullSelectionTools'),annotations=ieltsFullPartAnnotations(session,key);if(!source||!toolbar)return;
  const close=()=>{toolbar.hidden=true;window.getSelection?.()?.removeAllRanges()};source.onmouseup=()=>{const picked=ieltsFullSelection(source);if(!picked)return;ieltsFullToolbar(toolbar,picked.x,picked.y,[{id:'highlight',label:'Highlight',action:()=>{session.highlights[key]=ieltsFullAddHighlight(annotations.highlights,picked.start,picked.end);saveIeltsFull();close();ieltsFullRefreshPassage(session,part)}},{id:'note',label:'Note',action:()=>{const note={id:`note-${picked.start}-${picked.end}-${Date.now()}`,start:picked.start,end:picked.end,text:''};annotations.notes.push(note);saveIeltsFull();close();ieltsFullRefreshPassage(session,part);ieltsFullShowNotes(session,part,note.id)}}])};source.onclick=e=>{if(!window.getSelection?.()?.isCollapsed)return;const span=e.target.closest?.('[data-exam-word]');if(!span)return;const index=Number(span.dataset.examWord),highlight=annotations.highlights.find(item=>index>=item.start&&index<=item.end),notes=annotations.notes.filter(item=>index>=item.start&&index<=item.end);if(!highlight&&!notes.length)return;const rect=span.getBoundingClientRect(),items=[];if(highlight)items.push({id:'delete-highlight',label:'Delete Highlight',action:()=>{session.highlights[key]=annotations.highlights.filter(item=>item.id!==highlight.id);saveIeltsFull();close();ieltsFullRefreshPassage(session,part)}});notes.forEach((note,i)=>items.push({id:`open-note-${i}`,label:notes.length>1?`Open Note ${i+1}`:'Open Note',action:()=>{close();ieltsFullShowNotes(session,part,note.id)}}));ieltsFullToolbar(toolbar,rect.left+rect.width/2,Math.max(8,rect.top-8),items)};$('#ieltsFullNotesToggle').onclick=()=>ieltsFullShowNotes(session,part,annotations.notes[0]?.id)}
function ieltsFullShowNotes(session,part,focusId){const key=String(part.number),panel=$('#ieltsFullNotes'),notes=ieltsFullPartAnnotations(session,key).notes;if(!notes.length){panel.hidden=true;return}let active=notes.find(note=>note.id===focusId)||notes[0];panel.hidden=false;const render=()=>{panel.innerHTML=`<div class="ielts-full-notes-title"><strong>Notes</strong><button type="button" id="ieltsFullNotesClose" aria-label="隐藏笔记">×</button></div>${notes.length>1?`<div class="ielts-full-note-tabs">${notes.map((note,i)=>`<button type="button" class="${note.id===active.id?'active':''}" data-exam-note-id="${note.id}">${i+1}</button>`).join('')}</div>`:''}<div class="ielts-full-note-anchor">Passage ${key} · words ${active.start+1}–${active.end+1}</div><textarea id="ieltsFullNoteText" placeholder="Write your notes here. They save automatically.">${esc(active.text)}</textarea><div class="ielts-full-note-delete"><button type="button" id="ieltsFullNoteDelete">Delete</button></div>`;$('#ieltsFullNotesClose').onclick=()=>panel.hidden=true;panel.querySelectorAll('[data-exam-note-id]').forEach(button=>button.onclick=()=>{active=notes.find(note=>note.id===button.dataset.examNoteId)||active;render()});const text=$('#ieltsFullNoteText');text.oninput=e=>{active.text=e.target.value;saveIeltsFull()};text.focus();$('#ieltsFullNoteDelete').onclick=e=>{if(e.target.dataset.confirm!=='1'){e.target.dataset.confirm='1';e.target.textContent='Confirm deleting';return}session.notes[key]=notes.filter(note=>note.id!==active.id);saveIeltsFull();ieltsFullRefreshPassage(session,part);const remaining=session.notes[key];if(!remaining.length)panel.hidden=true;else{active=remaining[0];render()}}};render()}
function ieltsFullControl(item,part,q,answer,active=false){const number=Number(q.id.split(':').pop()),raw=part.questions?.find(x=>x.number===number),group=part.groups?.find(g=>g.questions.some(x=>x.number===number)),type=raw?.type||group?.type,options=raw?.options?Object.entries(raw.options).map(([key,label])=>({key,label})):group?.options?.map(x=>({key:x.key,label:x.text}))||[],id=active?'ieltsFullAnswer':`ieltsFullAnswer-${number}`,name=`ielts-full-answer-${number}`,data=`data-exam-answer="${esc(q.id)}"`;
  if(type==='true_false_not_given'||type==='yes_no_not_given'){const keys=type==='true_false_not_given'?['TRUE','FALSE','NOT GIVEN']:['YES','NO','NOT GIVEN'];return `<div class="ielts-full-choices">${keys.map(key=>`<label><input ${data} type="radio" name="${name}" value="${key}" ${String(answer).toUpperCase()===key?'checked':''}>${key}</label>`).join('')}</div>`}
  if(type==='multiple_choice'&&options.length)return `<div class="ielts-full-choices">${options.map(({key,label})=>`<label><input ${data} type="radio" name="${name}" value="${esc(key)}" ${answer===key?'checked':''}><b>${esc(key)}</b> ${esc(label)}</label>`).join('')}</div>`;
  if(type?.startsWith('matching')&&options.length)return `<select ${data} id="${id}" class="field" aria-label="Question ${number} answer"><option value="">Choose an answer</option>${options.map(({key,label})=>`<option value="${esc(key)}" ${answer===key?'selected':''}>${esc(key)} · ${esc(label)}</option>`).join('')}</select>`;
  return `<input ${data} id="${id}" class="field" type="text" autocomplete="off" aria-label="Question ${number} answer" placeholder="Type your answer" value="${esc(answer)}">`}
async function renderIeltsFullExam(){const box=$('#ieltsFullWorkspace');if(!box)return;const session=ieltsFullSession();if(!session){nav('ielts-custom');return}try{await loadIeltsCustom()}catch(error){box.textContent='题库加载失败：'+error.message;return}const mock=customMock(session.mockId);if(!customMockReady(mock)){box.textContent='此模拟卷的题目不完整';return}if(session.section==='finished')return ieltsFullRenderResult(session,mock,box);if(session.deadline<=Date.now()){ieltsFullFinishSection(true);return}
  if(box.dataset.section!==session.section){ieltsFullStopAudio();box.dataset.section=session.section;box.innerHTML=`<header class="ielts-full-top" id="ieltsFullHeader"><div class="ielts-full-brand"><strong>CUSTOM TRAINING MOCK</strong><span>${esc(mock.label)} · <span id="ieltsFullSection"></span></span></div><div class="ielts-full-head-actions"><div class="ielts-full-clock-wrap" role="timer" aria-live="off"><span>Time remaining</span><strong class="exam-clock" id="ieltsFullClock">00:00</strong></div><button type="button" class="ielts-full-notes-toggle" id="ieltsFullNotesToggle" hidden aria-label="显示笔记"><span aria-hidden="true">▤</span> Notes <b id="ieltsFullNotesCount"></b></button><button type="button" id="ieltsFullOptionsButton" aria-expanded="false" aria-haspopup="menu"><span aria-hidden="true">☰</span> Options</button><button type="button" id="ieltsFullExit">Exit</button></div><div class="ielts-full-options" id="ieltsFullOptionsMenu" role="menu" hidden></div></header><div class="ielts-full-instruction"><span id="ieltsFullProgress"></span><span>答题会自动保存，计时不会暂停。</span><button type="button" id="ieltsFullSubmit">Submit section</button></div><main class="ielts-full-panes" id="ieltsFullPanes"><article class="ielts-full-source" id="ieltsFullSourcePane"><div id="ieltsFullSource"></div><div id="ieltsFullAudio"></div></article><div class="ielts-full-divider" id="ieltsFullDivider" role="separator" aria-orientation="vertical" aria-label="调整文章与题目区域宽度" tabindex="0"><span></span></div><article class="ielts-full-question"><div id="ieltsFullQuestion"></div><div class="ielts-full-question-actions"><button type="button" id="ieltsFullPrevious">← Previous</button><button type="button" id="ieltsFullFlag">⚑ Review</button><button type="button" id="ieltsFullNext">Next →</button></div></article></main><div class="ielts-full-selection" id="ieltsFullSelectionTools" hidden></div><aside class="ielts-full-notes" id="ieltsFullNotes" hidden></aside><nav class="ielts-full-bottom" aria-label="Question navigation"><span id="ieltsFullPartLabel"></span><div id="ieltsFullNavigator" class="exam-number-nav"></div></nav><div id="ieltsFullModal" class="ielts-full-modal" hidden></div>`;
    $('#ieltsFullExit').onclick=()=>ieltsFullDialog('退出考试？答卷和剩余时间会保留，计时不会暂停。',()=>{ieltsFullStopAudio();clearInterval(ieltsFullTimer);saveIeltsFull();sessionStorage.removeItem('ieltsFullActive');nav('ielts-custom')});$('#ieltsFullSubmit').onclick=()=>ieltsFullFinishSection();$('#ieltsFullOptionsButton').onclick=()=>{ieltsFullOptions(session);$('#ieltsFullOptionsButton').setAttribute('aria-expanded',String(!$('#ieltsFullOptionsMenu').hidden))};ieltsFullSplit(session)}
  const section=session.section;$('#ieltsFullSection').textContent={listening:'Listening',reading:'Academic Reading',writing:'Writing'}[section];$('#ieltsFullProgress').textContent={listening:'Listening · 30 minutes · audio plays once',reading:'Academic Reading · 60 minutes · select text to Highlight or Note',writing:'Writing · Task 1 and Task 2 share 60 minutes'}[section];const noteCount=Object.values(session.notes||{}).reduce((n,value)=>n+ieltsFullAnnotationRanges(value,true).length,0);$('#ieltsFullNotesToggle').hidden=section!=='reading'||noteCount===0;$('#ieltsFullNotesCount').textContent=noteCount?`(${noteCount})`:'';ieltsFullApplyPreferences(session);
  if(section==='writing')renderIeltsFullWriting(session,mock);else renderIeltsFullQuestions(session,mock);ieltsFullClock()}
function renderIeltsFullQuestions(session,mock){const section=session.section,questions=ieltsFullQuestions(session),index=session.indices[section]||0,q=questions[index];if(!q)return;const answers=session.answers[section],flags=session.flags[section],item=section==='listening'?customListening(mock.listeningId):customReading(mock.readingId),partFor=question=>{const number=Number(question.id.split(':').pop());return item.parts.find(candidate=>section==='listening'?candidate.questions?.some(x=>x.number===number):candidate.groups?.some(group=>group.questions.some(x=>x.number===number)))||item.parts[0]},part=partFor(q),partQuestions=questions.filter(question=>partFor(question).number===part.number);
  let previousPart=0;$('#ieltsFullNavigator').innerHTML=questions.map((question,i)=>{const partNumber=partFor(question).number,first=partNumber!==previousPart,activePart=partNumber===part.number;previousPart=partNumber;return `${first?`<button type="button" class="ielts-full-part-chip ${activePart?'active':''}" data-ielts-full-part="${partNumber}">${section==='reading'?'Passage':'Part'} ${partNumber}</button>`:''}<button type="button" aria-label="Question ${i+1}${answers[question.id]?'，answered':'，not answered'}${flags[question.id]?'，flagged':''}" class="${i===index?'active':''} ${answers[question.id]?'answered':''} ${flags[question.id]?'review':''} ${activePart?'':'inactive-part'}" data-ielts-full-index="${i}">${i+1}</button>`}).join('');const goTo=next=>{session.indices[section]=Math.max(0,Math.min(39,next));saveIeltsFull();renderIeltsFullQuestions(session,mock);window.requestAnimationFrame?.(()=>document.getElementById(`ielts-q-${next+1}`)?.scrollIntoView({block:'center'}))};$$('[data-ielts-full-index]').forEach(button=>button.onclick=()=>goTo(Number(button.dataset.ieltsFullIndex)));$$('[data-ielts-full-part]').forEach(button=>button.onclick=()=>{const target=questions.findIndex(question=>partFor(question).number===Number(button.dataset.ieltsFullPart));if(target>=0)goTo(target)});
  $('#ieltsFullPartLabel').textContent=`${section==='listening'?'Listening · Part':'Reading · Passage'} ${part.number}`;const source=$('#ieltsFullSource'),sourceKey=item.id+':'+part.number;if(section==='reading'){const annotations=ieltsFullPartAnnotations(session,String(part.number)),passage=q.content?.passage||'';if(source.dataset.part!==sourceKey){source.dataset.part=sourceKey;source.dataset.passage=passage;source.innerHTML=`<h2>${esc(part.title)}</h2><div class="exam-source-content">${ieltsFullPassageHTML(passage,annotations.highlights,annotations.notes)}</div>`;$('#ieltsFullSourcePane').scrollTop=0}$('#ieltsFullAudio').innerHTML='';ieltsFullReadingTools(session,part);ieltsFullUpdateNotesButton(session)}else{source.dataset.part=sourceKey;source.innerHTML=`<div><h2>Listening · Part ${part.number}</h2><p>Listen and answer Questions ${Number(partQuestions[0].id.split(':').pop())}–${Number(partQuestions.at(-1).id.split(':').pop())}. The transcript and answers are hidden during the test.</p></div>`;ieltsFullAudio(item,part)}
  const renderedLayouts=new Set;$('#ieltsFullQuestion').innerHTML=`<div class="ielts-full-question-head"><span>${section==='reading'?'Passage':'Part'} ${part.number}</span><strong>Question ${index+1} / 40</strong></div><div class="ielts-full-part-questions">${partQuestions.map(question=>{const number=Number(question.id.split(':').pop()),original=part.questions?.find(x=>x.number===number)||part.groups?.flatMap(group=>group.questions).find(x=>x.number===number),group=part.groups?.find(candidate=>candidate.questions.some(x=>x.number===number)),stem=original?.options||group?.options?[original.instruction||group?.instruction,original.prompt].filter(Boolean).join('\n'):question.stem,layoutKey=JSON.stringify(question.content?.layout||null),layout=section==='reading'&&question.content?.layout&&!renderedLayouts.has(layoutKey)?customReadingLayout(question.content.layout):'';if(layout)renderedLayouts.add(layoutKey);return `<section class="ielts-full-question-card ${question.id===q.id?'current':''}" id="ielts-q-${number}"><div class="ielts-full-question-number"><strong>${number}</strong><button type="button" class="${flags[question.id]?'active':''}" data-exam-flag="${esc(question.id)}" aria-label="${flags[question.id]?'Remove flag from':'Flag'} question ${number}">⚑</button></div><div class="ielts-full-question-body">${layout}<div class="ielts-full-prompt">${esc(stem).replaceAll('\n','<br>')}</div>${ieltsFullControl(item,part,question,String(answers[question.id]||''),question.id===q.id)}<small data-exam-save="${esc(question.id)}">Saved automatically</small></div></section>`}).join('')}</div>`;
  const update=(questionId,value)=>{answers[questionId]=value;saveIeltsFull();const questionIndex=questions.findIndex(question=>question.id===questionId);$(`[data-ielts-full-index="${questionIndex}"]`)?.classList.toggle('answered',Boolean(String(value).trim()));const saved=$(`[data-exam-save="${questionId}"]`);if(saved)saved.textContent='Saved automatically'};$('#ieltsFullQuestion').querySelectorAll('[data-exam-answer]').forEach(field=>{const event=field.matches?.('input[type=radio]')?'onchange':'oninput';field[event]=e=>update(field.dataset.examAnswer,e.target.value);field.onfocus=()=>{const next=questions.findIndex(question=>question.id===field.dataset.examAnswer);if(next>=0&&next!==session.indices[section]){session.indices[section]=next;saveIeltsFull()}}});const activeField=$('#ieltsFullAnswer');if(activeField){const event=activeField.type==='radio'?'onchange':'oninput';activeField[event]=e=>update(q.id,e.target.value)};$('#ieltsFullQuestion').querySelectorAll('[data-exam-flag]').forEach(button=>button.onclick=()=>{flags[button.dataset.examFlag]=!flags[button.dataset.examFlag];saveIeltsFull();renderIeltsFullQuestions(session,mock)});
  $('#ieltsFullPrevious').disabled=index===0;$('#ieltsFullNext').disabled=index===39;$('#ieltsFullPrevious').onclick=()=>goTo(index-1);$('#ieltsFullNext').onclick=()=>goTo(index+1);$('#ieltsFullFlag').hidden=false;$('#ieltsFullFlag').textContent=flags[q.id]?'✓ Remove Review flag':'⚑ Flag for Review';$('#ieltsFullFlag').onclick=()=>{flags[q.id]=!flags[q.id];saveIeltsFull();renderIeltsFullQuestions(session,mock)}}
function renderIeltsFullWriting(session,mock){const key=session.writingTab,task=key==='writing1'?customOpen.writingTask1.find(t=>t.id===mock.writingTask1Id):customOpen.writingTask2.find(t=>t.id===mock.writingTask2Id),draft=session.drafts[key]||'';
  $('#ieltsFullPartLabel').textContent='Writing';$('#ieltsFullNavigator').innerHTML=`<button type="button" class="${key==='writing1'?'active':''}" data-ielts-writing="writing1">Task 1</button><button type="button" class="${key==='writing2'?'active':''}" data-ielts-writing="writing2">Task 2</button>`;$$('[data-ielts-writing]').forEach(b=>b.onclick=()=>{session.writingTab=b.dataset.ieltsWriting;saveIeltsFull();renderIeltsFullWriting(session,mock)});
  $('#ieltsFullSource').innerHTML=`<h2>${key==='writing1'?'Academic Task 1':'Task 2'} · ${esc(task.type)}</h2><p>${esc(task.prompt).replaceAll('\n','<br>')}</p>${task.chartSpec?customChart(task.chartSpec):''}`;$('#ieltsFullAudio').innerHTML='';$('#ieltsFullQuestion').innerHTML=`<label for="ieltsFullDraft">我的作文 · 自动保存</label><textarea id="ieltsFullDraft" class="rec-text" rows="18" placeholder="在这里写作文">${esc(draft)}</textarea><p id="ieltsFullWordCount">${draft.trim()?draft.trim().split(/\s+/).length:0} words</p><small>提交 Writing 后，可在结果页复制题目与作文。</small>`;
  $('#ieltsFullDraft').oninput=e=>{session.drafts[key]=e.target.value;$('#ieltsFullWordCount').textContent=(e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0)+' words';saveIeltsFull()};$('#ieltsFullPrevious').disabled=key==='writing1';$('#ieltsFullNext').disabled=key==='writing2';$('#ieltsFullFlag').hidden=true;$('#ieltsFullPrevious').onclick=()=>{session.writingTab='writing1';saveIeltsFull();renderIeltsFullWriting(session,mock)};$('#ieltsFullNext').onclick=()=>{session.writingTab='writing2';saveIeltsFull();renderIeltsFullWriting(session,mock)}}
window.addEventListener('pagehide',()=>{clearInterval(ieltsFullTimer);ieltsFullSpeechToken++});
if(sessionStorage.getItem('ieltsFullActive')===state.examEngine.ieltsFullSession?.mockId&&state.examEngine.ieltsFullSession.section!=='finished')nav('ielts-full-exam');
