let computerExamTimer=null,computerExamSaveTimer=null,computerExamAudioUrl='',privateComputerQuestions=[];
function computerQuestionBank(){return [...state.examEngine.questions,...builtinExamQuestions,...privateComputerQuestions]}
function computerSessionQuestions(){const ids=state.examEngine.activeSession?.questionIds||[],bank=computerQuestionBank();return ids.map(id=>bank.find(question=>question.id===id)).filter(Boolean)}
function examDurationMinutes(projectId,type,count){if(projectId==='ielts'&&type==='ielts_reading')return 60;if(projectId==='ielts'&&type==='ielts_listening')return 30;if(projectId==='toeic'&&type==='full_mock')return 120;return Math.max(10,Math.ceil(count*1.2))}
function startComputerExam(projectId,type,mode='learning',format='specialized'){
  let questions=format==='full'?allProjectExamQuestions(projectId):allProjectExamQuestions(projectId,type);if(format==='full'){const required=projectId==='toeic'?PROJECT_EXAM_DEFAULTS.toeic:projectId==='ielts'?PROJECT_EXAM_DEFAULTS.ielts:[],available=new Set(questions.map(question=>question.type));if(required.some(item=>!available.has(item)))return toast('当前本地资料还不完整，暂时无法启动 Full Mock')}if(!questions.length)return toast('这个分区还没有可用的本地题目或音频');const startedAt=Date.now(),minutes=examDurationMinutes(projectId,format==='full'?'full_mock':type,questions.length);state.examEngine.activeSession={id:'exam-'+startedAt.toString(36),projectId,type:format==='full'?'full_mock':type,mode,format,questionIds:questions.map(question=>question.id),index:0,answers:{},review:{},highlights:[],startedAt,deadline:startedAt+minutes*60000,completedAt:null,result:null};save({immediate:true,refresh:false});nav('computer-exam')
}
function startPrivateComputerExam(paper){if(!paper.answers?.length)return toast('这份试卷还没有 Answer Key，无法本地判分');const perSection=paper.sections.length?Math.ceil(paper.answers.length/paper.sections.length):0;privateComputerQuestions=paper.answers.map((item,index)=>{const section=perSection?paper.sections[Math.min(paper.sections.length-1,Math.floor(index/perSection))]:null;return normalizeExamQuestion({id:`private:${paper.id}:${item.number}`,projectId:paper.projectId,type:paper.examType||'fill_blank',section:section?.title||paper.title,stem:`Question ${item.number} · 请按本地试卷内容作答`,answer:item.answer,content:paper.extractedText?{title:paper.title,passage:paper.extractedText}:null,audio:section?{sha256:section.audioSha256,start:null,end:null,sectionId:section.id}:null,source:{paperId:paper.id,title:paper.title},sourceType:'private_local',attribution:'用户本地私人资料'},paper.projectId)});const startedAt=Date.now(),minutes=examDurationMinutes(paper.projectId,paper.examType,privateComputerQuestions.length);state.examEngine.activeSession={id:'exam-'+startedAt.toString(36),privatePaperId:paper.id,projectId:paper.projectId,type:paper.examType,mode:'exam',format:'timed',questionIds:privateComputerQuestions.map(question=>question.id),index:0,answers:{},review:{},highlights:[],startedAt,deadline:startedAt+minutes*60000,completedAt:null,result:null};save({immediate:true,refresh:false});nav('computer-exam')}
function queueComputerExamSave(){clearTimeout(computerExamSaveTimer);$('#computerExamSaveState').textContent='保存中…';computerExamSaveTimer=setTimeout(()=>{save({refresh:false});$('#computerExamSaveState').textContent='已保存'},900)}
function safeHighlightedPassage(text,highlights){let html=esc(text).replaceAll('\n','<br>');for(const highlight of highlights){const safe=esc(highlight);if(safe&&html.includes(safe))html=html.replace(safe,`<mark>${safe}</mark>`)}return html}
function examLearningHint(question){if(typeof localTeacherHint==='function')return localTeacherHint(question);if(question.projectId==='ielts'&&question.tags.includes('true-false-not-given'))return 'Learning Mode：先定位原文，再判断陈述是相同、相反，还是原文没有给出。不要用常识补答案。';if(question.projectId==='ielts')return 'Learning Mode：先预测答案词性与字数限制，再回原文定位同义替换。';if(question.projectId==='toeic')return 'Learning Mode：先判断空格需要的词性或句法功能，再检查固定搭配与时态。';return 'Learning Mode：先定位证据，再作答。'}
async function loadComputerExamAudio(question){if(computerExamAudioUrl){URL.revokeObjectURL(computerExamAudioUrl);computerExamAudioUrl=''}const audio=$('#computerExamAudio'),sha256=question.audio?.sha256||question.audio?.audioSha256;if(!audio||!sha256)return;try{const record=await getPrivateBlob(sha256);if(!record?.blob)return;computerExamAudioUrl=URL.createObjectURL(record.blob);audio.src=computerExamAudioUrl;audio.onloadedmetadata=()=>{if(Number.isFinite(question.audio?.start))audio.currentTime=question.audio.start};audio.ontimeupdate=()=>{if(Number.isFinite(question.audio?.end)&&audio.currentTime>=question.audio.end)audio.pause()}}catch(error){console.error('本地音频加载失败',error)}}
function renderComputerExam(){
  const session=state.examEngine.activeSession;if(!session||session.completedAt)return nav('exam-engine');const questions=computerSessionQuestions(),question=questions[session.index];if(!question)return nav('exam-engine');
  const project=projectById(session.projectId),answer=session.answers[question.id]||'',highlights=session.highlights.filter(item=>item.questionId===question.id).map(item=>item.text);$('#computerExamTitle').textContent=(project?.name||session.projectId)+' · '+(EXAM_TYPE_REGISTRY[session.type]?.label||session.type);$('#computerExamMeta').textContent=`${session.mode==='learning'?'Learning Mode':'Exam Mode'} · ${session.format==='full'?'Full Mock':session.format==='timed'?'Timed Practice':'专项练习'} · ${questions.length} 题${session.projectId==='ielts'&&session.type==='ielts_listening'&&questions.length!==40?'（当前资料非标准 40 题）':''}`;$('#computerQuestionNumber').textContent=`Question ${session.index+1} / ${questions.length}`;$('#computerQuestionStem').textContent=question.stem;$('#toggleComputerReview').textContent=session.review[question.id]?'✓ 已标记 Review':'标记 Review';$('#toggleComputerReview').classList.toggle('primary',Boolean(session.review[question.id]));
  $('#computerExamNav').innerHTML=questions.map((item,index)=>`<button data-computer-index="${index}" class="${index===session.index?'active':''} ${session.answers[item.id]?'answered':''} ${session.review[item.id]?'review':''}">${index+1}</button>`).join('');$$('[data-computer-index]').forEach(button=>button.onclick=()=>{session.index=Number(button.dataset.computerIndex);renderComputerExam()});
  const passage=question.content?.passage||'';$('#computerSourceTitle').textContent=question.content?.title||question.section||'题目资料';$('#computerSourceContent').innerHTML=passage?safeHighlightedPassage(passage,highlights):'<p class="sub">本题没有阅读文章。请在右侧直接作答。</p>';$('#highlightExamSelection').style.display=passage?'inline-flex':'none';
  $('#computerAudioArea').innerHTML=question.audio?'<audio id="computerExamAudio" controls preload="metadata"></audio><p class="sub">音频按需从本机读取，不写播放进度。</p>':session.type==='ielts_listening'||session.type.startsWith('toeic_part_')&&Number(session.type.split('_').pop())<=4?'<p class="sub">当前题目没有绑定音频。请先在私人题库中导入并绑定 Section。</p>':'';loadComputerExamAudio(question);
  $('#computerAnswerArea').innerHTML=question.options.length?`<div class="practice-options">${question.options.map((option,index)=>`<button class="practice-option ${normalizedExamAnswer(answer)===normalizedExamAnswer(option)?'selected':''}" data-computer-answer="${esc(option)}"><span>${String.fromCharCode(65+index)}</span>${esc(option)}</button>`).join('')}</div>`:`<input class="field computer-text-answer" id="computerTextAnswer" value="${esc(String(answer))}" autocomplete="off" placeholder="输入答案">`;
  $$('[data-computer-answer]').forEach(button=>button.onclick=()=>{session.answers[question.id]=button.dataset.computerAnswer;queueComputerExamSave();renderComputerExam()});const input=$('#computerTextAnswer');if(input)input.oninput=()=>{session.answers[question.id]=input.value;queueComputerExamSave()};$('#computerLearningHint').textContent=session.mode==='learning'?examLearningHint(question):'';$('#computerLearningHint').hidden=session.mode!=='learning';$('#computerExamFeedback').textContent='';
  $('#previousComputerQuestion').disabled=session.index===0;$('#nextComputerQuestion').disabled=session.index===questions.length-1;$('#previousComputerQuestion').onclick=()=>{session.index=Math.max(0,session.index-1);renderComputerExam()};$('#nextComputerQuestion').onclick=()=>{session.index=Math.min(questions.length-1,session.index+1);renderComputerExam()};startComputerExamClock()
}
function startComputerExamClock(){clearInterval(computerExamTimer);const update=()=>{const session=state.examEngine.activeSession;if(!session||session.completedAt)return clearInterval(computerExamTimer);const left=Math.max(0,session.deadline-Date.now()),minutes=Math.floor(left/60000),seconds=Math.floor(left%60000/1000);$('#computerExamClock').textContent=String(minutes).padStart(2,'0')+':'+String(seconds).padStart(2,'0');if(!left){clearInterval(computerExamTimer);submitComputerExam(true)}};update();computerExamTimer=setInterval(update,1000)}
function submitComputerExam(automatic=false){const session=state.examEngine.activeSession,questions=computerSessionQuestions();if(!session||session.completedAt)return;if(!automatic&&!confirm('确认交卷？未作答题目会计为错误。'))return;clearInterval(computerExamTimer);clearTimeout(computerExamSaveTimer);let correct=0;const now=Date.now();for(const question of questions){const answer=session.answers[question.id]||'',ok=isObjectiveAnswerCorrect(question,answer);if(ok)correct++;else{const previous=state.examEngine.wrong[question.id];state.examEngine.wrong[question.id]={questionId:question.id,projectId:question.projectId,type:question.type,lastAnswer:String(answer),lastAttemptAt:now,reviewStep:0,due:now,reasons:previous?.reasons||[]}}state.examEngine.attempts.push({id:'attempt-'+now+'-'+question.id,sessionId:session.id,questionId:question.id,projectId:question.projectId,type:question.type,answer:String(answer),correct:ok,createdAt:now,sourceType:question.sourceType})}if(state.examEngine.attempts.length>500)state.examEngine.attempts=state.examEngine.attempts.slice(-500);session.completedAt=now;session.result={correct,total:questions.length,percent:questions.length?Math.round(correct/questions.length*100):0};save({immediate:true,refresh:false});if(typeof renderLocalTeacherResult==='function'){renderLocalTeacherResult(session,questions);return}$('#page-computer-exam').innerHTML=`<div class="card computer-result"><span class="practice-label">本地判分完成</span><h2>${correct} / ${questions.length}</h2><p>正确率 ${session.result.percent}% · 错题已加入当前学习空间的复习队列。</p><button class="btn primary" id="finishComputerExam">返回考试训练</button></div>`;$('#finishComputerExam').onclick=()=>{state.examEngine.activeSession=null;save({immediate:true,refresh:false});location.reload()}}
$('#toggleComputerReview').onclick=()=>{const session=state.examEngine.activeSession,question=computerSessionQuestions()[session?.index];if(!session||!question)return;session.review[question.id]=!session.review[question.id];save({refresh:false});renderComputerExam()};
$('#highlightExamSelection').onclick=()=>{const session=state.examEngine.activeSession,question=computerSessionQuestions()[session?.index],text=window.getSelection()?.toString().trim().slice(0,500);if(!session||!question||!text||!question.content?.passage.includes(text))return toast('请先在左侧文章中选择文字');if(!session.highlights.some(item=>item.questionId===question.id&&item.text===text))session.highlights.push({questionId:question.id,text});save({refresh:false});renderComputerExam()};
$('#exitComputerExam').onclick=()=>{clearInterval(computerExamTimer);nav('exam-engine')};$('#submitComputerExam').onclick=()=>submitComputerExam(false);
