const EXAM_TYPE_REGISTRY={
  term_definition:{label:'名词解释',answerKind:'subjective'},short_answer:{label:'简答题',answerKind:'subjective'},essay:{label:'论述题',answerKind:'subjective'},
  toeic_part_1:{label:'Listening Part 1',answerKind:'objective'},toeic_part_2:{label:'Listening Part 2',answerKind:'objective'},toeic_part_3:{label:'Listening Part 3',answerKind:'objective'},toeic_part_4:{label:'Listening Part 4',answerKind:'objective'},toeic_part_5:{label:'Reading Part 5',answerKind:'objective'},toeic_part_6:{label:'Reading Part 6',answerKind:'objective'},toeic_part_7:{label:'Reading Part 7',answerKind:'objective'},
  ielts_reading:{label:'Reading',answerKind:'objective'},ielts_listening:{label:'Listening',answerKind:'objective'},
  choice:{label:'选择题',answerKind:'objective'},true_false:{label:'判断题',answerKind:'objective'},fill_blank:{label:'填空题',answerKind:'objective'}
};
const PROJECT_EXAM_DEFAULTS={toeic:['toeic_part_1','toeic_part_2','toeic_part_3','toeic_part_4','toeic_part_5','toeic_part_6','toeic_part_7'],ielts:['ielts_reading','ielts_listening'],chinese:['term_definition','short_answer','essay']};
const CUSTOM_EXAM_TYPES=['choice','true_false','fill_blank','term_definition','short_answer','essay'];
let examEngineView={projectId:'',type:''};
function examProjectTypes(project){return [...(project.examTypes||PROJECT_EXAM_DEFAULTS[project.id]||CUSTOM_EXAM_TYPES)]}
function normalizeExamQuestion(question,projectId){return {id:String(question.id),projectId:question.projectId||projectId,type:question.type,section:question.section||'',stem:String(question.stem||''),options:Array.isArray(question.options)?question.options:[],answer:question.answer??null,keywords:Array.isArray(question.keywords)?question.keywords:[],referenceAnswer:String(question.referenceAnswer||''),points:Array.isArray(question.scorePoints)?question.scorePoints:Array.isArray(question.points)?question.points:[],explanation:String(question.explanation||''),source:question.source||null,sourceType:question.sourceType||'local',license:question.license||'',attribution:question.attribution||'',tags:Array.isArray(question.tags)?question.tags:[],content:question.content||null,audio:question.audio||null}}
function adaptPreqinQuestion(question){return normalizeExamQuestion({...question,points:question.scorePoints||question.outlinePoints||[]},'chinese')}
function projectExamQuestions(projectId,type=''){return state.examEngine.questions.filter(question=>question.projectId===projectId&&(!type||question.type===type))}
function renderExamEngine(){
  if(!$('#examProjectSelect'))return;const projects=visibleProjects().filter(project=>PROJECT_EXAM_DEFAULTS[project.id]||project.id.startsWith('custom-')||project.id==='custom');if(!projects.length){$('#examProjectSelect').innerHTML='';$('#examEngineTitle').textContent='当前没有启用考试项目';$('#examEngineDescription').textContent='到“我的”显示或添加一个考试 / 专业课项目。';$('#examTypeTabs').innerHTML='';return}
  if(!projects.some(project=>project.id===examEngineView.projectId))examEngineView.projectId=projects[0].id;const project=projectById(examEngineView.projectId),types=examProjectTypes(project);if(!types.includes(examEngineView.type))examEngineView.type=types[0]||'';
  $('#examProjectSelect').innerHTML=projects.map(item=>`<option value="${item.id}">${esc(item.name)}</option>`).join('');$('#examProjectSelect').value=project.id;$('#examTypeTabs').innerHTML=types.map(type=>`<button class="mode ${type===examEngineView.type?'active':''}" data-exam-type="${type}">${esc(EXAM_TYPE_REGISTRY[type]?.label||type)}</button>`).join('');$$('[data-exam-type]').forEach(button=>button.onclick=()=>{examEngineView.type=button.dataset.examType;renderExamEngine()});
  const questions=project.id==='chinese'?(questionCatalog?.questions||[]).map(adaptPreqinQuestion).filter(question=>question.type===examEngineView.type):projectExamQuestions(project.id,examEngineView.type);$('#examEngineEyebrow').textContent=project.type.replaceAll('_',' ').toUpperCase();$('#examEngineTitle').textContent=project.name+' · '+(EXAM_TYPE_REGISTRY[examEngineView.type]?.label||'题型');$('#examEngineDescription').textContent=project.id==='chinese'?'先秦文学保持名词解释、简答与论述三类真实题型。':project.id==='toeic'?'按 Listening Part 1–4 与 Reading Part 5–7 分区。':project.id==='ielts'?'当前先建立 Reading 与 Listening 分区；Writing / Speaking 后续单独接入。':'自定义项目可以选择自己的题型集合。';$('#examEngineSummary').innerHTML=`<b>${questions.length}</b><span>本地可用题目</span><small>${questions.length?'可以进入训练':'题型框架已就绪，等待题库接入'}</small>`;$('#examEngineStatus').textContent=questions.length?'标准答案题本地判定；主观题使用基础覆盖检查。':'当前不会调用 AI，也不会伪造练习题。';$('#startExamEngine').disabled=!questions.length&&project.id!=='chinese';$('#customExamTypeConfig').innerHTML=project.id.startsWith('custom-')||project.id==='custom'?'<div class="label">自定义题型</div>'+CUSTOM_EXAM_TYPES.map(type=>`<label><input type="checkbox" data-custom-exam-type="${type}" ${types.includes(type)?'checked':''}> ${esc(EXAM_TYPE_REGISTRY[type].label)}</label>`).join(''):'';$$('[data-custom-exam-type]').forEach(input=>input.onchange=()=>{const selected=$$('[data-custom-exam-type]:checked').map(item=>item.dataset.customExamType);if(!selected.length){input.checked=true;return toast('至少保留一种题型')}project.examTypes=selected;save();renderExamEngine()})
}
$('#examProjectSelect').onchange=event=>{examEngineView.projectId=event.target.value;examEngineView.type='';renderExamEngine()};
$('#startExamEngine').onclick=()=>{const project=projectById(examEngineView.projectId);if(project?.id==='chinese'){courseView.type=examEngineView.type;nav('preqin-literature');return}toast('该分区题库将在下一阶段接入')};
loadQuestionCatalog().then(()=>renderExamEngine()).catch(()=>renderExamEngine());
