const ITALIAN_GRAMMAR_LABELS=[
  {topics:'名词性别与冠词 · essere · mangiare / bere · 基本语序',verbs:['essere','mangiare','bere']},
  {topics:'正式/非正式问候 · stare 的常用问候形式',verbs:['stare']},
  {topics:'冠词 · volere · mangiare / bere · 动词后接名词或不定式',verbs:['volere','mangiare','bere']},
  {topics:'gender · 单复数 · 形容词一致 · essere 描述',verbs:['essere']},
  {topics:'地点介词 · andare 的常用形式 · 出行常用动词',verbs:['andare','arrivare','partire','trovare']}
];
function setItalianView(view){const grammar=view==='grammar';$('#italianCoursePanel').hidden=grammar;$('#italianGrammarPanel').hidden=!grammar;$$('[data-italian-view]').forEach(button=>button.classList.toggle('active',button.dataset.italianView===view));if(grammar)renderItalianGrammar();else renderItalianCourse()}
async function renderItalianGrammar(){const panel=$('#italianGrammarPanel');if(!panel)return;panel.innerHTML='<div class="card italian-loading">正在读取 grammar guidebook…</div>';try{await loadItalianCourse();const units=italianCourseUnits();panel.innerHTML=`<article class="card italian-grammar-intro"><div><div class="eyebrow">SOURCE-BASED GRAMMAR</div><h3>跟着主课程学基础语法</h3><p>以下内容直接来自已审计的 MIT 课程 guidebook。点意大利语例词可查本地中文；练习仍使用对应单元的原课程题。</p></div><div class="italian-grammar-gap"><b>当前真实缺口</b><span>尚无许可与质量都合适的 avere 完整变位、规则动词完整范式和常用不规则动词表，因此暂不伪造。</span></div></article><div class="italian-grammar-grid">${units.map((unit,index)=>{const meta=ITALIAN_GRAMMAR_LABELS[index],first=unit.lessons[0],unlocked=italianLessonUnlocked(italianLessonPosition(first.id));return`<article class="card italian-grammar-card"><div class="row between"><span class="tag">Unit ${index+1}</span><span class="italian-grammar-state">${unlocked?'可练习':'随主线解锁'}</span></div><h3>${esc(unit.titleZh)}</h3><p class="italian-grammar-topics">${esc(meta.topics)}</p><div class="italian-verb-tags">${meta.verbs.map(verb=>`<button data-italian-lookup="${verb}">${verb}</button>`).join('')}</div><details><summary>查看原课程 Guidebook</summary><div class="italian-grammar-copy">${italianGuideMarkup(unit.guidebook)}</div></details><button class="btn ${unlocked?'primary':''}" data-italian-grammar-practice="${first.id}" ${unlocked?'':'disabled'}>进入本单元练习</button></article>`}).join('')}</div>`;panel.querySelectorAll('.italian-grammar-copy i').forEach(node=>node.innerHTML=italianClickableText(node.textContent));bindItalianLookupButtons(panel);$$('[data-italian-grammar-practice]').forEach(button=>button.onclick=()=>{setItalianView('course');openItalianLesson(button.dataset.italianGrammarPractice,true)})}catch(error){panel.innerHTML=`<div class="card italian-error">${esc(error.message)}</div>`}}
$$('[data-italian-view]').forEach(button=>button.onclick=()=>setItalianView(button.dataset.italianView));
