/* IELTS Custom Training Mock: stable references, openly licensed pack, local-only speaking. */
let customManifest=null,customOpen=null,customSpeaking=null,customTab='mocks',customWork=null;
let customSpeechToken=0,customSpeechPart='';
const CUSTOM_PRIVATE_DB='englishMemoryLab_ielts_custom_private_v1';
function customDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(CUSTOM_PRIVATE_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('banks');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function customSpeakingStore(value){const db=await customDB();return new Promise((resolve,reject)=>{const tx=db.transaction('banks',value?'readwrite':'readonly'),s=tx.objectStore('banks'),r=value?s.put(value,activeProfile().id):s.get(activeProfile().id);let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function loadIeltsCustom(){if(!customManifest){const [m,o]=await Promise.all([fetch('data/ielts-custom-manifest.json'),fetch('data/ielts-custom-open.json')]);if(!m.ok||!o.ok)throw new Error('IELTS 数据加载失败');customManifest=await m.json();customOpen=await o.json()}customSpeaking=await customSpeakingStore();return customManifest}
function customProgress(id){state.examEngine.customMockProgress=state.examEngine.customMockProgress||{};return state.examEngine.customMockProgress[id]||(state.examEngine.customMockProgress[id]={sections:{},drafts:{}})}
function completeCustomMockSection(id,section){if(!id||!section)return;customProgress(id).sections[section]=Date.now();save({immediate:true,refresh:false})}
function customMock(id){return customManifest.mocks.find(mock=>mock.id===id)}
function customReading(id){return customOpen.reading.find(item=>item.id===id)}
function customListening(id){return customOpen.listening.find(item=>item.id===id)}
function customMockReady(mock){const l=customListening(mock.listeningId);return Boolean(l&&customReading(mock.readingId)&&customSpeaking&&(l.audioType!=='TTS'||'speechSynthesis'in window))}
async function renderIeltsCustom(){const panel=$('#customCatalog');if(!panel)return;panel.innerHTML='<p class="sub">正在读取题库目录…</p>';try{await loadIeltsCustom()}catch(error){panel.textContent='题库加载失败：'+error.message;return}
  $('#customSpeakingStatus').textContent=customSpeaking?'已在当前学习空间导入：43 个 Part 1 话题、46 张 cue card、46 组 Part 3。题目仅存本机。':'未在当前学习空间导入原版 0903 PDF；S001–S030 的原题暂不可打开。';
  $$('[data-custom-tab]').forEach(button=>button.classList.toggle('primary',button.dataset.customTab===customTab));
  if(customTab==='mocks')panel.innerHTML=`<p class="sub">已固定 30 组引用。Listening 01–07 使用设备合成语音，18 有来源提供的预录合成音频；其余来源未加载，21–30 待补。导入当季口语原版 PDF 后，仅题目与音频齐备的整套可以启动。</p><div class="custom-grid">${customManifest.mocks.map(mock=>{const l=customListening(mock.listeningId),r=customReading(mock.readingId),ready=customMockReady(mock),progress=customProgress(mock.id);return `<article class="card custom-card"><h3>${esc(mock.label)}</h3><small>CUSTOM TRAINING MOCK · 自组训练 Mock</small><p>Listening ${l?(l.audioType==='TTS'?'设备 TTS 模拟':'预录 TTS 音频'):'待加载 / 待补'} · Reading ${r?'已加载':'仅私人资料 / 未加载'}<br>Writing 已加载 · Speaking ${customSpeaking?'本机已导入':'等待本地导入'}</p><p class="sub">${Object.keys(progress.sections).length} / 5 个科目已完成</p><div class="row"><button class="btn primary" data-custom-full="${mock.id}" ${ready?'':'disabled'}>开始整套</button><button class="btn" data-custom-start="${mock.id}:listening" ${l?'':'disabled'}>听力</button><button class="btn" data-custom-start="${mock.id}:reading" ${r?'':'disabled'}>阅读</button><button class="btn" data-custom-start="${mock.id}:writing">写作</button><button class="btn" data-custom-start="${mock.id}:speaking" ${customSpeaking?'':'disabled'}>口语</button></div></article>`}).join('')}</div>`;
  else if(customTab==='listening')panel.innerHTML=`<h3>Listening Bank · 20 个候选引用</h3><p class="sub">7 套设备合成语音、1 套预录合成语音；12 个引用未加载或不支持公开打包。没有真人录音可用。</p><div class="custom-grid">${[...customOpen.listening,...customManifest.listeningReferences].map(item=>`<article class="card custom-card"><h3>${esc(item.id)} · ${esc(item.title||item.sourceRepo.split('/').pop())}</h3><p>${esc(item.audioType)} · ${esc(item.availability)} · ${item.parts?'40Q / 40A':'题目及音频未加载'}</p><small>来源：${esc(item.sourceRepo)} · ${esc(item.contentLicense||'题目授权未明确')}</small><button class="btn" data-custom-solo="listening:${item.id}" ${item.parts?'':'disabled'}>开始练习</button></article>`).join('')}</div>`;
  else if(customTab==='reading')panel.innerHTML=`<h3>Academic Reading Bank</h3><p class="sub">9 套开放性较明确、各含同卷 P1–P3 / 40Q / 40A；21 个风险来源仅存引用，未加载正文。</p><div class="custom-grid">${[...customOpen.reading,...customManifest.readingReferences].map(item=>`<article class="card custom-card"><h3>${esc(item.id)} · ${esc(item.title||'私人来源引用')}</h3><p>${item.parts?'40Q / 40A · 可打开':'仅私人资料可用 / 未加载'}</p><button class="btn" data-custom-solo="reading:${item.id}" ${item.parts?'':'disabled'}>打开阅读</button></article>`).join('')}</div>`;
  else if(customTab==='writing')panel.innerHTML=`<h3>Writing Bank</h3><p class="sub">Task 1：38 道 prompt 与可绘制图表 · Task 2：42 道 prompt。</p><div class="custom-grid">${[...customOpen.writingTask1,...customOpen.writingTask2].map(item=>`<article class="card custom-card"><h3>${esc(item.id)} · ${esc(item.type)}</h3><p>${esc(item.prompt.slice(0,100))}…</p><button class="btn" data-custom-solo="writing:${item.id}">打开写作</button></article>`).join('')}</div>`;
  else panel.innerHTML=customSpeaking?`<h3>Speaking · 2026 年 9–12 月</h3><p>43 Part 1 topics / 247 questions · 46 cue cards · 46 Part 3 groups / 233 questions</p><div class="custom-grid">${customManifest.speakingSets.map(set=>`<article class="card custom-card"><h3>${set.id}</h3><p>${esc(set.part1TopicIds.join(' · '))}<br>${esc(set.part2CueCardId)} → ${esc(set.part3GroupId)}</p><button class="btn" data-custom-solo="speaking:${set.id}">查看原题</button></article>`).join('')}</div>`:'<p class="sub">请先从本机导入原版 0903 PDF；公开站点不包含原题正文。</p>';
  $$('[data-custom-full]').forEach(b=>b.onclick=()=>launchCustomFull(b.dataset.customFull));$$('[data-custom-start]').forEach(b=>b.onclick=()=>{const [id,section]=b.dataset.customStart.split(':');startCustomSection(id,section)});$$('[data-custom-solo]').forEach(b=>b.onclick=()=>{const [kind,id]=b.dataset.customSolo.split(':');startCustomSolo(kind,id)});
}
function launchCustomFull(id){const mock=customMock(id);if(!customMockReady(mock))return toast('整套仍缺可用资料');const done=customProgress(id).sections;const next=['listening','reading','writing1','writing2','speaking'].find(item=>!done[item]);startCustomSection(id,next||'listening')}
function startCustomSection(id,section){const mock=customMock(id);if(!mock)return;if(section==='listening')return startCustomExam('listening',mock.listeningId,id);if(section==='reading')return startCustomExam('reading',mock.readingId,id);if(section==='speaking')return openCustomWork('speaking',mock.speakingSetId,id);return openCustomWork('writing',section==='writing2'?mock.writingTask2Id:mock.writingTask1Id,id)}
function startCustomSolo(kind,id){if(kind==='reading'||kind==='listening')startCustomExam(kind,id,null);else openCustomWork(kind,id,null)}
function customAnswerVariants(value){if(Array.isArray(value))return [...new Set(value.flat(Infinity).map(item=>typeof item==='object'?item.value:item).map(String))];return [String(value)]}
function customQuestions(kind,item){return item.parts.flatMap(part=>kind==='listening'?part.questions.map(q=>({n:q.number,stem:q.prompt,answer:q.answer,explanation:q.explanation,part})):
  part.groups.flatMap(g=>g.questions.map(q=>({n:q.number,stem:(g.instruction?g.instruction+'\n':'')+q.prompt,answer:q.answers,explanation:q.explanation,part}))));}
function startCustomExam(kind,id,mockId){const item=kind==='reading'?customReading(id):customListening(id);if(!item)return toast('这份资料还没有加载');if(kind==='listening'&&item.audioType==='TTS'&&!('speechSynthesis'in window))return toast('当前设备不支持合成语音，不能开始听力');
  privateComputerQuestions=buildCustomExamQuestions(kind,item);
  if(privateComputerQuestions.length!==40)return toast('题目不足 40，拒绝启动');const now=Date.now();state.examEngine.activeSession={id:'exam-'+now.toString(36),customMockId:mockId,customSection:kind,customBankId:id,projectId:'ielts',type:`ielts_${kind}`,mode:'exam',format:'timed',questionIds:privateComputerQuestions.map(q=>q.id),index:0,answers:{},review:{},highlights:[],startedAt:now,deadline:now+(kind==='reading'?60:30)*60000,completedAt:null,result:null};save({immediate:true,refresh:false});nav('computer-exam')}
function renderCustomListeningAudio(session,question){if(session.type!=='ielts_listening')return;const item=customListening(session.customBankId),part=item?.parts.find(p=>question.section.endsWith('Part '+p.number));const area=$('#computerAudioArea');if(!part||!area)return;const partId=session.customBankId+':'+part.number;
  if(part.audioUrl){const existing=area.querySelector('audio[data-custom-part]');if(existing?.dataset.customPart===partId)return;area.innerHTML=`<p class="sub">Part ${part.number} · 来源提供的预录 TTS；按需加载</p><audio controls preload="metadata" data-custom-part="${esc(partId)}" src="${esc(part.audioUrl)}"></audio>`;return}
  if(customSpeechPart&&customSpeechPart!==partId){customSpeechToken++;speechSynthesis.cancel();customSpeechPart=''}if(area.dataset.customPart===partId)return;area.dataset.customPart=partId;area.innerHTML=`<p class="sub">Part ${part.number} · 设备合成语音模拟（非真人或原始考试录音；练习停顿不计时）</p><button class="btn primary" id="customPlayPart">▶ 播放本 Part</button><button class="btn" id="customStopPart">■ 停止</button>`;$('#customPlayPart').onclick=()=>{customSpeechToken++;speechSynthesis.cancel();customSpeechPart=partId;const token=customSpeechToken;let index=0;const play=()=>{if(token!==customSpeechToken||index>=part.lines.length)return;const line=part.lines[index++],utterance=new SpeechSynthesisUtterance(line.text);utterance.lang='en-GB';utterance.rate=.92;utterance.onend=play;speechSynthesis.speak(utterance)};play()};$('#customStopPart').onclick=()=>{customSpeechToken++;customSpeechPart='';speechSynthesis.cancel()}}
function buildCustomExamQuestions(kind,item){return customQuestions(kind,item).map(({n,stem,answer,explanation,part})=>normalizeExamQuestion({id:`custom:${item.id}:${n}`,projectId:'ielts',type:`ielts_${kind}`,section:`${item.title} · Part ${part.number}`,stem,answer:customAnswerVariants(answer),explanation,content:kind==='reading'?{title:part.title,passage:part.texts.flatMap(t=>t.paragraphs||[]).map(p=>(p.id?p.id+'\n':'')+p.text).join('\n\n')}:null,sourceType:'custom_open',license:item.contentLicense,attribution:item.sourceRepo},'ielts'))}
const customColors=['#6259c5','#28a7a0','#ed9b56','#bb68b3','#507fc8','#91a951'];
function customChart(spec){if(!spec)return '<p class="sub">缺少图表媒体。</p>';
  const title=`<h3>${esc(spec.title||'')}</h3>`, kind=spec.kind;
  if(kind==='mixed')return `<div class="custom-chart-mixed">${(spec.panels||[]).map(customChart).join('')}</div>`;
  if(kind==='table')return title+`<div class="custom-table-wrap"><table>${(spec.rows||[]).map((row,i)=>`<tr>${row.map(cell=>i?`<td>${esc(String(cell))}</td>`:`<th>${esc(String(cell))}</th>`).join('')}</tr>`).join('')}</table></div>`;
  if(kind==='process')return title+`<div class="custom-process">${(spec.steps||[]).map((step,i)=>`<div><b>${i+1}. ${esc(step.label)}</b><small>${step.next?.length?'→ '+step.next.map(next=>esc((spec.steps.find(s=>s.id===next)||{label:next}).label)).join(' / '):'流程终点'}</small></div>`).join('')}</div>`;
  if(kind==='map')return title+`<div class="custom-chart-mixed">${(spec.snapshots||[]).map(snap=>`<figure><figcaption>${esc(snap.label)}</figcaption><svg role="img" aria-label="${esc(snap.label)}" viewBox="0 0 600 350"><rect width="600" height="350" fill="#f4f8f5"/>${(snap.features||[]).map(f=>{const x=Number(f.x)*6,y=Number(f.y)*3.5,w=Number(f.w)*6,h=Number(f.h)*3.5,fill=f.shape==='river'?'#8ac4d7':f.shape==='road'?'#b9b7bd':f.shape==='tree'?'#90bc84':'#ddd1b7';return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${f.shape==='circle'?Math.min(w,h)/2:5}" fill="${fill}" stroke="#6e7882"/><text x="${x+w/2}" y="${y+h/2}" text-anchor="middle" font-size="11">${esc(f.label)}</text>`}).join('')}</svg></figure>`).join('')}</div>`;
  const categories=spec.x_axis?.categories||[],series=spec.series||[];
  if(kind==='pie'){let offset=0;const vals=series[0]?.values||[],total=vals.reduce((a,b)=>a+Number(b),0);const sectors=vals.map((raw,i)=>{const share=Number(raw)/total,a=offset*2*Math.PI-Math.PI/2,b=(offset+share)*2*Math.PI-Math.PI/2;offset+=share;const x1=200+135*Math.cos(a),y1=180+135*Math.sin(a),x2=200+135*Math.cos(b),y2=180+135*Math.sin(b);return `<path d="M 200 180 L ${x1} ${y1} A 135 135 0 ${share>.5?1:0} 1 ${x2} ${y2} Z" fill="${customColors[i%6]}" stroke="white" stroke-width="2"/>`}).join('');return title+`<svg viewBox="0 0 600 360" role="img" aria-label="${esc(spec.title)}">${sectors}${categories.map((cat,i)=>`<rect x="370" y="${42+i*42}" width="14" height="14" fill="${customColors[i%6]}"/><text x="392" y="${54+i*42}" font-size="13">${esc(cat)}: ${esc(String(vals[i]))}</text>`).join('')}</svg>`}
  const max=Number(spec.y_axis?.max)||Math.max(1,...series.flatMap(s=>s.values||[]).map(Number)),min=Number(spec.y_axis?.min)||0,span=Math.max(1,max-min),x=i=>70+i*470/Math.max(1,categories.length-1),y=v=>260-(Number(v)-min)*210/span;
  const grid=[0,.25,.5,.75,1].map(t=>`<line x1="60" x2="550" y1="${260-t*210}" y2="${260-t*210}" stroke="#dae0ec"/><text x="48" y="${264-t*210}" text-anchor="end" font-size="11">${Math.round((min+t*span)*100)/100}</text>`).join('');
  let marks='';for(let j=0;j<series.length;j++){const s=series[j],color=customColors[j%6];if(kind==='line'){marks+=`<polyline fill="none" stroke="${color}" stroke-width="3" points="${s.values.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}"/>`+s.values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="${color}"/>`).join('')}
    else marks+=s.values.map((v,i)=>{let bottom=0;if(kind==='stacked_bar')bottom=series.slice(0,j).reduce((n,prev)=>n+Number(prev.values[i]||0),0);const width=kind==='grouped_bar'?Math.min(26,350/categories.length/series.length):Math.min(50,350/categories.length),bx=70+i*470/Math.max(1,categories.length)+(kind==='grouped_bar'?(j-series.length/2)*width:0)-width/2;return `<rect x="${bx}" y="${y(bottom+v)}" width="${width}" height="${Math.max(0,y(bottom)-y(bottom+v))}" fill="${color}"/>`}).join('')}
  return title+`<svg viewBox="0 0 600 360" role="img" aria-label="${esc(spec.title)}">${grid}${marks}${categories.map((cat,i)=>`<text x="${x(i)}" y="285" text-anchor="end" transform="rotate(-30 ${x(i)} 285)" font-size="11">${esc(cat)}</text>`).join('')}${series.map((s,j)=>`<rect x="${70+j*125}" y="335" width="12" height="12" fill="${customColors[j%6]}"/><text x="${86+j*125}" y="345" font-size="11">${esc(s.name)}</text>`).join('')}</svg><p class="sub">${esc(spec.unit||'')}</p>`
}
function openCustomWork(kind,id,mockId){const item=kind==='speaking'?customManifest?.speakingSets.find(set=>set.id===id):[...customOpen.writingTask1,...customOpen.writingTask2].find(task=>task.id===id);if(!item||kind==='speaking'&&!customSpeaking)return toast('所选题目未加载');customWork={kind,id,mockId};nav('ielts-custom-work')}
function renderIeltsCustomWork(){const box=$('#customWorkspace');if(!customWork||!box)return;const {kind,id,mockId}=customWork;
  if(kind==='speaking'){const set=customManifest.speakingSets.find(s=>s.id===id),p1=set.part1TopicIds.map(key=>customSpeaking.part1.find(t=>t.id===key)),p2=customSpeaking.part2.find(c=>c.id===set.part2CueCardId),p3=customSpeaking.part3.find(g=>g.id===set.part3GroupId);if(p1.some(x=>!x)||!p2||!p3||p3.linkedPart2Id!==p2.id){box.textContent='口语题库引用错误';return}
    box.innerHTML=`<button class="btn" id="customBack">← 返回题库</button><span class="practice-label">自组训练 Mock · ${esc(id)}</span><h2>Speaking</h2><h3>Part 1</h3>${p1.map(t=>`<section><h4>${esc(t.title)}</h4><ol>${t.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol></section>`).join('')}<h3>Part 2 · ${esc(p2.id)}</h3><p>${esc(p2.prompt)}</p><ul>${p2.cuePoints.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><h3>Part 3 · ${esc(p3.id)}</h3><ol>${p3.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol><div class="row"><button class="btn" data-go-page="language-skills">打开现有录音工具</button><button class="btn primary" id="customFinish">标记本次口语完成</button></div>`;
  }else {const task=[...customOpen.writingTask1,...customOpen.writingTask2].find(t=>t.id===id),section=id.startsWith('WT1')?'writing1':'writing2';state.examEngine.customPractice=state.examEngine.customPractice||{drafts:{}};const progress=mockId?customProgress(mockId):state.examEngine.customPractice,text=progress.drafts?.[id]||'';box.innerHTML=`<button class="btn" id="customBack">← 返回题库</button><span class="practice-label">IELTS Writing ${section==='writing1'?'Task 1':'Task 2'} · ${esc(id)}</span><h2>${esc(task.type)}</h2><p class="custom-prompt">${esc(task.prompt).replaceAll('\n','<br>')}</p>${task.chartSpec?`<div class="custom-media">${customChart(task.chartSpec)}</div>`:''}<label for="customDraft">我的作文 · 自动保存在当前学习空间</label><textarea id="customDraft" class="rec-text" rows="14" placeholder="在这里写作文">${esc(text)}</textarea><p id="customWordCount">${text.trim()?text.trim().split(/\s+/).length:0} words</p><div class="row"><button class="btn" id="customCopy">复制题目与作文</button><button class="btn primary" id="customFinish">标记本题完成</button></div>`;
    $('#customDraft').oninput=()=>{const text=$('#customDraft').value;$('#customWordCount').textContent=(text.trim()?text.trim().split(/\s+/).length:0)+' words';progress.drafts[id]=text;save({refresh:false})};
    $('#customCopy').onclick=async()=>{const result=`IELTS Writing ${section==='writing1'?'Task 1':'Task 2'}\nQuestion:\n${task.prompt}\n\nMy Answer:\n${$('#customDraft').value}`;try{await navigator.clipboard.writeText(result);toast('已复制题目与作文')}catch{toast('浏览器不允许自动复制，请手动选取文本')}};
  }
  $('#customBack').onclick=()=>nav('ielts-custom');const recordButton=box.querySelector('[data-go-page="language-skills"]');if(recordButton)recordButton.onclick=()=>nav('language-skills');$('#customFinish').onclick=()=>{if(mockId)completeCustomMockSection(mockId,kind==='speaking'?'speaking':id.startsWith('WT1')?'writing1':'writing2');toast('已记录到本机');nav('ielts-custom')};
}
window.addEventListener('pagehide',()=>{customSpeechToken++;if('speechSynthesis'in window)speechSynthesis.cancel()});
$$('[data-custom-tab]').forEach(button=>button.onclick=()=>{customTab=button.dataset.customTab;renderIeltsCustom()});
$('#customSpeakingInput').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;$('#customSpeakingStatus').textContent='正在本机解析并核对全部数量…';try{let pages;if(/\.pdf$/i.test(file.name)){const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;pages=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),items=(await page.getTextContent()).items;pages.push(items.map(item=>item.str+(item.hasEOL?'\n':' ')).join(''))}}else pages=(await file.text()).split('\f');const {parseSpeakingBank}=await import('./speaking-bank-parser.mjs');const parsed=parseSpeakingBank(pages);await customSpeakingStore(parsed);customSpeaking=parsed;toast('当季口语题库已保存到当前设备');renderIeltsCustom()}catch(error){$('#customSpeakingStatus').textContent=error.message}finally{event.target.value=''}};
if(sessionStorage.getItem('ieltsCustomReturn')){sessionStorage.removeItem('ieltsCustomReturn');setTimeout(()=>nav('ielts-custom'),100)}
else if(state.examEngine.activeSession?.customBankId&&!state.examEngine.activeSession.completedAt){loadIeltsCustom().then(()=>{const session=state.examEngine.activeSession,kind=session.type==='ielts_reading'?'reading':'listening',item=kind==='reading'?customReading(session.customBankId):customListening(session.customBankId);if(item){privateComputerQuestions=buildCustomExamQuestions(kind,item);nav('computer-exam')}}).catch(console.error)}
