const KEY='englishMemoryLab_v1';
const defaultState={docs:[],activeDoc:null,study:{index:0,mode:'full'},logs:{},vocab:{decks:[],activeDeck:null,session:null,builtinInstalled:{},progress:{}},vocabLogs:{},todayChecklist:{},questionEngine:{drafts:{},review:{},checks:{},planTasks:[],activePlanId:null},settings:{speechRate:.9,speechLang:'en-US',apiEndpoint:'',apiModel:'',apiKey:'',vocabBatchSize:'100'}};
let state=load(); state.vocab=state.vocab||{decks:[],activeDeck:null,session:null,builtinInstalled:{},progress:{}}; state.vocab.decks=state.vocab.decks||[]; state.vocab.builtinInstalled=state.vocab.builtinInstalled||{}; state.vocab.progress=state.vocab.progress||{}; state.vocabLogs=state.vocabLogs||{}; state.todayChecklist=state.todayChecklist||{}; state.questionEngine=state.questionEngine||{}; state.questionEngine.drafts=state.questionEngine.drafts||{}; state.questionEngine.review=state.questionEngine.review||{}; state.questionEngine.checks=state.questionEngine.checks||{}; state.questionEngine.planTasks=state.questionEngine.planTasks||[]; state.questionEngine.activePlanId=state.questionEngine.activePlanId||null; state.settings=state.settings||{}; state.settings.vocabBatchSize=state.settings.vocabBatchSize||'100'; let recognition=null; let examQ=0; let vocabAdvanceTimer=null; const builtinDeckCache=new Map(); const deckIndexCache=new WeakMap();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));refreshDashboard()}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function nav(page){const parent={study:'training',vocab:'training',exam:'training',review:'training','preqin-literature':'library',stats:'me',settings:'me'}[page]||page;$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+page));$$('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.page===parent));if(page==='today')renderToday();if(page==='me')renderProfileSummary();if(page==='review')renderReview();if(page==='stats')renderStats();if(page==='exam')renderExam();if(page==='vocab')renderVocabHome();if(page==='preqin-literature')renderPreqinCourse();if(page==='plan')renderCoursePlans();window.scrollTo({top:0,behavior:'smooth'})}
$$('.navbtn').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));
$$('[data-go-page]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.goPage)));
const stop=new Set('the a an and or but if when while to of in on at for from with as is are was were be been being i you he she it we they my your his her our their this that these those do does did have has had can could should would will may might very much more most some any each every about into than then so also not because therefore however instead during after before who whom which what where why how through between according several really make made making get got good great important experience thing things people person'.split(' '));
function splitSentences(t){return (t.replace(/\r/g,'\n').match(/[^.!?。！？\n]+[.!?。！？]+|[^.!?。！？\n]+$/g)||[]).map(s=>s.trim()).filter(s=>/[A-Za-z]/.test(s)&&s.length>5).slice(0,500)}
