const ITALIAN_REVIEW_DAYS=[0,1,3,7,14,30];
let italianDictionaryManifest=null,italianDictionaryWords=[],italianDictionaryIndex=new Map(),italianDictionaryLoaded=new Set(),italianLookupCurrent=null;
state.italianCourse=state.italianCourse||{};state.italianCourse.savedWords=state.italianCourse.savedWords||{};

function italianToken(value){return String(value||'').toLocaleLowerCase('it').normalize('NFKC').replace(/[’‘]/g,"'").replace(/^(?:l['’]|il |lo |la |i |gli |le |un |uno |una )/,'').replace(/^[^a-zà-öø-ÿ]+|[^a-zà-öø-ÿ']+$/gi,'').trim()}
function italianClickableText(text){return String(text||'').split(/([A-Za-zÀ-ÖØ-öø-ÿ]+(?:['’][A-Za-zÀ-ÖØ-öø-ÿ]+)?)/u).map(part=>/^[A-Za-zÀ-ÖØ-öø-ÿ]/u.test(part)?`<button class="italian-lookup-word" data-italian-lookup="${esc(part)}" type="button">${esc(part)}</button>`:esc(part)).join('')}
function indexItalianWords(words){for(const word of words||[]){const key=italianToken(word.word);if(key&&!italianDictionaryIndex.has(key))italianDictionaryIndex.set(key,word);const plural=italianToken(word.plural);if(plural&&!italianDictionaryIndex.has(plural))italianDictionaryIndex.set(plural,{...word,matchedForm:word.plural})}italianDictionaryWords.push(...(words||[]))}
async function loadItalianDictionaryChunk(index=0){if(italianDictionaryLoaded.has(index))return;if(!italianDictionaryManifest)italianDictionaryManifest=await fetch('data/italian-manifest.json').then(response=>{if(!response.ok)throw new Error('Italian 词库索引读取失败');return response.json()});const chunk=italianDictionaryManifest.core.chunks[index];if(!chunk)return;const payload=await fetch(chunk.file).then(response=>{if(!response.ok)throw new Error('Italian 词库分片读取失败');return response.json()});indexItalianWords(payload.words);italianDictionaryLoaded.add(index)}
async function prepareItalianDictionary(){if(italianDictionaryWords.length)return;for(const deckId of ['italian_full','italian_core']){try{const deck=await idbGetDeck(deckId);if(deck?.words?.length){indexItalianWords(deck.words);italianDictionaryLoaded.add(0);italianDictionaryLoaded.add(1);return}}catch{}}await loadItalianDictionaryChunk(0)}
function sourceInfinitive(word){const explicit=italianToken(word?.infinitive);if(explicit)return explicit;const match=String(word?.meaning||'').match(/^([a-zà-öø-ÿ]+)\s*的/u);return match?italianToken(match[1]):''}
async function findItalianWord(raw){await prepareItalianDictionary();const key=italianToken(raw);let word=italianDictionaryIndex.get(key);if(!word&&!italianDictionaryLoaded.has(1)){await loadItalianDictionaryChunk(1);word=italianDictionaryIndex.get(key)}if(!word)return null;const infinitive=sourceInfinitive(word),lemma=infinitive&&italianDictionaryIndex.get(infinitive);return{...word,query:raw,normalized:key,lemma:lemma?.word||infinitive||word.word}}
function italianField(label,value){return value?`<div><dt>${label}</dt><dd>${esc(String(value))}</dd></div>`:''}
async function openItalianLookup(raw){const modal=$('#italianLookupModal'),body=$('#italianLookupBody');modal.classList.add('show');body.innerHTML='<div class="italian-dictionary-loading">正在查询本地 Italian 词库…</div>';$('#italianLookupTitle').textContent=raw;try{const word=await findItalianWord(raw);italianLookupCurrent=word;if(!word){body.innerHTML=`<div class="empty">现有本地词库暂未收录“${esc(raw)}”。没有使用 AI 猜测释义。</div>`;$('#italianSaveWord').style.display='none';return}const saved=state.italianCourse.savedWords[italianToken(word.lemma||word.word)];body.innerHTML=`<div class="italian-meaning">${esc(word.meaning)}</div><dl class="italian-word-fields">${italianField('词条',word.word)}${italianField('原形 / lemma',word.lemma!==word.word?word.lemma:'')}${italianField('词性',word.pos)}${italianField('性别',word.gender)}${italianField('复数',word.plural)}${italianField('不定式',word.infinitive)}${italianField('IPA',word.phonetic)}${italianField('频率排名',word.rank)}</dl>${word.example?`<div class="italian-example"><b>${italianClickableText(word.example)}</b>${word.exampleZh?`<span>${esc(word.exampleZh)}</span>`:''}</div>`:''}`;$('#italianSaveWord').style.display='inline-flex';$('#italianSaveWord').textContent=saved?'移出生词本':'加入生词 / 复习';bindItalianLookupButtons(body)}catch(error){italianLookupCurrent=null;body.innerHTML=`<div class="empty">${esc(error.message)}</div>`;$('#italianSaveWord').style.display='none'}}
function bindItalianLookupButtons(root=document){root.querySelectorAll('[data-italian-lookup]').forEach(button=>button.onclick=event=>{event.stopPropagation();openItalianLookup(button.dataset.italianLookup)})}
function bindItalianHelpers(item,lesson){bindItalianLookupButtons($('#italianExercise'));const text=item.audioTarget||(['fillBlank','wordBank','typeAnswer'].includes(item.type)?item.sentence||item.prompt:'');const exercise=$('#italianExercise');if(text&&exercise&&!exercise.querySelector('.italian-sentence-help'))exercise.insertAdjacentHTML('beforeend',`<button class="btn italian-sentence-help" id="italianSentenceHelp">查看这句的中文辅助</button><div id="italianSentenceHelpResult" class="italian-sentence-help-result" hidden></div>`);if($('#italianSentenceHelp'))$('#italianSentenceHelp').onclick=()=>showItalianSentenceHelp(text);const guide=$('.italian-guide>div');if(guide&&!guide.querySelector('.italian-unit-words')){guide.insertAdjacentHTML('beforeend',`<div class="italian-unit-words"><b>本单元点词查询</b><div>${lesson.unit.words.map(word=>`<button data-italian-lookup="${esc(word.target)}">${esc(word.target)}</button>`).join('')}</div></div>`);bindItalianLookupButtons(guide)}renderItalianSavedWords()}
async function showItalianSentenceHelp(text){const result=$('#italianSentenceHelpResult');result.hidden=false;result.innerHTML='正在查询本地词库…';const tokens=[...new Set(String(text).match(/[A-Za-zÀ-ÖØ-öø-ÿ]+(?:['’][A-Za-zÀ-ÖØ-öø-ÿ]+)?/gu)||[])],rows=[];for(const token of tokens){const word=await findItalianWord(token);rows.push(`<button data-italian-lookup="${esc(token)}"><b>${esc(token)}</b><span>${esc(word?.meaning||'词库暂无释义')}</span></button>`)}result.innerHTML=`<div>${rows.join('')}</div><small>这里是逐词中文辅助，不是整句翻译。整句翻译接口暂未启用。</small>`;bindItalianLookupButtons(result)}
function italianDueWords(){return Object.values(state.italianCourse?.savedWords||{}).filter(word=>(word.due||0)<=now())}
function italianDueCount(){return italianDueWords().length}
function renderItalianSavedWords(){const box=$('#italianSavedWords');if(!box)return;const saved=Object.values(state.italianCourse.savedWords||{}),due=italianDueWords();box.innerHTML=`<div class="row between"><b>生词与复习</b><span class="tag">${due.length} 到期</span></div>${saved.length?saved.slice(0,12).map(word=>`<div class="italian-saved-row"><button data-italian-lookup="${esc(word.word)}"><b>${esc(word.word)}</b><small>${esc(compactMeaning(word.meaning))}</small></button><button data-italian-review="${esc(word.key)}" title="记住了">✓</button></div>`).join(''):'<p class="sub">点击课程里的意大利语单词，可加入这里。</p>'}`;bindItalianLookupButtons(box);$$('[data-italian-review]').forEach(button=>button.onclick=()=>rateItalianSavedWord(button.dataset.italianReview,'good'))}
function rateItalianSavedWord(key,rating){const word=state.italianCourse.savedWords[key];if(!word)return;const current=Number(word.reviewStep)||0,step=rating==='again'?0:Math.min(ITALIAN_REVIEW_DAYS.length-1,current+1);word.reviewStep=step;word.last=now();word.due=now()+ITALIAN_REVIEW_DAYS[step]*86400000;save();renderItalianSavedWords();toast(rating==='again'?'已加入今天复习':`已记录 · Day ${ITALIAN_REVIEW_DAYS[step]}`)}
function toggleItalianSavedWord(){if(!italianLookupCurrent)return;const key=italianToken(italianLookupCurrent.lemma||italianLookupCurrent.word),existing=state.italianCourse.savedWords[key];if(existing)delete state.italianCourse.savedWords[key];else state.italianCourse.savedWords[key]={key,word:italianLookupCurrent.word,lemma:italianLookupCurrent.lemma,meaning:italianLookupCurrent.meaning,pos:italianLookupCurrent.pos||'',gender:italianLookupCurrent.gender||'',plural:italianLookupCurrent.plural||'',infinitive:italianLookupCurrent.infinitive||'',phonetic:italianLookupCurrent.phonetic||'',reviewStep:0,due:now(),last:0,addedAt:now()};save();$('#italianLookupModal').classList.remove('show');renderItalianSavedWords();toast(existing?'已移出生词本':'已加入生词和今日复习')}

$('#closeItalianLookup').onclick=()=>$('#italianLookupModal').classList.remove('show');$('#italianLookupSpeak').onclick=()=>italianLookupCurrent&&speak(italianLookupCurrent.word,{userInitiated:true,lang:'it-IT'});$('#italianSaveWord').onclick=toggleItalianSavedWord;$('#italianLookupModal').onclick=event=>{if(event.target.id==='italianLookupModal')event.currentTarget.classList.remove('show')};
