const ENGLISH_RELATION_DECKS=new Set(['toeic_core','toeic_full','ielts_core','kaoyan_core']);
let englishRelationsPromise=null;
const englishRelationShardPromises=new Map();

function isEnglishRelationDeck(deck){return !!deck&&(!deck.builtin||ENGLISH_RELATION_DECKS.has(deck.id))}
function englishRelationShardKey(word){const first=normWord(word).charAt(0);return /[a-z]/.test(first)?first:'_'}
function loadEnglishRelationManifest(){if(!englishRelationsPromise)englishRelationsPromise=fetch(new URL('data/english-word-relations.json',document.baseURI),{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('English relations HTTP '+response.status);return response.json()}).catch(error=>{console.warn(error);return {entries:{}}});return englishRelationsPromise}
async function loadEnglishRelations(word){const manifest=await loadEnglishRelationManifest();if(manifest.entries)return manifest;const shard=manifest.shards?.[englishRelationShardKey(word)];if(!shard)return {...manifest,entries:{}};if(!englishRelationShardPromises.has(shard.file))englishRelationShardPromises.set(shard.file,fetch(new URL(shard.file,document.baseURI),{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('English relation shard HTTP '+response.status);return response.json()}).catch(error=>{console.warn(error);return {entries:{}}}));const data=await englishRelationShardPromises.get(shard.file);return {...manifest,entries:data.entries||{}}}
function englishRelationFor(data,word){return data?.entries?.[normWord(word)]||null}
function relationItems(items,kind){if(!items?.length)return'';if(kind==='family')return items.map(item=>`<li><b>${esc(item.word)}</b>${item.pos?` · ${esc(item.pos)}`:''}${item.relation?` · ${esc(item.relation)}`:''}</li>`).join('');if(kind==='collocations')return items.map(item=>`<li><b>${esc(item.text)}</b>${item.translation?` · ${esc(item.translation)}`:''}${item.note?`<small>${esc(item.note)}</small>`:''}</li>`).join('');return items.map(item=>`<li><b>${esc(item.word)}</b>${item.difference||item.sense||item.note?`<small>${esc(item.difference||item.sense||item.note)}</small>`:''}</li>`).join('')}
function englishRelationAttribution(entry,data){const sources=(entry.sources||[entry.source]).filter(Boolean),meta=data.sources||[];const links=sources.map(url=>{const item=meta.find(source=>url.startsWith(source.url));return `<a href="${esc(url)}" target="_blank" rel="noopener">${esc(item?.name||'来源')}</a>`});const licenses=[...new Set(meta.filter(source=>sources.some(url=>url.startsWith(source.url))).map(source=>source.license))];return `${links.join(' / ')}${licenses.length?` · ${esc(licenses.join(' / '))}`:''}`}
function englishRelationPanel(entry,data){if(!entry?.relations)return'';const groups=[['family','词族'],['synonyms','近义词'],['collocations','常用搭配'],['confusables','易混词']].filter(([key])=>entry.relations[key]?.length);if(!groups.length)return'';return `<details class="vocab-relations english-relations"><summary>关联词</summary><div class="english-relation-groups">${groups.map(([key,label])=>`<details><summary>${label} ${entry.relations[key].length}</summary><ul>${relationItems(entry.relations[key],key)}</ul></details>`).join('')}</div><small class="relation-source">来源：${englishRelationAttribution(entry,data)}</small></details>`}

const baseShowVocabDetail21=showVocabDetail;
showVocabDetail=async function(id){const deck=vocabBrowserState.deck,word=wordById(deck,id);baseShowVocabDetail21(id);if(!word||!isEnglishRelationDeck(deck))return;$('#vocabDetailBody').querySelectorAll(':scope > .vocab-relations').forEach(node=>node.remove());const data=await loadEnglishRelations(word.word),entry=englishRelationFor(data,word.word);if(vocabBrowserState.detail!==word||!$('#vocabDetailModal').classList.contains('show'))return;const html=englishRelationPanel(entry,data),example=$('#vocabDetailBody .vocab-detail-example');if(html&&example)example.insertAdjacentHTML('beforebegin',html)};
