const LOCAL_TEACHER_STRATEGIES={
  ielts_reading:{title:'IELTS Reading',steps:['先读题干并圈出定位词','回原文找同义替换，而不是只找原词','T/F/NG 分清“相反”和“没有提到”','Matching 先排除已确定项','警惕绝对化、偷换范围和因果倒置']},
  ielts_listening:{title:'IELTS Listening',steps:['播放前预测答案内容与词性','留意转折、顺序和话题切换信号词','说话人自我纠正时以后面的信息为准','检查拼写、单复数和数字','严格遵守题目 word limit']},
  toeic_part_1:{title:'TOEIC Part 1',steps:['先扫人物、动作和位置','区分正在发生与静态状态','警惕发音相近但语义无关的词']},toeic_part_2:{title:'TOEIC Part 2',steps:['先判断问句类型','回答可以是间接回应','警惕重复题干词的干扰项']},toeic_part_3:{title:'TOEIC Part 3',steps:['播放前快速读题','抓人物关系、目的和下一步','注意转折后的真实决定']},toeic_part_4:{title:'TOEIC Part 4',steps:['先识别公告或讲话场景','按题号顺序跟踪信息','重点听时间、地点与行动要求']},toeic_part_5:{title:'TOEIC Part 5',steps:['先判断空格的句法功能','再看词性、时态和主谓一致','最后检查固定搭配与连接词']},toeic_part_6:{title:'TOEIC Part 6',steps:['先确定整篇体裁与目的','用前后句检查代词和连接关系','句子插入题看逻辑衔接']},toeic_part_7:{title:'TOEIC Part 7',steps:['先看题目再定位文章','区分原文信息与推断','多篇阅读核对人物、时间和文件关系']}
};
const WRONG_REASON_LABELS={locating:'定位',paraphrase:'同义替换',vocabulary:'词汇',distractor:'干扰项',spelling:'拼写',number:'单复数',careless:'粗心',time:'时间不足'};
function teacherStrategy(question){return LOCAL_TEACHER_STRATEGIES[question.type]||{title:'本地答题策略',steps:['先定位题目证据','排除不符合题干的选项','提交前复核答案格式']}}
function localTeacherHint(question){const strategy=teacherStrategy(question);return `${strategy.title}：${strategy.steps.join(' → ')}`}
function expectedExamAnswer(question){return Array.isArray(question.answer)?question.answer[0]:question.answer}
function toggleWrongReason(questionId,reason){const wrong=state.examEngine.wrong[questionId];if(!wrong)return;wrong.reasons=Array.isArray(wrong.reasons)?wrong.reasons:[];wrong.reasons=wrong.reasons.includes(reason)?wrong.reasons.filter(item=>item!==reason):[...wrong.reasons,reason];save({refresh:false});$$(`[data-wrong-question="${questionId}"] [data-wrong-reason]`).forEach(button=>button.classList.toggle('active',wrong.reasons.includes(button.dataset.wrongReason)))}
function renderLocalTeacherResult(session,questions){const wrongQuestions=questions.filter(question=>!isObjectiveAnswerCorrect(question,session.answers[question.id]||''));$('#page-computer-exam').innerHTML=`<div class="computer-result-wrap"><article class="card computer-result"><span class="practice-label">本地判分完成</span><h2>${session.result.correct} / ${session.result.total}</h2><p>正确率 ${session.result.percent}% · ${wrongQuestions.length?'请给错题标记原因，之后复习会保留这些记录。':'本轮全部正确。'}</p></article>${wrongQuestions.map(question=>{const strategy=teacherStrategy(question),selected=state.examEngine.wrong[question.id]?.reasons||[];return `<article class="card local-teacher-review" data-wrong-question="${question.id}"><div class="row between"><span class="practice-label">${esc(strategy.title)}</span><b>${esc(question.section||'错题分析')}</b></div><h3>${esc(question.stem)}</h3><div class="answer-compare"><span>你的答案：<b>${esc(String(session.answers[question.id]||'未作答'))}</b></span><span>参考答案：<b>${esc(String(expectedExamAnswer(question)))}</b></span></div>${question.explanation?`<p class="teacher-explanation">${esc(question.explanation)}</p>`:''}<ol>${strategy.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><div class="wrong-reason-picker"><span>这次错因：</span>${Object.entries(WRONG_REASON_LABELS).map(([reason,label])=>`<button class="${selected.includes(reason)?'active':''}" data-wrong-reason="${reason}">${label}</button>`).join('')}</div></article>`}).join('')}<button class="btn primary finish-teacher-review" id="finishComputerExam">返回考试训练</button></div>`;$$('[data-wrong-reason]').forEach(button=>button.onclick=()=>toggleWrongReason(button.closest('[data-wrong-question]').dataset.wrongQuestion,button.dataset.wrongReason));$('#finishComputerExam').onclick=()=>{state.examEngine.activeSession=null;save({immediate:true,refresh:false});location.reload()}}
