const REVIEW_DAYS=[0,1,3,7,14,30],WEEKDAY_LABELS=['日','一','二','三','四','五','六'];
function projectById(id){return state.projects.find(project=>project.id===id)||null}
function projectPage(id){return id==='chinese'?'preqin-literature':id==='italiano'?'italiano':['toeic','ielts','kaoyan-english'].includes(id)?'vocab':'library'}
function projectCountdown(project){if(!project?.examDate)return null;const today=new Date();today.setHours(0,0,0,0);const exam=new Date(project.examDate+'T00:00:00');return Math.max(0,Math.ceil((exam-today)/86400000))}
function generatedTodayTasks(){
  const projects=new Map(visibleProjects().map(project=>[project.id,project])),weekday=new Date().getDay(),tasks=[],due=Math.min(state.planner.maxDailyReviews,dueCards().length+vocabDueCount());
  if(due>0)tasks.push({id:'review-'+dayKey(),projectId:'review',name:'到期复习',meta:`优先完成 ${due} 项 · Day 0/1/3/7/14/30`,minutes:Math.max(5,Math.ceil(due*.4)),color:'red',glyph:'↻',page:dueCards().length?'review':'vocab'});
  state.planner.schedules.filter(schedule=>schedule.enabled&&schedule.weekdays.includes(weekday)&&projects.has(schedule.projectId)).forEach(schedule=>{const project=projects.get(schedule.projectId),amount=Math.max(1,Number(schedule.amount)||1),minutes=schedule.mode==='minutes'?amount:Math.max(5,Math.ceil(amount*(schedule.unit==='词'?.45:3)));tasks.push({id:'schedule-'+schedule.id,name:schedule.title,meta:schedule.mode==='minutes'?`学习 ${amount} 分钟`:`${amount} ${schedule.unit}`,minutes,color:project.color||'violet',glyph:project.glyph||project.name.slice(0,1),page:projectPage(project.id),projectId:project.id})});
  state.questionEngine.planTasks.filter(task=>!task.completed&&projects.has(task.projectId)).forEach(task=>tasks.push({id:'course-'+task.id,name:task.title,meta:`已完成 ${(task.questionIds||[]).length} / ${task.target} 题`,minutes:Math.max(10,task.target*5),color:projects.get(task.projectId).color||'amber',glyph:projects.get(task.projectId).glyph||'文',page:'preqin-literature',projectId:task.projectId}));
  return tasks;
}
function renderPlanner(){
  if(!$('#planProject'))return;const projects=visibleProjects();$('#planProject').innerHTML=projects.map(project=>`<option value="${project.id}">${esc(project.name)}</option>`).join('');$('#maxDailyReviews').value=state.planner.maxDailyReviews;
  $('#examDateList').innerHTML=projects.map(project=>`<label class="exam-date-row"><span class="project-glyph ${project.color||'violet'}">${esc(project.glyph||project.name.slice(0,1))}</span><span><b>${esc(project.name)}</b><small>${project.examDate?'距离考试 D-'+projectCountdown(project):'未设置考试日期'}</small></span><input class="field" type="date" data-exam-project="${project.id}" value="${project.examDate||''}"></label>`).join('')||'<div class="empty">先到“我的”显示学习项目。</div>';
  $$('[data-exam-project]').forEach(input=>input.onchange=()=>{const project=projectById(input.dataset.examProject);if(!project)return;project.examDate=input.value||null;save();renderPlanner();renderToday()});
  const schedules=state.planner.schedules;$('#scheduleList').innerHTML=schedules.length?schedules.map(schedule=>{const project=projectById(schedule.projectId),days=schedule.weekdays.map(day=>WEEKDAY_LABELS[day]).join('、');return `<article class="schedule-row ${schedule.enabled?'':'paused'}"><span class="project-glyph ${project?.color||'violet'}">${esc(project?.glyph||'•')}</span><div><b>${esc(schedule.title)}</b><small>${esc(project?.name||'已归档项目')} · ${schedule.mode==='minutes'?schedule.amount+' 分钟':schedule.amount+' '+schedule.unit} · 周${days}</small></div><span>${schedule.enabled?'已启用':'已暂停'}</span><div class="row"><button class="btn" data-schedule-toggle="${schedule.id}">${schedule.enabled?'暂停':'启用'}</button><button class="btn danger" data-schedule-delete="${schedule.id}">删除</button></div></article>`}).join(''):'<div class="empty">还没有每周计划。</div>';
  $$('[data-schedule-toggle]').forEach(button=>button.onclick=()=>{const schedule=schedules.find(item=>item.id===button.dataset.scheduleToggle);if(schedule){schedule.enabled=!schedule.enabled;save();renderPlanner();renderToday()}});$$('[data-schedule-delete]').forEach(button=>button.onclick=()=>{if(!confirm('删除这条每周计划？'))return;state.planner.schedules=schedules.filter(item=>item.id!==button.dataset.scheduleDelete);save();renderPlanner();renderToday()});
}
$('#planMode').onchange=()=>{$('#planUnit').disabled=$('#planMode').value==='minutes';if($('#planMode').value==='minutes')$('#planUnit').value='分钟'};
$('#maxDailyReviews').onchange=()=>{state.planner.maxDailyReviews=Math.max(0,Math.min(999,Number($('#maxDailyReviews').value)||0));save();renderToday();toast('复习上限已保存')};
$('#addPlanSchedule').onclick=()=>{const projectId=$('#planProject').value,title=$('#planTitle').value.trim(),amount=Math.max(1,Number($('#planAmount').value)||1),mode=$('#planMode').value,unit=mode==='minutes'?'分钟':($('#planUnit').value.trim()||'项'),weekdays=$$('.weekday-picker input:checked').map(input=>Number(input.value));if(!projectId||!title)return toast('请选择项目并填写任务名称');if(!weekdays.length)return toast('至少选择一个学习日');state.planner.schedules.push({id:'schedule-'+Date.now().toString(36),projectId,title:title.slice(0,50),mode,amount,unit:unit.slice(0,16),weekdays,enabled:true,createdAt:Date.now()});$('#planTitle').value='';save();renderPlanner();renderToday();toast('学习计划已添加')};
const previousRenderCoursePlans=renderCoursePlans;renderCoursePlans=async function(){renderPlanner();return previousRenderCoursePlans()};
renderPlanner();renderToday();
