const vocabBrowserState={deck:null,query:'',filter:'all',page:1,pageSize:50,detail:null};

function vocabDayStart(){const d=new Date();d.setHours(0,0,0,0);return d.getTime()}
function vocabExampleData(word){const raw=word?.example;if(raw&&typeof raw==='object')return {sentence:String(raw.sentence||''),translation:String(raw.translation||word.exampleZh||''),source:String(raw.source||''),generated:raw.generated===true};return {sentence:String(raw||''),translation:String(word?.exampleZh||''),source:String(word?.exampleSource||''),generated:word?.exampleGenerated===true}}
function vocabWordStatus(word){if((word.level||0)>0&&(word.due||0)<=now())return {key:'due',label:'待复习'};if((word.level||0)>=3)return {key:'mastered',label:'已掌握'};if((word.wrong||0)>0)return {key:'wrong',label:'错词'};if((word.seen||0)>0)return {key:'learning',label:'学习中'};return {key:'unlearned',label:'未学'}}
function vocabDeckStats(deck){const total=deck.words.length,today=vocabDayStart();let learned=0,mastered=0,due=0,wrong=0,todayNew=0;for(const word of deck.words){if((word.seen||0)>0)learned++;if((word.level||0)>=3)mastered++;if((word.level||0)>0&&(word.due||0)<=now())due++;if((word.wrong||0)>0)wrong++;if((word.firstSeen||0)>=today)todayNew++}const cursor=Math.max(0,Math.min(total-1,Number(state.vocab.resume?.[deck.id])||0));let next=deck.words.findIndex((word,index)=>index>=cursor&&!(word.seen||0));if(next<0)next=deck.words.findIndex(word=>!(word.seen||0));const position=next<0?total:next+1;return {total,learned,unlearned:total-learned,mastered,due,wrong,todayNew,position,percent:total?Math.round(mastered/total*100):0}}
function vocabStatsHTML(stats){return `<div class="vocab-deck-progress"><div class="vocab-progress-head"><b>掌握 ${stats.percent}%</b><span>新词位置 ${stats.position} / ${stats.total}</span></div><div class="progress"><i style="width:${stats.percent}%"></i></div><div class="vocab-stat-grid"><span><b>${stats.total}</b>总词数</span><span><b>${stats.learned}</b>已学</span><span><b>${stats.unlearned}</b>未学</span><span><b>${stats.mastered}</b>已掌握</span><span><b>${stats.due}</b>待复习</span><span><b>${stats.wrong}</b>错词/强化中</span><span><b>${stats.todayNew}</b>今日新学</span></div></div>`}
function nextUnlearnedWords(deck){const total=deck.words.length,cursor=Math.max(0,Math.min(total-1,Number(state.vocab.resume?.[deck.id])||0));return [...deck.words.slice(cursor),...deck.words.slice(0,cursor)].filter(word=>!(word.seen||0))}
function startVocabContinue(deckId){const deck=state.vocab.decks.find(item=>item.id===deckId)||builtinDeckCache.get(deckId);if(!deck)return;if(state.vocab.activeDeck===deckId&&state.vocab.session&&currentVocabWord()){renderVocabSession();$('#vocabTrainer').style.display='block';$('#vocabTrainer').scrollIntoView({behavior:'smooth',block:'start'});return}let pool=nextUnlearnedWords(deck),size=state.settings.vocabBatchSize||'100';if(!pool.length){const due=deck.words.filter(word=>(word.level||0)>0&&(word.due||0)<=now());if(due.length)return startVocabScreen(deckId,true);return toast('这个词库已经没有未学单词')}if(size!=='all')pool=pool.slice(0,Math.max(4,Number(size)||100));pool.forEach(word=>{word.sessionCorrect=0;word.sessionWrong=0});state.vocab.activeDeck=deck.id;state.vocab.session={phase:'screen',queue:pool.map(word=>word.id),participants:pool.map(word=>word.id),index:0,started:now(),questionStart:now(),resumeSequential:true,screen:{fast:0,steady:0,slow:0,wrong:0},reinforceTotal:0,reinforceDone:0};save();$('#vocabTrainer').style.display='block';renderVocabSession();setTimeout(()=>$('#vocabTrainer').scrollIntoView({behavior:'smooth',block:'start'}),30)}
function recordVocabFirstSeenAndResume(deck,word,wasNew,session){if(!deck||!word)return;if(wasNew&&!word.firstSeen)word.firstSeen=now();if(session?.resumeSequential&&wasNew){const index=deck.words.indexOf(word);if(index>=0)state.vocab.resume[deck.id]=Math.min(deck.words.length,index+1)}if(deck.builtin)saveBuiltinProgress(deck,word);save()}

const baseAnswerVocabChoice=answerVocabChoice;
answerVocabChoice=function(selected,button,forceUnknown=false){const deck=activeVocabDeck(),word=currentVocabWord(),session=state.vocab.session,wasNew=!!word&&!(word.seen||0);baseAnswerVocabChoice(selected,button,forceUnknown);recordVocabFirstSeenAndResume(deck,word,wasNew,session)};
const baseCheckVocabSpell=checkVocabSpell;
checkVocabSpell=function(showOnly=false){const deck=activeVocabDeck(),word=currentVocabWord(),session=state.vocab.session,wasNew=!!word&&!(word.seen||0);baseCheckVocabSpell(showOnly);recordVocabFirstSeenAndResume(deck,word,wasNew,session)};
const baseRenderVocabChoice=renderVocabChoice;
renderVocabChoice=function(deck,word){baseRenderVocabChoice(deck,word);const example=vocabExampleData(word),box=$('#vocabExample');if(box)box.innerHTML=example.sentence?`${esc(example.sentence)}${example.translation?`<small>${esc(example.translation)}</small>`:''}`:'<span>暂无例句</span>'};
const baseRenderVocabSession=renderVocabSession;
renderVocabSession=function(){baseRenderVocabSession();const box=$('#vocabExample'),session=state.vocab.session;if(box&&session?.phase==='spell')box.innerHTML=''};

function renderVocabCardEnhancements(){for(const meta of visibleBuiltinMetas()){const card=document.querySelector(`[data-builtin-card="${meta.id}"]`);if(!card)continue;const deck=builtinDeckCache.get(meta.id),stats=deck?vocabDeckStats(deck):{total:meta.expected,learned:0,unlearned:meta.expected,mastered:0,due:0,wrong:0,todayNew:0,position:1,percent:0};card.querySelector('.vocab-deck-progress')?.remove();card.querySelector('.vocab-extra-actions')?.remove();card.querySelector('.source')?.insertAdjacentHTML('beforebegin',vocabStatsHTML(stats));card.insertAdjacentHTML('beforeend',`<div class="row vocab-extra-actions"><button class="btn primary" data-vcontinue="${meta.id}">继续学习</button><button class="btn" data-vquick="${meta.id}">快速筛词</button><button class="btn" data-vbrowse="${meta.id}">查看完整词库</button></div>`)}for(const deck of state.vocab.decks){const button=document.querySelector(`[data-vscreen="${deck.id}"]`),card=button?.closest('.vocab-deck');if(!card)continue;card.querySelector('.vocab-deck-progress')?.remove();card.querySelector('.vocab-extra-actions')?.remove();card.firstElementChild?.insertAdjacentHTML('beforeend',vocabStatsHTML(vocabDeckStats(deck)));card.insertAdjacentHTML('beforeend',`<div class="row vocab-extra-actions"><button class="btn primary" data-vcontinue="${deck.id}">继续学习</button><button class="btn" data-vquick="${deck.id}">快速筛词</button><button class="btn" data-vbrowse="${deck.id}">查看完整词库</button></div>`)}$$('[data-vcontinue]').forEach(button=>button.onclick=async()=>{const id=button.dataset.vcontinue,deck=state.vocab.decks.find(item=>item.id===id)||await installBuiltin(id,false);if(deck)startVocabContinue(id)});$$('[data-vquick]').forEach(button=>button.onclick=async()=>{const id=button.dataset.vquick,deck=state.vocab.decks.find(item=>item.id===id)||await installBuiltin(id,false);if(deck)startVocabQuick(deck)});$$('[data-vbrowse]').forEach(button=>button.onclick=async()=>{const id=button.dataset.vbrowse,deck=state.vocab.decks.find(item=>item.id===id)||await installBuiltin(id,false);if(deck)openVocabBrowser(deck)})}
const baseRenderVocabHome=renderVocabHome;
renderVocabHome=function(){baseRenderVocabHome();renderVocabCardEnhancements()};

function openVocabBrowser(deck){vocabBrowserState.deck=deck;vocabBrowserState.query='';vocabBrowserState.filter='all';vocabBrowserState.page=1;$('#vocabBrowserSearch').value='';$('#vocabBrowserFilter').value='all';$('#vocabBrowserTitle').textContent=deck.title+' · 完整词库';$('#vocabBrowser').hidden=false;renderVocabBrowser();$('#vocabBrowser').scrollIntoView({behavior:'smooth',block:'start'})}
function vocabBrowserWords(){const deck=vocabBrowserState.deck;if(!deck)return [];const query=normWord(vocabBrowserState.query);return deck.words.filter(word=>{const filter=vocabBrowserState.filter;if(filter==='unlearned'&&(word.seen||0)>0)return false;if(filter==='learning'&&!((word.seen||0)>0&&(word.level||0)<3))return false;if(filter==='mastered'&&(word.level||0)<3)return false;if(filter==='due'&&!((word.level||0)>0&&(word.due||0)<=now()))return false;if(filter==='wrong'&&!(word.wrong||0))return false;if(!query)return true;return normWord(word.word).includes(query)||String(word.meaning||'').toLowerCase().includes(query)})}
function renderVocabBrowser(){const words=vocabBrowserWords(),pages=Math.max(1,Math.ceil(words.length/vocabBrowserState.pageSize));vocabBrowserState.page=Math.min(vocabBrowserState.page,pages);const start=(vocabBrowserState.page-1)*vocabBrowserState.pageSize,visible=words.slice(start,start+vocabBrowserState.pageSize),deck=vocabBrowserState.deck;$('#vocabBrowserSummary').textContent=`${words.length} / ${deck.words.length} 词 · 保持原词库顺序`;$('#vocabBrowserList').innerHTML=visible.length?visible.map(word=>{const index=deck.words.indexOf(word)+1,status=vocabWordStatus(word);return `<button class="vocab-browser-row" data-vdetail="${esc(word.id)}"><span>${index}</span><b>${esc(word.word)}</b><small>${esc(word.meaning)}</small><em class="vocab-status ${status.key}">${status.label}</em></button>`}).join(''):'<div class="empty">没有符合条件的单词</div>';$('#vocabBrowserPage').textContent=`第 ${vocabBrowserState.page} / ${pages} 页`;$('#vocabBrowserPrev').disabled=vocabBrowserState.page<=1;$('#vocabBrowserNext').disabled=vocabBrowserState.page>=pages;$$('[data-vdetail]').forEach(button=>button.onclick=()=>showVocabDetail(button.dataset.vdetail))}
function vocabWordRelations(deck,word){const family=(word.wordFamily||[]).map(item=>({word:item.word,pos:item.pos||'',relation:item.relation||''}));if(word.infinitive&&normWord(word.infinitive)!==normWord(word.word))family.push({word:word.infinitive,pos:'',relation:'不定式'});if(word.plural&&normWord(word.plural)!==normWord(word.word))family.push({word:word.plural,pos:'',relation:'复数'});for(const item of deck.words){if(family.length>=20)break;if(item.id!==word.id&&normWord(item.infinitive)===normWord(word.word))family.push({word:item.word,pos:item.pos||'',relation:'词形'})}const seen=new Set();return {family:family.filter(item=>item.word&&!seen.has(normWord(item.word))&&seen.add(normWord(item.word))),confusables:Array.isArray(word.confusables)?word.confusables:[]}}
function showVocabDetail(id){const deck=vocabBrowserState.deck,word=wordById(deck,id);if(!word)return;vocabBrowserState.detail=word;const status=vocabWordStatus(word),example=vocabExampleData(word),relations=vocabWordRelations(deck,word),fields=[["中文",word.meaning],["词性",word.pos],["IPA",word.phonetic],["Gender",word.gender],["Plural",word.plural],["Infinitive",word.infinitive]].filter(([,value])=>value),family=relations.family.length?relations.family.map(item=>`<li><b>${esc(item.word)}</b>${item.pos?` · ${esc(item.pos)}`:''}${item.relation?` · ${esc(item.relation)}`:''}</li>`).join(''):'<li class="sub">暂无</li>',confusables=relations.confusables.length?relations.confusables.map(item=>`<li><b>${esc(item.word)}</b>${item.note?` · ${esc(item.note)}`:''}</li>`).join(''):'<li class="sub">暂无</li>';$('#vocabDetailTitle').textContent=word.word;$('#vocabDetailBody').innerHTML=`<div class="vocab-detail-fields">${fields.map(([label,value])=>`<div><span>${label}</span><b>${esc(value)}</b></div>`).join('')}<div><span>学习状态</span><b>${status.label}</b></div><div><span>快速筛词</span><b>${({known:'认识',fuzzy:'模糊',unknown:'不认识'})[word.quickStatus]||'未筛'}</b></div></div><details class="vocab-relations"><summary>词族 / 词形</summary><ul>${family}</ul></details><details class="vocab-relations"><summary>易混词</summary><ul>${confusables}</ul></details><div class="vocab-detail-example"><span>例句</span>${example.sentence?`<p>${esc(example.sentence)}</p>${example.translation?`<small>${esc(example.translation)}</small>`:''}${example.source?`<small>来源：${esc(example.source)}</small>`:''}`:'<p class="sub">暂无例句</p>'}</div>`;$('#vocabDetailModal').classList.add('show')}
$('#vocabBrowserSearch').oninput=e=>{vocabBrowserState.query=e.target.value;vocabBrowserState.page=1;renderVocabBrowser()};
$('#vocabBrowserFilter').onchange=e=>{vocabBrowserState.filter=e.target.value;vocabBrowserState.page=1;renderVocabBrowser()};
$('#vocabBrowserPrev').onclick=()=>{vocabBrowserState.page--;renderVocabBrowser()};
$('#vocabBrowserNext').onclick=()=>{vocabBrowserState.page++;renderVocabBrowser()};
$('#closeVocabBrowser').onclick=()=>{$('#vocabBrowser').hidden=true};
$('#closeVocabDetail').onclick=()=>{$('#vocabDetailModal').classList.remove('show')};
$('#vocabDetailSpeak').onclick=()=>{if(vocabBrowserState.detail)speak(vocabBrowserState.detail.word,{lang:vocabBrowserState.deck?.speechLang,userInitiated:true})};
